### ISSUE TITLE
Feature request - subscript & superscript

### ISSUE THREAD

**Issue by MichaelSavin** [jpuri/react-draft-wysiwyg#1]
I can't find an example subscript & superscript implementation on Draft.js

**Comment by jpuri** [comment]
That should be possible as inline style. I will spend some time to check this out!

Thanks

**Comment by MichaelSavin** [comment]
:+1:

**Comment by jpuri** [comment]
@MichaelSavin: I have added option of sub-script and super-script and also remove styling to the editor.

After a round of testing I will release stable 1.0 ready for prod use.

**Comment by MichaelSavin** [comment]
@jpuri Thanks!

**Comment by jpuri** [comment]
Hi @MichaelSavin, I am closing the issue since its completed now.
