### ISSUE TITLE
Feature: It would be amazing to change the default target="_self" automatically.

### ISSUE THREAD

**Issue by eddsaura** [jpuri/react-draft-wysiwyg#1003]
I saw in the documentation that I can change the default behaviour of the link target but just in the toolbar.

` toolbar={{
          link: {
            defaultTargetOption: '_blank',
          },
        }}`

I'd like to accomplish a _blank target anchor always, without letting the user choose, just paste the url and make it an external anchor.

I had to do it with regex replace.

Thanks a lot.

**Comment by henperi** [comment]
How did you achieve this?

**Comment by eddsaura** [comment]
> How did you achieve this?

Hey man, sorry for being late.

I just did this.

```js
.replace(/target="_self"/g, 'target="_blank"')
```
Finding that string and replacing it with
