### ISSUE TITLE
Img tag is not inserted after i resolve the response 

### ISSUE THREAD

**Issue by aminkhorrami** [jpuri/react-draft-wysiwyg#1011]
when i upload an image , via upload uploadImageCallBack , i resolve the url ( in a correct format like the documents ) but somehow my img tag is not updated into the EditortState ! what is the problem ? 

`uploadImageCallBack = file => {

    return new Promise((resolve, reject) => {

      const form = new FormData();

      form.append("img", file);

      axios({
        method: "PATCH",

        url: this.props.uploadURl,

        headers: {

          "Content-Type": "multipart/form-data",

          Authorization: `Bearer ${this.props.token}`

        },

        data: form

      })
        .then(response => {

          if (response.status === 200) {

            const file = {

              data: {

                link: `${process.env.REACT_APP_ENDPOINT}${response.data.imgs[0]}`,

            }

          }
            resolve(file);

          }
       
 })
        .catch(err => {

          reject(err);

          console.log(err);
        });
    });
  };`

**Comment by juansa91** [comment]
hey @aminkhorrami, sorry to bother you at this point in time but since you closed the issue may i ask how you resolved it ? Im having the same problem, thank you!!
