### ISSUE TITLE
New font family

### ISSUE THREAD

**Issue by erenerozan** [jpuri/react-draft-wysiwyg#1026]
Hi everyone
how can i add a **new** font in this editor?

**Comment by jrohlandt** [comment]
You can include the fonts in your css. E.g. import some Google fonts. 
Then add them to the toolbar like this: 
`<Editor
              ...
              toolbar={{
                fontFamily: {
                  options: ['Roboto', 'Oswald'],
                  className: undefined,
                  component: undefined,
                  dropdownClassName: undefined,
                },
              }}
            />`

**Comment by erenerozan** [comment]
Thank you @jrohlandt
