### ISSUE TITLE
Is there any way to make the editor responsive?

### ISSUE THREAD

**Issue by jrohlandt** [jpuri/react-draft-wysiwyg#1032]
I am looking for a editor that can be made responsive. Mainly I want to use em or rem for the user selectable font sizes.

Is there anyway to do that with this editor or even draftjs directly?

**Comment by jrohlandt** [comment]
Ok think I see how it can be done. Any advice would still be appreciated. Thanks

**Comment by potamir** [comment]
@jrohlandt can you share how is your solution for this? I'm also a bit stuck to make it responsive for mobile display. Thank You!

**Comment by jrohlandt** [comment]
@potamir, I ended up moving on to other tasks in my project so I didn't figure it out yet. I will get back to the editor in a week or two and I will let you know the result.
