### ISSUE TITLE
Controlled content with EditorState?

### ISSUE THREAD

**Issue by devnetf** [jpuri/react-draft-wysiwyg#104]
It seems that currently only contentState is supported. It is difficult to reset the text field after user pressed submit button with uncontrolled component.

Thanks!

**Comment by jpuri** [comment]
@devnetf: you can reset content using contentState property, check docs or this issue for details: https://github.com/jpuri/react-draft-wysiwyg/issues/84

**Comment by devnetf** [comment]
@jpuri  In order to reset properly with react, I need to make the editor a controlled component. However, contentState only keep track of the RawDraftContentState and not the EditorState. Hence, the cursor position was not remembered. As I type the cursor keep coming back to the beginning. Why EditorState is not exposed?

**Comment by jpuri** [comment]
Changing editor content was actually not requirement from editor initially what it was developed.
But I see your point, I will soon make this change.

**Comment by jdpagley** [comment]
I'm having the same problem.

**Comment by jpuri** [comment]
I will fix it soon @jdpagley , @devnetf.

**Comment by jpuri** [comment]
I have prioritized this one, it will be released next week.

**Comment by jpuri** [comment]
PR has code changes: https://github.com/jpuri/react-draft-wysiwyg/pull/125
I will release it soon.

**Comment by devnetf** [comment]
Thanks so much!

**Comment by jpuri** [comment]
The change has been release in in version `react-draft-wysiwyg@1.4.0`. For details of change please check docs.
