### ISSUE TITLE
fluctuation issue on image hover 

### ISSUE THREAD

**Issue by kishan-tocca** [jpuri/react-draft-wysiwyg#1046]
<ModalContainer
            show={openCloseModal}
            onHide={closeModalFn}
            className='user-modal'
            backdrop='static'
            size='lg'
            >
            <Modal.Header closeButton>
                <Modal.Title>Editor</Modal.Title>
            </Modal.Header>
            <Modal.Body>
                <Editor
                editorState={editor}
                toolbarClassName='toolbarClassName'
                wrapperClassName='wrapperClassName'
                editorClassName='editorClassName'
                onEditorStateChange={onChange}
                toolbar={{
                    image: {
                    uploadCallback: uploadImageCallBack,
                    alt: { present: true, mandatory: false }
                    }
                }}
                />
            </Modal.Body>
            <Modal.Footer>
                <CommonButton
                btnName='Save'
                onClick={saveData}
                className='primary-btn margin'
                />
            </Modal.Footer>
            </ModalContainer>;

while adding initial time its working perfect , but once after saving data and setting initial editorstate again . Hovering on image its getting fluctuation and not allowing cursor to add text after image
Also changing the image L,C,R not effecting while Initital EditorState content

**Comment by jpuri** [comment]
This is again not replicating in examples and seems to be issue with your implementation. Prefer to not use `editorState` but `defaultEditorState` to initialise the editor.
