### ISSUE TITLE
adding image not getting proper html

### ISSUE THREAD

**Issue by kishan-tocca** [jpuri/react-draft-wysiwyg#1047]
I have added image and get value from editorstate using 

            ```
stateToHTML(
                editorState.getCurrentContent()
                 );
```

but its not saving the enter key html after image in HTML form
so while setting data to editorstate using this

```
EditorState.createWithContent(
          ContentState.createFromBlockArray(
            convertFromHTML(html)
          )
        );
```

its not showing cursor after image and unable to add text after image
and results in image hover fluctuation

![editor](https://user-images.githubusercontent.com/66630960/98771921-86382a00-240b-11eb-9a61-cb3030ce3bce.png)

**Comment by jpuri** [comment]
Hi @kishan-tocca : it seems to work well here https://jpuri.github.io/react-draft-wysiwyg/#/demo
