### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by devnetf** [jpuri/react-draft-wysiwyg#105]
Does this support https://facebook.github.io/draft-js/docs/api-reference-editor.html#placeholder ?
I did not see it in the demo.

**Comment by jpuri** [comment]
Hi @devnetf, I was facing some styling issue with using DraftJs placeholder as unlike draftjs default block type in editor is <p> and it has some margins issue.

I will spend some time to fix this, thanks for bringing up 😄

**Comment by jpuri** [comment]
Fix has been moved to develop and will be available with the next release.

**Comment by jpuri** [comment]
Change has been released.
