### ISSUE TITLE
Any way to create a custom toolbar that sits outside of the editor?

### ISSUE THREAD

**Issue by jrohlandt** [jpuri/react-draft-wysiwyg#1095]
Hi have multiple editors on the same page and instead of having a toolbar in each editor I want to have one main toolbar at the top of the page and then have it control the currently active editor.

Is it possible to create a custom toolbar outside of the editor?

**Comment by kobajs** [comment]
@jrohlandt have you found a way?

**Comment by jrohlandt** [comment]
@kobajs not exactly. But I found a way to make it look like the toolbar is separate.
By putting the editor in a relatively positioned div and then absolutely positioning the toolbar and editor as needed via the toolbarStyle and editorStyle props, gives the appearance that they are separate.
