### ISSUE TITLE
Is it possible "resize" the Editor as a <textarea /> element? 

### ISSUE THREAD

**Issue by crscaballero** [jpuri/react-draft-wysiwyg#1096]
As the title says, I'm wondering if its possible to resize the Wysiwig Editor as the textarea elements from the right corner?
![Screen Shot 2021-03-31 at 11 42 02 AM](https://user-images.githubusercontent.com/48134692/113195090-b9425500-9216-11eb-9321-585d160dee92.png)

**Comment by vlaux** [comment]
Yep. Just set the [`resize` css](https://www.w3schools.com/cssref/css3_pr_resize.asp) prop in your class used on `editorClassName` or `editorStyle`.

**Comment by crscaballero** [comment]
> Yep. Just set the [`resize` css](https://www.w3schools.com/cssref/css3_pr_resize.asp) prop in your class used on `editorClassName` or `editorStyle`.

Thank you, I didn't think of it

in case someone else needed it, this would work like a charm

```
.wrapperClassName {
    resize: both;
    overflow: auto;
    height: 300px; // whatever height you want
    width: 100%;
    .editorClassName {
        height: 100%;
        width: 100%;
    }
}
```

NOTE: the `height: 100%;` into `.editorClassName` is necessary due to the styles on the `editorClassName` can be different than the `wrapperClassName`

**Comment by abuzer** [comment]
That causes and issues as the popups for heading and link get hide due to overflow.
