### ISSUE TITLE
Editor onBlur doesn't work

### ISSUE THREAD

**Issue by jdpagley** [jpuri/react-draft-wysiwyg#111]

**Comment by jpuri** [comment]
@jdpagley: the editor atm does not support event callbacks, but I think I should add these. I will soon add this.

For now a not so good HACK for you could be to wrap editor in div with tabIndex=0 and listen to its events for focus and blur.

**Comment by jdpagley** [comment]
@jpuri Okay thanks for the quick response :).. The additions will be greatly appreciated.

**Comment by jpuri** [comment]
@jdpagley: There is little complexity in it. Main editor also blur when user focuses inputs in toolbar.

Do you have a suggestion that in  this cases should onBlur get triggered - or it should trigger when whole thing editor + toolbar is blur ?

**Comment by jpuri** [comment]
The change has been release in in version `react-draft-wysiwyg@1.4.0`. For details of change please check docs.

**Comment by jdpagley** [comment]
@jpuri AWESOME! Thank you :)
