### ISSUE TITLE
Link component does not render correctly 

### ISSUE THREAD

**Issue by sureshHARDIYA** [jpuri/react-draft-wysiwyg#112]
Hi, I am using `react-draft-wysiwyg` component. I am using `draftToHtml` and `convertFromHTML` to save the editorState into database. With `Link`, it inserts the target and  attributes as it is supposed to. The problem is it does not render when `target` does not start with `http`.  

**This works,** 
`<a href="http://www.example.com">`example</a> works correctly. 

**This does not works,** 
`<a href="#com">`example</a> works correctly. 

Just to make clear, I am also rendering, `react-draft-wysiwyg/dist/react-draft-wysiwyg.css` as specified in the docs.

**Comment by jpuri** [comment]
@sureshHARDIYA: where is it not rendering correctly in editor or generated HTML ?

`convertFromHTML` is draftjs and does not suffice all the requirements of `react-draft-wysiwyg`. I always tell those using the editor to save state in JSON and convert to HTML only for display.

**Comment by sureshHARDIYA** [comment]
In the editor. The generated HTML is correct.

**Comment by jpuri** [comment]
ok, why do not you use JSON format for saving editor content it works way better.

**Comment by sureshHARDIYA** [comment]
Its one alternative to try. I hope there is some example on the demo, to follow.

**Comment by jpuri** [comment]
@sureshHARDIYA: saving content as JSON has various advantages of connecting with api and converting to different formats. You can convert it to HTML when needed for display but for storing JSON is definitely superior.

You can export JSON from editor and hydrate editor back using it. Docs and demo pages have examples for it.

Example of hydrating from JSON: https://github.com/jpuri/react-draft-wysiwyg/blob/master/docs/src/components/Demo/index.js#L175

https://github.com/jpuri/react-draft-wysiwyg/blob/master/docs/src/components/Demo/index.js#L175

(This line show `initialContentState` but you should try out `contentState`, plz read docs).

**Comment by jpuri** [comment]
@sureshHARDIYA: can I do something to help this issue. Create HTML to editorState is in backlog :)

Should I close this issue ?

**Comment by sureshHARDIYA** [comment]
@jpuri, this issue can be closed. I saw a new issue regarding editorState. I can close it.

**Comment by ForumT** [comment]
Anyupdates on this?
