### ISSUE TITLE
Custom HTML tag as wrapper around selected text

### ISSUE THREAD

**Issue by KulovacNedim** [jpuri/react-draft-wysiwyg#1133]
Hi is it possible to make a custom button that would create some HTML tag wrapped around selected text?

For example:
1. text entered in Editor is: 'Some Dummy Text'
2. I select 'Dummy' part and press button
3. and get draft like: '`<p>Some <code>Dummy</code> Text</p>`'

I tried with:
```
const contentState = Modifier.replaceText(
      editorState.getCurrentContent(),
      editorState.getSelection(),
      '<code>' + draftToHtml(convertToRaw(editorState.getCurrentContent())) + '</code>',
      editorState.getCurrentInlineStyle(),
    );
```
but as you can imagine, this method expects a string, and '`<code>`' is translated in `&lt;code&gt;`

Is there any other possibility?

**Comment by Aryan-mor** [comment]
I have this problem
your result code is 
`<code><p>Some Dummy Text</p></code>`

but you like this
`<p>Some <code>Dummy</code> Text</p>`

**Comment by roviks** [comment]
Any news about this topic? @KulovacNedim @Aryan-mor
