### ISSUE TITLE
Pls improve the ui

### ISSUE THREAD

**Issue by lorstenoplo** [jpuri/react-draft-wysiwyg#1152]
Im not criticizing but mostly the hover and active state styles of the tollbar buttons are like 2010s. So please change them.

**Comment by Anwardo** [comment]
You can fully customize the styles and even use fully custom components (my preference). At this time it seems the author will only release bugfixes.

**Comment by lorstenoplo** [comment]
@Anwardo thanks for responding, it that I'll close the issue...

**Comment by lorstenoplo** [comment]
Ss
