### ISSUE TITLE
Bug: Demo draftjs-to-html - font-size

### ISSUE THREAD

**Issue by volkandkaya** [jpuri/react-draft-wysiwyg#116]
On the demo draftjs-to-html converts font-size to 8 instead of 8px.

**Comment by jpuri** [comment]
@volkandkaya: thanks for brining this up, I will soon fix.

**Comment by andreslucas** [comment]
@volkandkaya you can use 'draft-js-export-html'

Check how to use it in [https://github.com/andresin87/wysiwyg](https://github.com/andresin87/wysiwyg)
Try it using [here](https://andresin87.github.io/wysiwyg/) (Output generated in HTML CoreStyles).

**Comment by volkandkaya** [comment]
@jpuri nice. Also are there an examples of the editor split into two, where the input area may be in a different component?

@andreslucas I tried to get it working but this editor creates a different type required by 'draft-js-export-html'. draftjs-to-html also works really well except the 'px'

**Comment by jpuri** [comment]
@volkandkaya: just published `draftjs-to-html#0.4.1` and `draftjs-to-markdown#0.0.6` with fixes.
