### ISSUE TITLE
ADD linkify boolean option

### ISSUE THREAD

**Issue by andresin87** [jpuri/react-draft-wysiwyg#117]
[here](https://www.draft-js-plugins.com/plugin/linkify) an example behaviour. Maybe with embeded thumb like facebook.

**Comment by jpuri** [comment]
@andresin87, I though about it at some point. Toolbar supports adding link and those links are with a `display text` and a actual `target`. If I add this linkify feature also then effectively 2 types on links will exist in the editor.

But I also agree that highlighting link in text is good idea. I will add it, it will not have option to edit it like current link. May be I can style it differently then current link.
