### ISSUE TITLE
Is there any way to add plugins ?

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [jpuri/react-draft-wysiwyg#1170]

**Comment by iisalazar** [comment]
Why was this issue closed @Sachin-chaurasiya without giving any context if the question was answered?

**Comment by Sachin-chaurasiya** [comment]
> Why was this issue closed @Sachin-chaurasiya without giving any context if the question was answered?

Hey @iisalazar, it’s been three years, so I don’t recall the exact reason, but I believe I might have found something somewhere. Could you clarify what specifically you’re looking for?
