### ISSUE TITLE
Image with Hyperlink not working

### ISSUE THREAD

**Issue by Iaskebba** [jpuri/react-draft-wysiwyg#1185]
I am trying to create an image with a hyperlink so when I use draftjs-to-html it has the following: 

`<a href="default.asp"><img src="smiley.gif" alt="HTML tutorial" style="width:42px;height:42px;"></a>`

I have tried to do this at both the entity level and html-to-draftjs but have been unsuccessful due to html-to-draftjs pruning off the <a> tag. When I try to do this at the entity level it doesn't appear like this is possible. Any suggestions?

**Comment by SBRKH** [comment]
> Accomplished through CustomBlockRenderer

Hello,

Is it possible to have an example of how you proceed with CustomBlockRenderer for this kind of thing ?

Thank you !
