### ISSUE TITLE
Toolbar modals closing prematurely

### ISSUE THREAD

**Issue by TheStu** [jpuri/react-draft-wysiwyg#120]
After opening a toolbar modal (creating a link for instance), clicking anywhere in the body of the modal causes the modal to close. So clicking on the 'Link Target' box, for instance, causes the modal to close. I don't have any clues about what the cause is but it seems to be happening on the github.io demo page too.

**Comment by jpuri** [comment]
@TheStu, thanks for bringing this up. I will fix it soon.

**Comment by jpuri** [comment]
@TheStu: latest published version `react-draft-wysiwyg@1.3.2` has the fix.

**Comment by TheStu** [comment]
awesome, thanks!

**Comment by Fouppy** [comment]
Actually I'm still having this bug, using 1.4.1 when setting `toolbarOnFocus`

**Comment by jpuri** [comment]
@Fouppy: I will check and fix it soon.
