### ISSUE TITLE
Popups should close when esp key is pressed

### ISSUE THREAD

**Issue by jpuri** [jpuri/react-draft-wysiwyg#121]

**Comment by sureshHARDIYA** [comment]
Also,  would be great, if active popup closes, when user click on other button or clicks outside the Editor like other editor.

**Comment by jpuri** [comment]
That already happens in latest version @sureshHARDIYA

**Comment by jpuri** [comment]
Change has been moved to develop branch, will soon be released.

**Comment by jpuri** [comment]
Change released in version `react-draft-wysiwyg@1.5.7` 😄
