### ISSUE TITLE
Feature request: Pre block for multiple lines of codes.

### ISSUE THREAD

**Issue by ZeroCho** [jpuri/react-draft-wysiwyg#122]
Thanks for the great editor.

I think there should be `pre` block which can put some codes inside. I run a blog about programming and I want to put some multiple lines of codes.

Currently, we can use inline code, but it's not for multiple code block.

**Comment by jpuri** [comment]
Hey @ZeroCho ,

This id duplicate https://github.com/jpuri/react-draft-wysiwyg/issues/71 :)
I plan to add it already. I am marking this one as closed.
