### ISSUE TITLE
Not able to focus on editor with functional components

### ISSUE THREAD

**Issue by ShalinShah84** [jpuri/react-draft-wysiwyg#1251]
We use the editor for the summary text and not able to focus on the textarea when mounted. Here is what I got so far in the code which is not working.
const editorRef = useRef(null);
useEffect(() => {
            editorRef?.current.focusEditor()
        }, [editorRef]);

<Editor
      editorRef={(ref) => (editorRef.current = ref)} />

Any help ?

**Comment by NikitaLukashuk1** [comment]
@ShalinShah84 how did you fix that?
