### ISSUE TITLE
ReferenceError: window is not defined 

### ISSUE THREAD

**Issue by dioveath** [jpuri/react-draft-wysiwyg#1281]
```javascript
import { Editor } from "react-draft-wysiwyg";
import "react-draft-wysiwyg/dist/react-draft-wysiwyg.css";

export default function Dashboard() {

  return (
      <main className="main">
        <Editor/>
      </main>
  );
} 
```

Getting ReferenceError: window is not defined, running on NextJs 12.1.0

Initially, without adding CSS I was getting tooltip icons but later adding CSS it started throwing errors.

**Comment by dioveath** [comment]
I found it is not working on refresh, but works after launching the page again from other links. Don't know much about the internals but I guess the problem is due to different work development flow in NextJs.

**Comment by Barefoot-Dev** [comment]
@dioveath Any solution here in NextJS?

**Comment by dioveath** [comment]
This error happens when Nextjs tries to render in the server for SSR. We can lazy load the libraries to solve the issue. Import it with dynamic from 'next/dynamic' which will not preload it to the server (SSR). Like,

```js
import dynamic from 'next/dynamic';

import "react-draft-wysiwyg/dist/react-draft-wysiwyg.css";
const Editor = dynamic(() => import("react-draft-wysiwyg"), { ssr: false });

export default function Dashboard() {

  return (
      <main className="main">
        <Editor/>
      </main>
  );
} 
```

**Comment by aboutonlineblog** [comment]
> This error happens when Nextjs tries to render in the server for SSR. We can lazy load the libraries to solve the issue. Import it with dynamic from 'next/dynamic' which will not preload it to the server (SSR). Like,
> 
> ```js
> import dynamic from 'next/dynamic';
> 
> import "react-draft-wysiwyg/dist/react-draft-wysiwyg.css";
> const Editor = dynamic(() => import("react-draft-wysiwyg"), { ssr: false });
> 
> export default function Dashboard() {
> 
>   return (
>       <main className="main">
>         <Editor/>
>       </main>
>   );
> } 
> ```

Hi, I got an error when using your solution

**Error: Element type is invalid. Received a promise that resolves to: [object Module]. Lazy element type must resolve to a class or function.**
<img width="952" alt="Screen Shot 2023-02-15 at 6 29 20 PM" src="https://user-images.githubusercontent.com/35444868/219002679-af3e1f83-cab8-4faa-a1e3-a0dc18668307.png">

I tried doing the react lazy

```
const Editor = React.lazy(() => import("react-draft-wysiwyg"));

const Editor = React.lazy(async () => {
  let obj = await import("react-draft-wysiwyg");
  return obj;
});
```
still nothing works

**Comment by aboutonlineblog** [comment]
Nevermind, I found the solution here

https://github.com/jpuri/react-draft-wysiwyg/issues/893#issuecomment-1431231296
