### ISSUE TITLE
Hello. Some basic example?

### ISSUE THREAD

**Issue by theLordz** [jpuri/react-draft-wysiwyg#13]
**_Hello!_**

Based on what I've seen in the demos you provided, I like your implementation. I think it may be very good in production because of the practical way of grouping and arranging the design functions within it.

I want to test it in our projects. 

But I think it might be helpful a basic usage guide, because I get this **Warning**: validateDOMNesting(...): < div> cannot appear as a descendant of < p>. See DraftEditorContents > p > ... > DraftEditorBlock > div.

Thank you for sharing your project.

**Comment by jpuri** [comment]
Hi @theLordz,

Nice that you liked the project !

Sure you can test it in your project. Latest installable can be downloaded from npm. It version is `0.1.9` (though npm page still shows old version - ignore it).

Follow docs for example:
Import this css: 
https://github.com/jpuri/react-draft-wysiwyg/blob/master/docs/src/index.js#L7
and this JS:
https://github.com/jpuri/react-draft-wysiwyg/blob/master/docs/src/components/Demo1/index.js#L5

ATM format in which you need to save is DraftJS content state: https://facebook.github.io/draft-js/docs/api-reference-content-state.html
I am thinking of extending it to simple HTML also later. The plan is also to bring out 1.0 in few days (https://github.com/jpuri/react-draft-wysiwyg/issues/2).

For any help I am usually available at DraftJS slack: https://draftjs.herokuapp.com/

**Comment by jpuri** [comment]
@theLordz: docs on the site have been updated, please refer them.

I am closing this issue.
