### ISSUE TITLE
Outputted Links are Incorrect

### ISSUE THREAD

**Issue by vhmth** [jpuri/react-draft-wysiwyg#131]
If you use the link widget (or try to import links), you'll notice that

```
<a href="https://google.com">https://google.com</a>
```

gets converted to

```
<a href="https://google.com">undefined</a>
```

You can see this by playing with this (found this from [this issue](https://github.com/jpuri/react-draft-wysiwyg/issues/116)):

https://andresin87.github.io/wysiwyg/?selectedKind=ReactDraftWysiwyg&selectedStory=Output%20generated%20in%20HTML&full=0&down=1&left=1

This effectively nullifies being able to export as HTML. I'm not sure if this is an issue with [draft-js-export-html](https://github.com/sstur/draft-js-export-html) - was wondering if someone could point me in the right direction here.

**Comment by jpuri** [comment]
@vhmth: thanks for bringing this up. This issue has came up in some of last releases, I will fix it fast.

**Comment by jpuri** [comment]
@vhmth : `draftjs-to-html@0.4.2` this version has the fix.

**Comment by vhmth** [comment]
@jpuri woah thanks for such a quick response! It does seem like this fixes it for when you add links, but when you load the HTML back into the editor, the editor change event shows undefined.

https://www.opentest.co/share/97340450c2d511e6a575e589126b5a40

**Comment by jpuri** [comment]
@vhmth: do you mean conversion from HTML to EditorState ?

The draftjs  lib to hydrate editor state from HTML doe snot covers all HTML tags - also HTML vocabulary is so vast, its hard to cover everything. I plan to write a lib to hydrate editor state from HTML, there are lot of requests for it: https://github.com/jpuri/react-draft-wysiwyg/issues/103.

I strongly recommend saving editor state as JSON. Saving content as JSON is anyways better and then change to HTML or markdown when needed.

**Comment by vhmth** [comment]
Ah I see - yeah that's probably it. Thank you so much for keeping me updated in a timely manner. I really really appreciate all the work you've done on this lib @jpuri. I'll keep an eye on #103. Let me know how I can be of any help (from code reviews to whatever).

**Comment by jpuri** [comment]
Thanks @vhmth :)
Do consider saving content as json if that serves ur use case, fb also saves draft content as json. html is good for displaying the content but not for saving.

**Comment by jpuri** [comment]
Hey @vhmth,

I am closing this issue, also plz check this lib: html-to-draftjs@0.0.1-beta details here: https://github.com/jpuri/react-draft-wysiwyg/issues/103
