### ISSUE TITLE
(ASK) What data required in resolve (at uploadImageCallback)

### ISSUE THREAD

**Issue by kimdotnet** [jpuri/react-draft-wysiwyg#134]
In uploadImageCallback it must pass the data to resolve from backend server.

But I don't know what format of data should be pass to the resolve function.

I already tried like this:
```
const data = { link: res.data.url};
resolve(data);
```

but got this error:
```
Uncaught (in promise) TypeError: Cannot read property 'link' of undefined
    at eval (react-draft-wysiwyg.js:33)
(anonymous) @ react-draft-wysiwyg.js:33
```

**Comment by jpuri** [comment]
Sorry, the docs are confusing about it, I will fix, plz pass this:

```
const data = { link: res.data.url};
resolve({ data });
```

**Comment by kimdotnet** [comment]
It's works!
Thanks jpuri

Hope this editor will be as great as cke or summernote :), but in React world

**Comment by jpuri** [comment]
Thanks a lot @kimdotnet 😄
