### ISSUE TITLE
Render HTML template's css in editor. 

### ISSUE THREAD

**Issue by ananddodia** [jpuri/react-draft-wysiwyg#138]
I have a HTML email template. I want to edit that in editor.
When I add that HTML in editor. It only shows text content. All my css and images are removed in editor.

Please help. how should I get css and image render in editor.

**Comment by jpuri** [comment]
@ananddodia:

I am working atm to create a lib to allow conversion from html to editor state needed for the library. Atm the functionality provided by draftjs does not suffices for this editor.

Editor supports conversion to and from RawContentState.

**Comment by ananddodia** [comment]
Thanks. Waiting for update.
Please inform when its done.
Your editor is nice and cover many features that I need.

**Comment by jpuri** [comment]
Please check update here: https://github.com/jpuri/react-draft-wysiwyg/issues/103

Please not that this lib atm can translate for draftjs content only html generated by react-draft-wysiwyg.

**Comment by jpuri** [comment]
Closing as there is no response, issue can be re-opened when needed.

**Comment by pratikpatil613** [comment]
hi i am working on react native app with this great editor. I have a HTML email template. I want to edit that in editor.
When I add that HTML in editor. template not rendering with proper inline style and css.
 **this is my code below:**

const html1 = `<!DOCTYPE html>  <html lang="en"> <head> <meta charset="UTF-8"> <title>HTML Email Template | Webdevtrick.com</title> </head> <body> <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">  <tbody><tr> <td align="center"> <table class="col-600" width="600" border="0" align="center" cellpadding="0" cellspacing="0"> <tbody><tr> <td align="center" valign="top" background="https://images.pexels.com/photos/1936299/pexels-photo-1936299.jpeg?cs=srgb&dl=artificial-intelligence-codes-developing-1936299.jpg&fm=jpg" bgcolor="#66809b" style="background-size:cover; background-position:top;height=" 400""=""> <table class="col-600" width="600" height="400" border="0" align="center" cellpadding="0" cellspacing="0"> <tbody><tr> <td height="40"></td> </tr> <tr> <td align="center" style="line-height: 0px;"> <img style="display:block; line-height:0px; font-size:0px; border:0px;" src="https://webdevtrick.com/wp-content/uploads/logo-fb-1.png" width="109" height="115" alt="logo"> </td> </tr> <tr> <td align="center" style="font-family: 'Raleway', sans-serif; font-size:37px; color:#ffffff; line-height:24px; font-weight: bold; letter-spacing: 5px;"> WELCOME <span style="font-family: 'Raleway', sans-serif; font-size:37px; color:#ffffff; line-height:39px; font-weight: 300; letter-spacing: 5px;">TO NEWSLETTER</span> </td> </tr> <tr> <td align="center" style="font-family: 'Lato', sans-serif; font-size:15px; color:#ffffff; line-height:24px; font-weight: 300;"> Now you will recive Email everytime automatically <br>on our new updates. </td> </tr> <tr> <td height="50"></td> </tr> </tbody></table> </td> </tr> </tbody></table> </td> </tr>   <tr> <td align="center"> <table class="col-600" width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="margin-left:20px; margin-right:20px; border-left: 1px solid #dbd9d9; border-right: 1px solid #dbd9d9;"> <tbody><tr> <td height="35"></td> </tr> <tr> <td align="center" style="font-family: 'Raleway', sans-serif; font-size:22px; font-weight: bold; color:#333;">CONTENT SHOWCASE</td> </tr> <tr> <td height="10"></td> </tr> <tr> <td align="center" style="font-family: 'Lato', sans-serif; font-size:14px; color:#757575; line-height:24px; font-weight: 300;"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis maximus mollis.<br> Aenean purus magna, dignissim in aliquam quis, ullamcorper a dui. </td> </tr> </tbody></table> </td> </tr> <tr> <td align="center"> <table class="col-600" width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border-left: 1px solid #dbd9d9; border-right: 1px solid #dbd9d9; "> <tbody><tr> <td height="10"></td> </tr> <tr> <td> <table class="col3" width="183" border="0" align="left" cellpadding="0" cellspacing="0"> <tbody><tr> <td height="30"></td> </tr> <tr> <td align="center"> <table class="insider" width="133" border="0" align="center" cellpadding="0" cellspacing="0"> <tbody><tr align="center" style="line-height:0px;"> <td> <img style="display:block; line-height:0px; font-size:0px; border:0px;" src="https://webdevtrick.com/wp-content/uploads/email.png" width="78" height="78" alt="icon"> </td> </tr> <tr> <td height="15"></td> </tr> <tr align="center"> <td style="font-family: 'Raleway', Arial, sans-serif; font-size:20px; color:#333; line-height:24px; font-weight: bold;">Contact</td> </tr> <tr> <td height="10"></td> </tr> <tr align="center"> <td style="font-family: 'Lato', sans-serif; font-size:14px; color:#757575; line-height:24px; font-weight: 300;">Lorem ipsum dolor sit amet.</td> </tr> </tbody></table> </td> </tr> <tr> <td height="30"></td> </tr> </tbody></table> <table width="1" height="20" border="0" cellpadding="0" cellspacing="0" align="left"> <tbody><tr> <td height="20" style="font-size: 0;line-height: 0;border-collapse: collapse;"> <p style="padding-left: 24px;"> </p> </td> </tr> </tbody></table> <table class="col3" width="183" border="0" align="left" cellpadding="0" cellspacing="0"> <tbody><tr> <td height="30"></td> </tr> <tr> <td align="center"> <table class="insider" width="133" border="0" align="center" cellpadding="0" cellspacing="0"> <tbody><tr align="center" style="line-height:0px;"> <td> <img style="display:block; line-height:0px; font-size:0px; border:0px;" src="https://webdevtrick.com/wp-content/uploads/work.png" width="78" height="78" alt="icon"> </td> </tr> <tr> <td height="15"></td> </tr> <tr align="center"> <td style="font-family: 'Raleway', sans-serif; font-size:20px; color:#333; line-height:24px; font-weight: bold;">About</td> </tr> <tr> <td height="10"></td> </tr> <tr align="center"> <td style="font-family: 'Lato', sans-serif; font-size:14px; color:#757575; line-height:24px; font-weight: 300;">Lorem ipsum dolor sit amet.</td> </tr> </tbody></table> </td> </tr> <tr> <td height="30"></td> </tr> </tbody></table> <table width="1" height="20" border="0" cellpadding="0" cellspacing="0" align="left"> <tbody><tr> <td height="20" style="font-size: 0;line-height: 0;border-collapse: collapse;"> <p style="padding-left: 24px;"> </p> </td> </tr> </tbody></table> <table class="col3" width="183" border="0" align="right" cellpadding="0" cellspacing="0"> <tbody><tr> <td height="30"></td> </tr> <tr> <td align="center"> <table class="insider" width="133" border="0" align="center" cellpadding="0" cellspacing="0"> <tbody><tr align="center" style="line-height:0px;"> <td> <img style="display:block; line-height:0px; font-size:0px; border:0px;" src="https://webdevtrick.com/wp-content/uploads/computer.png" width="78" height="78" alt="icon"> </td> </tr> <tr> <td height="15"></td> </tr> <tr align="center"> <td style="font-family: 'Raleway', sans-serif; font-size:20px; color:#333; line-height:24px; font-weight: bold;">Services</td> </tr> <tr> <td height="10"></td> </tr> <tr align="center"> <td style="font-family: 'Lato', sans-serif; font-size:14px; color:#757575; line-height:24px; font-weight: 300;">Lorem ipsum dolor sit amet.</td> </tr> </tbody></table> </td> </tr> <tr> <td height="30"></td> </tr> </tbody></table> </td> </tr> </tbody></table> </td> </tr> <tr> <td height="5"></td> </tr>   <tr> <td align="center"> <table align="center" class="col-600" width="600" border="0" cellspacing="0" cellpadding="0"> <tbody><tr> <td align="center" bgcolor="#333"> <table class="col-600" width="600" align="center" border="0" cellspacing="0" cellpadding="0"> <tbody><tr> <td height="33"></td> </tr> <tr> <td> <table class="col1" width="183" border="0" align="left" cellpadding="0" cellspacing="0"> <tbody><tr> <td height="18"></td> </tr> <tr> <td align="center"> <img style="display:block; line-height:0px; font-size:0px; border:0px;" class="images_style" src="https://webdevtrick.com/wp-content/uploads/email-template.png" alt="img" width="156" height="160"> </td> </tr> </tbody></table> <table class="col3_one" width="380" border="0" align="right" cellpadding="0" cellspacing="0"> <tbody><tr align="left" valign="top"> <td style="font-family: 'Raleway', sans-serif; font-size:20px; color:#fbb016; line-height:30px; font-weight: bold;">Another Title Heading! </td> </tr> <tr> <td height="5"></td> </tr> <tr align="left" valign="top"> <td style="font-family: 'Lato', sans-serif; font-size:14px; color:#fff; line-height:24px; font-weight: 300;"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis maximus mollis. Aenean purus magna, dignissim in aliquam quis, ullamcorper a dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae. </td> </tr> <tr> <td height="10"></td> </tr> <tr align="left" valign="top"> <td> <table class="button" style="border: 2px solid #fff;" bgcolor="#fbb016" width="30%" border="0" cellpadding="0" cellspacing="0"> <tbody><tr> <td width="10"></td> <td height="30" align="center" style="font-family: 'Open Sans', Arial, sans-serif; font-size:13px; color:#ffffff;"> <a href="#" style="color:#ffffff; text-decoration: none;">Read more</a> </td> <td width="10"></td> </tr> </tbody></table> </td> </tr> </tbody></table> </td> </tr> <tr> <td height="33"></td> </tr> </tbody></table> </td> </tr> </tbody></table> </td> </tr>   <tr> <td align="center"> <table class="col-600" width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="margin-left:20px; margin-right:20px;"> <tbody><tr> <td align="center"> <table class="col-600" width="600" border="0" align="center" cellpadding="0" cellspacing="0" style=" border-left: 1px solid #dbd9d9; border-right: 1px solid #dbd9d9;"> <tbody><tr> <td height="50"></td> </tr> <tr> <td align="right"> <table class="col2" width="287" border="0" align="right" cellpadding="0" cellspacing="0"> <tbody><tr> <td align="center" style="line-height:0px;"> <img style="display:block; line-height:0px; font-size:0px; border:0px;" class="images_style" src="https://webdevtrick.com/wp-content/uploads/email-template-1.png" width="169" height="138"> </td> </tr> </tbody></table> <table width="287" border="0" align="left" cellpadding="0" cellspacing="0" class="col2" style=""> <tbody><tr> <td align="center"> <table class="insider" width="237" border="0" align="center" cellpadding="0" cellspacing="0"> <tbody><tr align="left"> <td style="font-family: 'Raleway', sans-serif; font-size:23px; color:#333; line-height:30px; font-weight: bold;">Our Services</td> </tr> <tr> <td height="5"></td> </tr> <tr> <td style="font-family: 'Lato', sans-serif; font-size:14px; color:#7f8c8d; line-height:24px; font-weight: 300;"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis maximus mollis. Aenean purus magna, dignissim in aliquam quis, ullamcorper a dui. </td> </tr> </tbody></table> </td> </tr> </tbody></table> </td> </tr> </tbody></table> </td> </tr>   <tr> <td align="center"> <table align="center" width="100%" border="0" cellspacing="0" cellpadding="0" style=" border-left: 1px solid #dbd9d9; border-right: 1px solid #dbd9d9;"> <tbody><tr> <td height="50"></td> </tr> <tr> <td align="center" bgcolor="#333"> <table class="col-600" width="600" border="0" align="center" cellpadding="0" cellspacing="0"> <tbody><tr> <td height="35"></td> </tr> <tr> <td align="center" style="font-family: 'Raleway', sans-serif; font-size:20px; color:#fbb016; line-height:24px; font-weight: bold;">Our Pricing</td> </tr> <tr> <td height="20"></td> </tr> <tr> <td align="center" style="font-family: 'Lato', sans-serif; font-size:14px; color:#fff; line-height: 1px; font-weight: 300;"> Check out our price below. </td> </tr> <tr> <td height="40"></td> </tr> </tbody></table> </td> </tr> </tbody></table> </td> </tr>   <tr> <td align="center"> <table width="600" class="col-600" align="center" border="0" cellspacing="0" cellpadding="0" style=" border-left: 1px solid #dbd9d9; border-right: 1px solid #dbd9d9;"> <tbody><tr> <td height="50"></td> </tr> <tr> <td> <table style="border:1px solid #e2e2e2;" class="col2" width="287" border="0" align="left" cellpadding="0" cellspacing="0"> <tbody><tr> <td height="40" align="center" bgcolor="#333" style="font-family: 'Raleway', sans-serif; font-size:18px; color:#fbb016; line-height:30px; font-weight: bold;">Starter</td> </tr> <tr> <td align="center"> <table class="insider" width="237" border="0" align="center" cellpadding="0" cellspacing="0"> <tbody><tr> <td height="20"></td> </tr> <tr align="center" style="line-height:0px;"> <td style="font-family: 'Lato', sans-serif; font-size:48px; color:#fbb016; font-weight: bold; line-height: 44px;">$99</td> </tr> <tr> <td height="15"></td> </tr> <tr> <td height="15"></td> </tr> <tr> <td align="center"> <table width="100" border="0" align="center" cellpadding="0" cellspacing="0" style="border: 2px solid #fbb016;"> <tbody><tr> <td width="10"></td> <td height="30" align="center" style="font-family: 'Lato', sans-serif; font-size:14px; font-weight: 300; color:#333;"> <a href="#" style="color: #333; text-decoration: none;">Learn More</a> </td> <td width="10"></td> </tr> </tbody></table> </td> </tr> </tbody></table> </td> </tr> <tr> <td height="30"></td> </tr> </tbody></table> <table width="1" height="20" border="0" cellpadding="0" cellspacing="0" align="left"> <tbody><tr> <td height="20" style="font-size: 0;line-height: 0;border-collapse: collapse;"> <p style="padding-left: 24px;"> </p> </td> </tr> </tbody></table> <table style="border:1px solid #e2e2e2;" class="col2" width="287" border="0" align="right" cellpadding="0" cellspacing="0"> <tbody><tr> <td height="40" align="center" bgcolor="#333" style="font-family: 'Raleway', sans-serif; font-size:18px; color:#fbb016; line-height:30px; font-weight: bold;">Advance</td> </tr> <tr> <td align="center"> <table class="insider" width="237" border="0" align="center" cellpadding="0" cellspacing="0"> <tbody><tr> <td height="20"></td> </tr> <tr align="center" style="line-height:0px;"> <td style="font-family: 'Lato', sans-serif; font-size:48px; color:#fbb016; font-weight: bold; line-height: 44px;">$150</td> </tr> <tr> <td height="30"></td> </tr> <tr align="center"> <td> <table width="100" border="0" align="center" cellpadding="0" cellspacing="0" style=" border: 2px solid #fbb016;"> <tbody><tr> <td width="10"></td> <td height="30" align="center" style="font-family: 'Lato', sans-serif; font-size:14px; font-weight: 300; color:#333;"> <a href="#" style="color: #333; text-decoration: none;">Learn More</a> </td> <td width="10"></td> </tr> </tbody></table> </td> </tr> </tbody></table> </td> </tr> <tr> <td height="30"></td> </tr> </tbody></table> </td> </tr> </tbody></table> </td> </tr>   <tr> <td align="center"> <table align="center" width="100%" border="0" cellspacing="0" cellpadding="0" style=" border-left: 1px solid #dbd9d9; border-right: 1px solid #dbd9d9;"> <tbody><tr> <td height="50"></td> </tr> <tr> <td align="center" bgcolor="#333" background="https://webdevtrick.com/wp-content/uploads/image-slider1.jpg" height="185"> <table class="col-600" width="600" border="0" align="center" cellpadding="0" cellspacing="0"> <tbody><tr> <td height="25"></td> </tr> <tr> <td align="center" style="font-family: 'Raleway', sans-serif; font-size:26px; font-weight: 500; color:#fbb016; background-color: #333;">Follow Us On Social Media</td> </tr> <tr> <td height="25"></td> </tr> </tbody></table><table align="center" width="35%" border="0" cellspacing="0" cellpadding="0"> <tbody><tr> <td align="center" width="30%" style="vertical-align: top;"> <a href="https://www.facebook.com/designmodo" target="_blank"> <img src="https://webdevtrick.com/wp-content/uploads/icon-twitter.png"> </a> </td> <td align="center" class="margin" width="30%" style="vertical-align: top;"> <a href="https://twitter.com/designmodo" target="_blank"> <img src="https://webdevtrick.com/wp-content/uploads/icon-fb.png"> </a> </td> <td align="center" width="30%" style="vertical-align: top;"> <a href="https://plus.google.com/+Designmodo/posts" target="_blank"> <img src="https://webdevtrick.com/wp-content/uploads/icon-googleplus.png"> </a> </td> </tr> </tbody></table> </td></tr></tbody></table> </td> </tr> </tbody></table> </td> </tr>  </tbody></table> </body> </html>`

**const contentBlock1 = htmlToDraft('<p>'+html1+'P')
		let editorState1: any = null
		if (contentBlock1) {
		const contentState = ContentState.createFromBlockArray(
			contentBlock1.contentBlocks,
		)
		editorState1 = EditorState.createWithContent(contentState)
		}
        setEditorState(editorState1)**

also tried with  **stateFromHTML** but not getting template as it is in editor

**let contentState = stateFromHTML(html1); 	   
setEditorState(EditorState.createWithContent(contentState));**
