### ISSUE TITLE
The dropdown options like fontsize, embedded, image are not working in nextjs

### ISSUE THREAD

**Issue by poorvi-vaish** [jpuri/react-draft-wysiwyg#1387]
![image](https://github.com/jpuri/react-draft-wysiwyg/assets/56024399/b0011ae4-18c8-427f-80b0-4894bb6e55da)
Some of the options are not working. What should I include so that it works.

**Comment by jusiho** [comment]
The same thing happens to me, could it be a version problem?
Help!

**Comment by poorvi-vaish** [comment]
NO actually some tools don't work in the development mode but they're working fine in production. You can check it by removing the Strict mode, it will work.
