### ISSUE TITLE
Request: customizable blockTypes

### ISSUE THREAD

**Issue by Fouppy** [jpuri/react-draft-wysiwyg#140]
Could it be possible to add options for blockTypes? i.e. allowing only 2 title levels and blockquote for example

Something like that:

```
blockType: {
  options: ['h1', 'h2', 'blockquote']
}
```

**Comment by jpuri** [comment]
No @Fouppy, its not possible atm.

**Comment by nuxdie** [comment]
hello. my PR #141 closes this issue, please consider merging it

**Comment by jpuri** [comment]
Awesome @nuxdie, it looks good. I will merge it. @Fouppy you will have this feature soon 😄

**Comment by Fouppy** [comment]
Nice :+1:. But as I understand it, if you want to remove some block types, it's only possible if they're not displayed in a dropdown, right?

**Comment by jpuri** [comment]
yes, you are right.

**Comment by jpuri** [comment]
Released.
