### ISSUE TITLE
react-draft-wysiwyg toolbar options not opening

### ISSUE THREAD

**Issue by Williams25** [jpuri/react-draft-wysiwyg#1431]
react-draft-wysiwyg toolbar options not opening emoji, font size, font family, link, upload image and color pick.

next 14x
react 18x

![Captura de tela 2024-04-05 131203](https://github.com/jpuri/react-draft-wysiwyg/assets/43673479/a7655d64-ef8f-42dd-af73-bd029e5f5f80)

**Comment by chrisidakwo** [comment]
Update your Next.js configuration file and set the property `reactStrictMode` to false.

Something like this, say your config file is called `next.config.mjs`:

```js
const nextConfig = {
  reactStrictMode: false,
  ...
};

export default nextConfig; // Or however you export it
```
