### ISSUE TITLE
its dont work with React 16.13.1 and vite

### ISSUE THREAD

**Issue by ericky0** [jpuri/react-draft-wysiwyg#1437]
hi 🖐️, i had a project with webpack (there everything worked normally), then i started to migrate to use vite, and i faced one problem with this library, when i use yarn dev (vite serve) i can normally go to my page that renders this component `import { Editor } from 'react-draft-wysiwyg';`

![image](https://github.com/jpuri/react-draft-wysiwyg/assets/53923000/56e483b7-17d4-4325-bc66-b5acecf78069)

i can also run yarn build with no problems (vite build --emptyOutDir)

but the problem is: when i run yarn start (serve -s dist) and i go to the page that renders this component, my page is blank and i receive these errors in the console

![image](https://github.com/jpuri/react-draft-wysiwyg/assets/53923000/10c104a1-04a8-4aa1-84d3-4b37351fc874)

"react": "^16.13.1",
"react-draft-wysiwyg": "^1.14.7",
"draft-js": "^0.11.7"

**Comment by ericky0** [comment]
i managed to solve this problem updating this lib `"@vitejs/plugin-react": "^4.2.1"`

**Comment by a4abs** [comment]
After using in index.html fix my issue, as global is missing

<script>
  window.global = window;
</script>
