### ISSUE TITLE
Easy way to add in new font families

### ISSUE THREAD

**Issue by dderr** [jpuri/react-draft-wysiwyg#147]
Is there an easy way to customize the list of font families. For instance:

export const fontFamilies = ['Impact', 'Open Sans', 'Roboto', 'Tahoma', 'Times New Roman', 'Verdana'];

**Comment by jpuri** [comment]
@dderr not right now, but it will be nice feature to have. I have some other priority things planned atm and will consider developing it after these.
I am also open to have a PR for this.

**Comment by jpuri** [comment]
Starting work on this feature now.

**Comment by jpuri** [comment]
Released in `react-draft-wysiwyg@1.5.4`.

**Comment by ericute** [comment]
Hi, @jpuri!

I know it has been a while since this has been implemented but I don't see any docs on how to add font families in the dropdown and how to add its source. Do you have a link / sample somewhere I could look into?

**Comment by KhizerWHussain** [comment]
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `i`.
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.


why this is giving me this error where is the issue how to resolve it please help

**Comment by KhizerWHussain** [comment]
also tell me how to render inital values in it i mean i am using bloglisting in my app where i can edit blog as well so when i click on edit it goes to this editor and prev data would come from redux how to display it in this library i have used it in react.quill which works fine but how to make it work here
