### ISSUE TITLE
how to clear content of Editor?

### ISSUE THREAD

**Issue by the1sky** [jpuri/react-draft-wysiwyg#148]
@jpuri I can not clean editor content after uploading content, any method? thanks

below are no effect:

`this.setState({
   editorState: EditorState.createEmpty(),
})`

or 

`const editorState = EditorState.push(this.state.editorState, ContentState.createFromText(''));
this.setState({ editorState });`

**Comment by jpuri** [comment]
Hey @the1sky: I expect this to work, can you share how you are passing this editorState as props to the editor.

**Comment by the1sky** [comment]
@jpuri , below is my component source code:

`import React from 'react';
import {connect} from 'react-redux';
import {convertToRaw, convertFromRaw, EditorState, ContentState, SelectionState, Modifier} from 'draft-js';
import {getRaw, getEmptyRaw} from '../../utils/convert';
import {Editor} from 'react-draft-wysiwyg';
import uploadImageCallBack from '../../utils/uploadImageCallBack';
import {addCardComment, modifyCardComment} from '../../actions';
import {EditorMode} from '../../constants/editor';

class MyEditNew extends React.Component {
  constructor(props) {
    super(props);
    const mode = props.mode;
    const content = props.actionContent;
    let editorState = EditorState.createEmpty();
    let initState;
    if (mode == EditorMode.modify && content) {
      initState = getRaw(content);
    } else {
      initState = getEmptyRaw();
    }
    this.state = ({
      initState,
      editorState,
    });
  }

  componentDidMount() {
    const self = this;
    const suggestion = self.getSuggestion();
    this.setState({
      suggestion,
    });
  }

  componentWillReceiveProps(nextProps) {
    const {editorState} = this.state;
    if (nextProps.boardUsers) {
      this.setState({
        editorState,
        suggestion: this.convertBoardUsersFormat(nextProps.boardUsers),
      });
    }
  }

  getSuggestion() {
    const {boardUsers} = this.props;
    return this.convertBoardUsersFormat(boardUsers);
  }

  /**
   * 转换用户数据展示格式
   *
   * @param originUsers
   * @returns {Array}
   */
  convertBoardUsersFormat(originUsers) {
    let res = [];
    if (originUsers) {
      originUsers.forEach(function (val, key) {
        const item = {
          text: val.username + '(' + val.mail + ')',
          value: val.username,
          url: '',
        };
        res.push(item);
      });
    }
    return res;
  }

  /**
   * 编辑器状态变更
   *
   * @param editorState
   */
  onEditorStateChange(editorState) {
    const contentState = convertFromRaw(editorState);
    const state = EditorState.createWithContent(contentState);
    this.setState({
      editorState: state,
    });
  };

  /**
   * 确认保存
   */
  confirm() {
    const self = this;
    const {editorState, editMode} = this.state;
    const {issueId, commentId} = this.props;
    const t = convertToRaw(editorState.getCurrentContent());
    const {dispatch} = this.props;
    if (editMode == EditorMode.add) {
      dispatch(addCardComment(issueId, '评论', JSON.stringify(t))).then(function (t) {
        self.clearContent.bind(self)();
      });
    } else {
      dispatch(modifyCardComment(issueId, '评论', commentId, JSON.stringify(t)));
    }
  }

  cancel() {
    this.props.disappear();
  }

  clearContent() {
    const editorState = EditorState.push(this.state.editorState, ContentState.createFromText(''));
    const initState = EditorState.push(this.state.initState, ContentState.createFromText(''));
    this.setState({editorState, initState});
  }

  /**
   * 工具栏配置
   *
   * @returns {{options: [string,string,string,string,string,string,string], inline: {options: [string,string,string,string]}, list: {inDropdown: boolean, options: [string,string]}, link: {inDropdown: boolean}, unlink: {inDropdown: boolean}}}
   */
  getToolbarConfig() {
    return {
      options: ['inline', 'image', 'link', 'unlink', 'emoji', 'fontSIze', 'list', 'colorPicker'],
      inline: {
        options: ['bold', 'italic', 'underline', 'strikethrough'],
      },
      list: {inDropdown: false, options: ['unordered', 'ordered']},
      link: {inDropdown: false},
      unlink: {inDropdown: false},
    };
  }

  /**
   * @配置
   *
   * @returns {{separator: string, trigger: string, suggestions: (Array|*), suppressContentEditableWarning: boolean}}
   */
  getMentionConfig() {
    const {suggestion} = this.state;
    return {
      separator: ' ',
      trigger: '@',
      suggestions: suggestion,
    };
  }

  render() {
    const {editorState, initState, editMode} = this.state;
    return (
      <div className="card-comment">
        <Editor
          suppressContentEditableWarning
          initialContentState={initState}
          editorState={editorState}
          toolbarClassName="demo-toolbar"
          wrapperClassName="demo-wrapper"
          editorClassName="demo-editor"
          onChange={this.onEditorStateChange.bind(this)}
          uploadCallback={uploadImageCallBack}
          placeholder="请输入评价内容..."
          toolbar={this.getToolbarConfig()}
          mention={this.getMentionConfig()}
        />
        <div className="cc-operator">
          {
            editMode == EditorMode.add ?
              <div className="cco-item cco-confirm" onClick={this.confirm.bind(this)}>发表评论</div> : null
          }
          {
            editMode == EditorMode.modify ?
              <div className="cco-item cco-confirm" onClick={this.confirm.bind(this)}>更新评论</div> : null
          }
          {
            editMode == EditorMode.modify ?
              <div className="cco-item cco-cancel" onClick={this.cancel.bind(this)}>取消</div> : null
          }
        </div>
      </div>
    );
  }
}

MyEditNew.defaultProps = {
  issueId: null,
  commentId: null,
  mode: EditorMode.add,
  disappear: null,
};

MyEditNew.propTypes = {
  mode: React.PropTypes.number.isRequired,
  disappear: React.PropTypes.func,
};

function mapStateToProps(state) {
  return {
    boardUsers: state.board.boardUsers,
  };
}

export default connect(mapStateToProps)(MyEditNew);






`

**Comment by the1sky** [comment]
@jpuri below is my component source code:

```
import React from 'react';
import {convertToRaw, convertFromRaw, EditorState, ContentState, SelectionState, Modifier} from 'draft-js';
import {getEmptyRaw} from '../../utils/convert';
import {Editor} from 'react-draft-wysiwyg';
import uploadImageCallBack from '../../utils/uploadImageCallBack';
import {EditorMode} from '../../constants/editor';

class MyEditNew extends React.Component {
  constructor(props) {
    super(props);
    let editorState = EditorState.createEmpty();
    let initState = getEmptyRaw();
    this.state = ({
      initState,
      editorState,
    });
  }

  /**
   * 编辑器状态变更
   *
   * @param editorState
   */
  onEditorStateChange(editorState) {
    const contentState = convertFromRaw(editorState);
    const state = EditorState.createWithContent(contentState);
    this.setState({
      editorState: state,
    });
  };

  /**
   * 确认保存
   */
  confirm() {
    this.clearContent();
  }

  cancel() {
  }

  clearContent() {
    const editorState = EditorState.push(this.state.editorState, ContentState.createFromText(''));
    const initState = EditorState.push(this.state.initState, ContentState.createFromText(''));
    this.setState({editorState, initState});
  }

  /**
   * 工具栏配置
   *
   * @returns {{options: [string,string,string,string,string,string,string], inline: {options: [string,string,string,string]}, list: {inDropdown: boolean, options: [string,string]}, link: {inDropdown: boolean}, unlink: {inDropdown: boolean}}}
   */
  getToolbarConfig() {
    return {
      options: ['inline', 'image', 'link', 'unlink', 'emoji', 'fontSIze', 'list', 'colorPicker'],
      inline: {
        options: ['bold', 'italic', 'underline', 'strikethrough'],
      },
      list: {inDropdown: false, options: ['unordered', 'ordered']},
      link: {inDropdown: false},
      unlink: {inDropdown: false},
    };
  }

  /**
   * @配置
   *
   * @returns {{separator: string, trigger: string, suggestions: (Array|*), suppressContentEditableWarning: boolean}}
   */
  getMentionConfig() {
    const {suggestion} = this.state;
    return {
      separator: ' ',
      trigger: '@',
      suggestions: suggestion,
    };
  }

  render() {
    const {editorState, initState, editMode} = this.state;
    return (
      <div className="card-comment">
        <Editor
          suppressContentEditableWarning
          initialContentState={initState}
          editorState={editorState}
          toolbarClassName="demo-toolbar"
          wrapperClassName="demo-wrapper"
          editorClassName="demo-editor"
          onChange={this.onEditorStateChange.bind(this)}
          uploadCallback={uploadImageCallBack}
          placeholder="请输入评价内容..."
          toolbar={this.getToolbarConfig()}
          mention={this.getMentionConfig()}
        />
        <div className="cc-operator">
          {
            editMode == EditorMode.add ?
              <div className="cco-item cco-confirm" onClick={this.confirm.bind(this)}>发表评论</div> : null
          }
          {
            editMode == EditorMode.modify ?
              <div className="cco-item cco-confirm" onClick={this.confirm.bind(this)}>更新评论</div> : null
          }
          {
            editMode == EditorMode.modify ?
              <div className="cco-item cco-cancel" onClick={this.cancel.bind(this)}>取消</div> : null
          }
        </div>
      </div>
    );
  }
}

export default MyEditNew;
```

**Comment by jpuri** [comment]
Hey @the1sky, this should work. Did you tried `EditorState.createEmpty()`.

**Comment by the1sky** [comment]
@jpuri it doesn't work,maybe your can try it

**Comment by jpuri** [comment]
@the1sky: I just tried, it does works for me.

**Comment by the1sky** [comment]
@jpuri it's great, can you show me your example source code?

**Comment by jpuri** [comment]
@the1sky: check this: https://github.com/jpuri/react-draft-wysiwyg/blob/master/js/playground/index.js#L47

**Comment by jpuri** [comment]
@the1sky: are you still facing this issue ? Should I go ahead to close it ?

**Comment by the1sky** [comment]
@jpuri, great, I can clear content now, you can close this issue， thanks

**Comment by the1sky** [comment]
@jpuri with my project code, I can clear content, but I can not edit text properly( cursor alway at line first, and no effect with toolbar function), so I try this function with you example, there's not effect, and below are steps:

`git clone https://github.com/jpuri/react-draft-wysiwyg.git`
`yarn install`
`yarn add draft-utils`
`npm run build`
`npm start`

click 'Force Editor State'

**Comment by the1sky** [comment]
@jpuri I read your source code, and I find the right way finally, below:
```
this.setState({
      contentState: convertToRaw(ContentState.createFromText('')),
 });
```

**Comment by Veronica1026** [comment]
Hi, I am also facing the issue. I cannot input anything after clearing the text box using EditorState.createEmpty(). could you explain how your contentState works? I have looked through your code in playground and I am getting confused why are you using 
contentBlocks = convertFromHTML,
contentState = ContentState.createFromBlockArray
rawContentState 
those things once converted to another and then go to the editorstate.
Could you provide some explanation?
