### ISSUE TITLE
`onTab` as a property

### ISSUE THREAD

**Issue by MandarinConLaBarba** [jpuri/react-draft-wysiwyg#150]
It appears currently that `onTab` is not exposed as a property that can be passed through to the `Editor` component. The current logic appears to support behavior for navigating up/down within ordered/unordered list blocks.

For our current use-case, we need the ability to trap `TAB` events so that we can blur the current `Editor` component (and move selection to the next component in a list). 

Any thoughts on allowing `onTab` to be passed into the component, with the default handler being the current function (that changes list depth)?

I'm referring to these sections in the code:

https://github.com/jpuri/react-draft-wysiwyg/blob/master/js/src/components/Editor/index.js#L160
https://github.com/jpuri/draftjs-utils/blob/master/js/list.js#L52

**Comment by jpuri** [comment]
@MandarinConLaBarba: Ideally I think it should be indenting if current block is list else blur. I can make this change soon. Plz suggest.

**Comment by jpuri** [comment]
Or still better I think will be to have a property callback. If callback return true editor should not execute its own onTab else it should.

**Comment by jpuri** [comment]
@MandarinConLaBarba: I think that it should be if onChange property is present and returns true do nothing, else if current block is list indent else blur.

**Comment by MandarinConLaBarba** [comment]
@jpuri `onChange` or `onTab`? I would think you'd be able to provide an `onTab` property?

**Comment by jpuri** [comment]
Type fixed 😄

**Comment by MandarinConLaBarba** [comment]
OK sounds good thanks :)

**Comment by MandarinConLaBarba** [comment]
If you want some help on this I can submit a PR in the next few days @jpuri - thanks for quick responses!

**Comment by jpuri** [comment]
Yep, I will be happy to have a PR for this.

~ Thanks

**Comment by MandarinConLaBarba** [comment]
OK sure, will try to have something in the next few days :)

**Comment by jpuri** [comment]
I just pushed the change to master branch, it will be available after next release (soon) 😄

**Comment by jpuri** [comment]
Just released change in version `react-draft-wysiwyg@1.6.4`. Closing the issue.
