### ISSUE TITLE
Custom stylemap/colors in color picker

### ISSUE THREAD

**Issue by MandarinConLaBarba** [jpuri/react-draft-wysiwyg#156]
Currently it appears the `ColorPicker` and `customStyleMap` use fixed rgb values (inline styles prefixed with `color-` and `bgcolor-`). In our implementation we need to use our own set of colors for the color picker. Thoughts on allowing a custom map of colors to be passed to the toolbar configuration? 

Also, IMO it might be easier to name the inline styles semantically rather than in the format of `color-rgb(<r>, <g>, <b>), bgcolor-rgb(<r>, <g>, <b>)`. We are doing some transactions with `EditorState` outside the context of the `Editor` (for example, we have a button that sets the entire `EditorState` to black), so instead of having to set inline styles to `color-black` we're having to set them to `color-rgb(0,0,0)`. I think it would be useful to be able to pass in a color map for the color picker/`customStyleMap`, and make it so the inline style names for the `customStyleMap` use the keys in the color map.

Example proposed `Editor` property:

`customColors={{red: 'rgb(x, x, x)'}, blue: 'rgb(x, x, x)'}}`

The `ColorPicker` would use this to dynamically generate the modal color options, and `draftjs-utils` would use this to generate the `customStyleMap` color config.

Reference links:

https://github.com/jpuri/draftjs-utils/blob/master/js/inline.js#L120
https://github.com/jpuri/react-draft-wysiwyg/blob/master/js/src/components/ColorPicker/index.js#L127

**Comment by jpuri** [comment]
Hey @MandarinConLaBarba: I agree to most of what you mentioned above. I was on short vacation I will soon review and merge you PR. I will prioritize and do other changes also which you mentioned above.

Thanks

**Comment by MandarinConLaBarba** [comment]
@jpuri hope you had a nice vacation!

**Comment by jpuri** [comment]
The fix has been moved to master branch and will soon be released.

**Comment by jpuri** [comment]
Just released fix in version `react-draft-wysiwyg@1.6.4`. Closing the issue.
