### ISSUE TITLE
Invalid 'content' CSS value on .rdw-dropdown-carettoopen & .rdw-dropdown-carettoclose

### ISSUE THREAD

**Issue by legrego** [jpuri/react-draft-wysiwyg#162]
[/js/src/components/Dropdown/Dropdown/styles.css](https://github.com/jpuri/react-draft-wysiwyg/blob/9b03f71ce39e769e316cfa3d8ff084ff78dc2769/js/src/components/Dropdown/Dropdown/styles.css#L24), lines 24 and 35 each have a 'content' property set to `-`, which is not valid CSS.

Is there a particular reason the value is set this way? If not, I'd be happy to update it to read `content: '-';` rather than `content: -;`.

As-is, I cannot include the `/dist/react-draft-wysiwyg.css` stylesheet into my build pipeline due to a preprocessor error at that point.

**Comment by jpuri** [comment]
Thanks a lot @legrego for reporting the issue, the fix is already in develop branch and I will soon  release it.

**Comment by jpuri** [comment]
Change released in version `react-draft-wysiwyg@1.5.7` 😄

**Comment by legrego** [comment]
@jpuri thank you so much!
