### ISSUE TITLE
Image component ignore `readOnly` property

### ISSUE THREAD

**Issue by StGeass** [jpuri/react-draft-wysiwyg#164]
I can still see and use image controls within `readOnly` mode

Toolbar in the bottom left corner:
![2017-01-07 3 34 49](https://cloud.githubusercontent.com/assets/906496/21737580/42628420-d48b-11e6-9146-d2e1562fb84d.png)

**Comment by jpuri** [comment]
@StGeass: thanks for pointing this out, I will fix it soon.

**Comment by jpuri** [comment]
Fix has been released in version `react-draft-wysiwyg@1.5.5`.

Closing the issue.
