### ISSUE TITLE
Custom button

### ISSUE THREAD

**Issue by tammomueller** [jpuri/react-draft-wysiwyg#169]
What is the recommended way to add a button to the toolbar that handles behavior currently not implemented by the project.

Example: A button that adds a video player to the editor.

So far the only way to do it appears to be by forking the entire project.

Thanks.

**Comment by tammomueller** [comment]
After some research I implemented the functionality in my fork:

My requirements:

- Ability to add custom buttons to the toolbar.
- Ability for button source source code to live outside of the react-draft-wysiwyg project.
- Ability to use existing buttons.
- Keep modifications to react-draft-wysiwyg project to a minimum.

Implementation:

The editor can receive an array of toolbarCustomButtons. Each button is preconfigured but properties for `editorState` and `onChange` are set generically. Buttons receive a defaultIcon, for now I used strikethrough.

See my reference implementation.

I can created a pull request if desired.

[Code](https://github.com/jpuri/react-draft-wysiwyg/compare/master...tammomueller:master)

**Comment by jpuri** [comment]
Hi @tammomueller: sorry for delayed reply. Your approach looks nice, I am not sure if config is needed for custom button as users (of library) can provide their own directly to their component. Can you plz create a PR for this. Thanks a lot 👍

**Comment by jpuri** [comment]
Plz base PR on `develop` branch.

**Comment by tammomueller** [comment]
@jpuri I agree. After having implemented my own button I realized that config may not be needed. I will remove it and base the PR on develop. Hopefully getting to it later today

**Comment by tammomueller** [comment]
@jpuri Created [PR](https://github.com/jpuri/react-draft-wysiwyg/pull/170) based on develop
