### ISSUE TITLE
BUG on editor style and wrapper style react-draft-wysiwyg": "1.4.1"

### ISSUE THREAD

**Issue by kimdotnet** [jpuri/react-draft-wysiwyg#172]
Styling doesn't work with editorStyle props or wrapperStyle props, but works well with editorClassname or wrapperClassname.

My code looks like this:
```
const editorStyle = {
    border: '1px solid black',
    padding: '5px',
    borderRadius: '2px',
    height: '300px',
    width: '100%',
  };
```
```
<Editor
      editorState={editorState}
      onEditorStateChange={onEditorStateChange}
      uploadCallback={uploadImageCallback}
      editorStyle={editorStyle}
      toolbar={toolbar}
    />
```

**Comment by jpuri** [comment]
Hey @kimdotnet,

Let me check this one.

**Comment by jpuri** [comment]
@kimdotnet: its working for me, which version of editor are you using. This support was added in some of the latest versions.

**Comment by kimdotnet** [comment]
I'm using version 1.4.1 and after updated to 1.5.8 styling works well

Thank you
