### ISSUE TITLE
image upload issue: drag and drop

### ISSUE THREAD

**Issue by levbrie** [jpuri/react-draft-wysiwyg#176]
Dragging and dropping an image doesn't seem to work in the demo - only clicking to upload does.

**Comment by jpuri** [comment]
Thanks a lot @levbrie for reporting this. I will fix it soon.

**Comment by jpuri** [comment]
Just released `react-draft-wysiwyg@1.6.1` with the fix. Closing this issue.

Thanks a lot @levbrie for reporting 👍
