### ISSUE TITLE
npm下载使用上传图片有一个问题，请教一下在哪里设置

### ISSUE THREAD

**Issue by files3** [jpuri/react-draft-wysiwyg#180]
<img width="430" alt="wx20170120-225541 2x" src="https://cloud.githubusercontent.com/assets/15240870/22153755/9964307e-df63-11e6-87e0-4fe8ddedf9b1.png">

你好，问一下如图红箭头指的文字，有设置修改的吗？

**Comment by jpuri** [comment]
Hey @files3,

Please detail in english.

**Comment by devnetf** [comment]
@jpuri @files3  he was asking if it is possible to customize the style where the red arrows are pointing.

**Comment by jpuri** [comment]
Thanks @devnetf.

@files3: Toolbar property has a parameter `popupClassName` for images. You can use it to style popup above.

You can nest css selectors to access sections you have highlighted.

Hope that helps, please let me know.

**Comment by files3** [comment]
@jpuri thanks

**Comment by jpuri** [comment]
Closing the issue.

**Comment by BrotherDi** [comment]
请问最后是怎么用popupClassName实现的
