### ISSUE TITLE
Ability to add custom block renderer

### ISSUE THREAD

**Issue by tammomueller** [jpuri/react-draft-wysiwyg#181]
@jpuri We needed the ability to render custom blocks like tweets, instagram posts and video. The [PR](https://github.com/jpuri/react-draft-wysiwyg/pull/178) I created allows the extension of the current blockRenderer. 

Behavior:

- custom block renderer is optional
- When a custom block renderer is specified but does not return a block the default block renderer is executed.

**Comment by jpuri** [comment]
Hey @tammomueller, Thanks a lot for the PR. I will merge and release it over the weekend.

**Comment by jpuri** [comment]
Just released `react-draft-wysiwyg@1.6.0` 🎉 

Closing the issue.
