### ISSUE TITLE
Unwanted console logging

### ISSUE THREAD

**Issue by igolden** [jpuri/react-draft-wysiwyg#184]
Great plugin! I love the ease of use. Thanks for putting this together.

I'm adding this into a production project, and during development I'm plagued with too much logging from the editor. It makes it difficult to find the other logging information that I"m looking for, and I think this should be easily toggled (logging={true/false}) or turned off completely. Developers should probably be able to setup their own logging events based on the callbacks you provide.

![screen shot 2017-01-25 at 3 59 23 pm](https://cloud.githubusercontent.com/assets/12289711/22313003/ade11802-e317-11e6-8cb4-fd53cd78ac6e.png)

I could always fork and remove the logging too, but I thought I'd start here. Happy to submit a PR to knock this out if you'd like to make that a prop toggle.

**Comment by jpuri** [comment]
Hey @igolden: which version of plugin are you using. I already removed them in last version.

**Comment by jpuri** [comment]
Check version `1.6.3`.

**Comment by igolden** [comment]
I did a fresh install via 'npm install react-draft-wysiwyg --save'
yesterday, and it's at 1.6.2. I'll update, thanks!
