### ISSUE TITLE
Flexibility for users to add custom emojis.

### ISSUE THREAD

**Issue by jpuri** [jpuri/react-draft-wysiwyg#186]
Options has been developed to add custom emojis. It has been moved to master branch and will soon be released.

**Comment by gregBerthelot** [comment]
Would be great to be able to add any icon font like Awesome font :)

**Comment by jpuri** [comment]
@gregBerthelot: good idea, I will prioritize it. I do not have time immediately to do this, later I will work on it.

**Comment by jpuri** [comment]
Closing this issue, I have created another to support icons like font-awesome.
