### ISSUE TITLE
Links are behaving strangely

### ISSUE THREAD

**Issue by jimbol** [jpuri/react-draft-wysiwyg#187]
Hi, sweet library! I'm running into some troubles with links, though.

Links are not mutable.
Attempting to delete characters on links moves the cursor over an entity.

![link-strange-behavior](https://cloud.githubusercontent.com/assets/1278367/22352646/0d403bf6-e3eb-11e6-965a-bbc0f4a48072.gif)

If you point me in the right direction, I'll try to open a PR to fix it.

**Comment by jpuri** [comment]
@jimbol: I just noticed this, its not the intended behavior. I will fix it soon.

**Comment by jpuri** [comment]
I have pushed the fix to master and will soon release it.

**Comment by jpuri** [comment]
Just released fix in version `react-draft-wysiwyg@1.6.4`. Closing the issue.
