### ISSUE TITLE
Mention: make them case insensitive

### ISSUE THREAD

**Issue by Fouppy** [jpuri/react-draft-wysiwyg#188]
Hi,

Another small request, is to have the ability to make mentions case insensitive. In suggestion list I have names, which are capitalized, and users have to use capitals too, otherwise there's no match at all.

Thanks!

**Comment by jpuri** [comment]
Sounds good @Fouppy, I will add a flag in mention configuration to make them case insensitive 👍

**Comment by Fouppy** [comment]
Nice, thanks!
