### ISSUE TITLE
Pass through ...props

### ISSUE THREAD

**Issue by jamesbillinger** [jpuri/react-draft-wysiwyg#189]
Would you consider passing `...props` through to the draft-js editor?  I have to add a custom `blockRenderMap` to the Editor and am unable to do so with current code.  I can submit a PR if it would help.

**Comment by jpuri** [comment]
Check this: https://github.com/jpuri/react-draft-wysiwyg/blob/master/js/src/components/Editor/index.js#L76

you can already pass that as props, I missed to mention that in docs, I will add it

**Comment by jamesbillinger** [comment]
Ah, actually the `blockRenderMap` is a different property than the `blockRendererFn`.  I don't totally understand it - but suffice it to say that if I can't override the `blockRenderMap` for my custom video entity then draft-js throws a hard error.

**Comment by jpuri** [comment]
Just released fix in version `react-draft-wysiwyg@1.6.4`. Closing the issue.
