### ISSUE TITLE
Error while installing react-draft-wysiwyg

### ISSUE THREAD

**Issue by SoniaBalodi** [jpuri/react-draft-wysiwyg#193]
Hi,

Few days back when i installed this package it was fine. But today I am getting below error. Please suggest.

D:\new folder\Design-Studio\client>npm install react-draft-wysiwyg
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -
-get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:829:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:1
1)
npm WARN addRemoteGit     at emitOne (events.js:77:13)
npm WARN addRemoteGit     at Socket.emit (events.js:169:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:486:12)
npm WARN addRemoteGit  git://github.com/jpuri/draftjs-utils.git#e121403fdc2f2b7d
5750575341ec95714da9e887 resetting remote C:\Users\sonia_balodi\AppData\Roaming\
npm-cache\_git-remotes\git-github-com-jpuri-draftjs-utils-git-e121403fdc2f2b7d57
50575341ec95714da9e887-b0c54691 because of error: { [Error: Command failed: git
-c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori
gin.url' }
npm ERR! git clone --template=C:\Users\sonia_balodi\AppData\Roaming\npm-cache\_g
it-remotes\_templates --mirror git://github.com/jpuri/draftjs-utils.git C:\Users
\sonia_balodi\AppData\Roaming\npm-cache\_git-remotes\git-github-com-jpuri-draftj
s-utils-git-e121403fdc2f2b7d5750575341ec95714da9e887-b0c54691: Cloning into bare
 repository 'C:\Users\sonia_balodi\AppData\Roaming\npm-cache\_git-remotes\git-gi
thub-com-jpuri-draftjs-utils-git-e121403fdc2f2b7d5750575341ec95714da9e887-b0c546
91'...
npm ERR! git clone --template=C:\Users\sonia_balodi\AppData\Roaming\npm-cache\_g
it-remotes\_templates --mirror git://github.com/jpuri/draftjs-utils.git C:\Users
\sonia_balodi\AppData\Roaming\npm-cache\_git-remotes\git-github-com-jpuri-draftj
s-utils-git-e121403fdc2f2b7d5750575341ec95714da9e887-b0c54691: fatal: Unable to
look up github.com (port 9418) (This is usually a temporary error during hostnam
e resolution and means that the local server did not receive a response from an
authoritative server. )
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\sonia_balodi\\Ap
pData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "react-draft-
wysiwyg"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\so
nia_balodi\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://gith
ub.com/jpuri/draftjs-utils.git C:\Users\sonia_balodi\AppData\Roaming\npm-cache\_
git-remotes\git-github-com-jpuri-draftjs-utils-git-e121403fdc2f2b7d5750575341ec9
5714da9e887-b0c54691
npm ERR! Cloning into bare repository 'C:\Users\sonia_balodi\AppData\Roaming\npm
-cache\_git-remotes\git-github-com-jpuri-draftjs-utils-git-e121403fdc2f2b7d57505
75341ec95714da9e887-b0c54691'...
npm ERR! fatal: Unable to look up github.com (port 9418) (This is usually a temp
orary error during hostname resolution and means that the local server did not r
eceive a response from an authoritative server. )
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\new folder\Design-Studio\client\npm-debug.log

**Comment by jpuri** [comment]
Hey @SoniaBalodi, Trouble seems to be coming from this repo: `git://gith
ub.com/jpuri/draftjs-utils.git`.

Can you plz share your package.json.

**Comment by SoniaBalodi** [comment]
package.json :



{
  "name": "fabric-ui",
  "description": "ReactJS component library with crisp, elegant and super-easy-to-use components.",
  "author": "Jiten Poddar <>",
  "private": true,
  "version": "0.1.0",
  "license": "MIT",
  "main": "dist/fabric-ui.js",
  "scripts": {
    "build": "webpack --config webpack.config.js",
    "build-docs": "webpack --config webpack.dev.config.js",
    "start": "webpack-dev-server --content-base build/ --config webpack.dev.config.js --watch --progress --port 2992 --host 0.0.0.0 --inline --hot",
    "postinstall": "npm run build"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/maxcc0/fabric-ui"
  },
  "keywords": [
    "Component Library",
    "ReactJs Components",
    "ReactJS Material Components",
    "ReactJS",
    "MaterialUI components"
  ],
  "devDependencies": {
    "autoprefixer-loader": "^3.2.0",
    "babel-core": "^6.1.4",
    "babel-loader": "^6.1.0",
    "babel-plugin-transform-runtime": "^6.1.4",
    "babel-preset-es2015": "^6.14.0",
    "babel-preset-react": "^6.11.1",
    "babel-preset-react-app": "^0.2.1",
    "babel-preset-stage-0": "^6.5.0",
    "babel-register": "^6.1.4",
    "copy-webpack-plugin": "^4.0.1",
    "cross-env": "^2.0.0",
    "css-loader": "^0.23.1",
    "del": "^2.2.0",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.8.5",
    "fill-range": "^2.2.2",
    "json-loader": "^0.5.3",
    "less": "^2.5.3",
    "less-loader": "^2.2.0",
    "node-libs-browser": "^1.0.0",
    "open": "0.0.5",
    "react-router": "^2.8.1",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.6",
    "webpack": "^1.9.10",
    "webpack-dev-server": "^1.9.0"
  },
  "dependencies": {
    "babel-polyfill": "^6.1.4",
    "babel-runtime": "^6.0.14",
    "bootstrap": "^3.3.5",
    "classnames": "^2.2.5",
    "draft-js": "^0.9.1",
    "draft-js-editor": "^1.8.6",
    "draft-js-inline-toolbar-plugin": "^2.0.0-beta9",
    "draft-js-plugins-editor": "^2.0.0-beta9",
    "express": "^4.14.0",
    "formsy-react": "^0.18.1",
    "highcharts": "^4.2.7",
    "invariant": "^2.1.1",
    "jquery": "^3.1.1",
    "json-loader": "^0.5.4",
    "jsonfile": "^2.4.0",
    "lodash": "^4.16.2",
    "material-ui": "^0.15.4",
    "qrcode.react": "^0.6.1",
    "quill": "^1.1.7",
    "react": "^15.4.1",
    "react-addons-css-transition-group": "^15.3.1",
    "react-addons-transition-group": "^15.3.1",
    "react-barcode": "^1.1.0",
    "react-color": "^2.11.1",
    "react-data-grid": "1.0.46",
    "react-dom": "^15.3.1",
    "react-draft-wysiwyg": "^1.5.8",
    "react-quill": "^0.4.1",
    "react-rnd": "^4.2.0",
    "react-tap-event-plugin": "^2.0.0",
    "superagent": "^3.1.0"
  }
}


Not sure why it has started giving error today. Was working fine few days back. I was setting up my project in some other machine today and i got this while doing npm i/npm install

**Comment by SoniaBalodi** [comment]
One more update. I tried installing package - react-draft-wysiwyg separately in an empty folder. Getting below error:

D:\New folder (2)>npm install react-draft-wysiwyg
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -
-get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:829:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:1
1)
npm WARN addRemoteGit     at emitOne (events.js:77:13)
npm WARN addRemoteGit     at Socket.emit (events.js:169:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:486:12)
npm WARN addRemoteGit  git://github.com/jpuri/draftjs-utils.git#e121403fdc2f2b7d
5750575341ec95714da9e887 resetting remote C:\Users\sonia_balodi\AppData\Roaming\
npm-cache\_git-remotes\git-github-com-jpuri-draftjs-utils-git-e121403fdc2f2b7d57
50575341ec95714da9e887-b0c54691 because of error: { [Error: Command failed: git
-c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori
gin.url' }
npm ERR! git clone --template=C:\Users\sonia_balodi\AppData\Roaming\npm-cache\_g
it-remotes\_templates --mirror git://github.com/jpuri/draftjs-utils.git C:\Users
\sonia_balodi\AppData\Roaming\npm-cache\_git-remotes\git-github-com-jpuri-draftj
s-utils-git-e121403fdc2f2b7d5750575341ec95714da9e887-b0c54691: Cloning into bare
 repository 'C:\Users\sonia_balodi\AppData\Roaming\npm-cache\_git-remotes\git-gi
thub-com-jpuri-draftjs-utils-git-e121403fdc2f2b7d5750575341ec95714da9e887-b0c546
91'...
npm ERR! git clone --template=C:\Users\sonia_balodi\AppData\Roaming\npm-cache\_g
it-remotes\_templates --mirror git://github.com/jpuri/draftjs-utils.git C:\Users
\sonia_balodi\AppData\Roaming\npm-cache\_git-remotes\git-github-com-jpuri-draftj
s-utils-git-e121403fdc2f2b7d5750575341ec95714da9e887-b0c54691: fatal: Unable to
look up github.com (port 9418) (This is usually a temporary error during hostnam
e resolution and means that the local server did not receive a response from an
authoritative server. )
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\sonia_balodi\\Ap
pData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "react-draft-
wysiwyg"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\so
nia_balodi\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://gith
ub.com/jpuri/draftjs-utils.git C:\Users\sonia_balodi\AppData\Roaming\npm-cache\_
git-remotes\git-github-com-jpuri-draftjs-utils-git-e121403fdc2f2b7d5750575341ec9
5714da9e887-b0c54691
npm ERR! Cloning into bare repository 'C:\Users\sonia_balodi\AppData\Roaming\npm
-cache\_git-remotes\git-github-com-jpuri-draftjs-utils-git-e121403fdc2f2b7d57505
75341ec95714da9e887-b0c54691'...
npm ERR! fatal: Unable to look up github.com (port 9418) (This is usually a temp
orary error during hostname resolution and means that the local server did not r
eceive a response from an authoritative server. )
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\New folder (2)\npm-debug.log

**Comment by jpuri** [comment]
Hey @SoniaBalodi : I am looking at it, will soon update.

**Comment by jpuri** [comment]
Hey @SoniaBalodi : I just published version `react-draft-wysiwyg@1.6.5`, try this out. Looks like you had issues coz of access for this repo on the machine you were installing: git://gith ub.com/jpuri/draftjs-utils.git.

I am not sure why you got this issue since its working well for me, the change should anyways fix it for you also.

**Comment by SoniaBalodi** [comment]
Hey @jpuri : Thankyou so much , I am now able to install the package.

**Comment by jpuri** [comment]
👍  thanks for reporting the issue.

**Comment by saravanannnallasamy** [comment]
Hi 
I have installed the package successfully, but while running project it throw an error.

>> /home/happlo2/Projects/alpine-be/node_modules/react-draft-wysiwyg/dist/react-draft-wysiwyg.css:1
>> .rdw-option-wrapper {
>> ^
>> ParseError: Unexpected token
Warning: Error running grunt-browserify. 


I have import this in the jsx file where the editor is used,
import { Editor } from 'react-draft-wysiwyg';
import 'react-draft-wysiwyg/dist/react-draft-wysiwyg.css';

I don't why it throws error.

**Comment by erapatil** [comment]
Hi, I have just installed the editor and trying to use it. I can see the component in the output with all the operations performing perfectly,however when i am trying to access the content that is inside the editor(input which is being changed) it throws an error stating innerHTML cannot be accessed in emit change methodof EditableDiv JS file. 

EditableDiv.js:20 Uncaught TypeError: Cannot read property 'innerHTML' of undefined
    at Constructor.emitChange (EditableDiv.js:20)
    at Object.ReactErrorUtils.invokeGuardedCallback (ReactErrorUtils.js:70)
    at executeDispatch (EventPluginUtils.js:89)
    at Object.executeDispatchesInOrder (EventPluginUtils.js:112)
    at executeDispatchesAndRelease (EventPluginHub.js:44)
    at executeDispatchesAndReleaseTopLevel (EventPluginHub.js:55)
    at Array.forEach (<anonymous>)
    at forEachAccumulated (forEachAccumulated.js:25)
    at Object.processEventQueue (EventPluginHub.js:231)
    at runEventQueueInBatch (ReactEventEmitterMixin.js:18)

How can i access the content written inside the editor??  I need to access the content and store it in the database with the respective html tags. Which means if the user is making the content bold the data in the database should be stored as <b>Content</b>.
 Thanks for the Help!

**Comment by erapatil** [comment]
Like this. ![image](https://user-images.githubusercontent.com/24955463/28198068-e865c112-6878-11e7-9c15-329bf52cd82e.png)
