### ISSUE TITLE
¿Original Sass react-draft-wysiwyg.css file?

### ISSUE THREAD

**Issue by hmontes** [jpuri/react-draft-wysiwyg#196]
Hi!

First. Congratulations for your excellent component. Is really awesome!

Do you have the original .scss (or .sass) file for react-draft-wysiwyg.css? I want to customize a bit and its more easy with the original file.

Thanks

**Comment by jpuri** [comment]
Hey @hmontes:

Thanks :)
I did not used SASS for the project, I used .css files only which are in the repo next to .js file for each component.

**Comment by hmontes** [comment]
Oh. Sorry. I have problems to import the css. So, i unminify the css and i put the code in a personal sass file.

Thanks for the support. BTW, do you have themes?

**Comment by jpuri** [comment]
Hey @hmontes , No I do not have themes. There is one example at bottom here you can check: https://jpuri.github.io/react-draft-wysiwyg/#/demo

This is corresponding code: https://github.com/jpuri/react-draft-wysiwyg/blob/master/docs/src/components/Demo/index.js#L235

**Comment by hmontes** [comment]
Very nice work! And nice (and useful) demos.

Last question. In your experience. How you recommend to save the generated data (text and image links) in a sql database. In Json or Html?

Thanks for your excellent support :)

**Comment by jpuri** [comment]
Thanks :)
I strongly recommend JSON format. Convert it to html(https://github.com/jpuri/draftjs-to-html) using only when needed for display purpose.

**Comment by hmontes** [comment]
Thank you for your help and advices. :)

i try to edit the css like the quicly reply from github :)

**Comment by jpuri** [comment]
👍

**Comment by ducnvhn** [comment]
hi @hmontes . How do you integrated SASS in your component. I cannot style the nested element of the toolbar like with classes like : "rwd-block-wrapper", "rdw-inline-wrapper"..etc. 
Could you please share your solution please.

**Comment by hmontes** [comment]
@ducnvhn Fine.

The Inline component (B, I, etc) are images. So, you can't style directly. I made a trick with that.

First. I put a custom class to the inline via param. something like that:

```
...
render() {
    const toolbar = {
      options: ['inline', 'blockType', 'link', 'embedded', 'image', 'remove', 'history'],
      inline: {
        options: ['bold', 'italic', 'underline', 'strikethrough'],
        className: 'editor-opacity',
      },
      blockType: {
        inDropdown: false,
        options: ['H1', 'H2', 'H3', 'H4', 'H5', 'H6', 'Blockquote'],
        className: 'editor-buttons'
      },
      link: {className: 'editor-opacity'},
      embedded: {className: 'editor-opacity'},
      image: {className: 'editor-opacity'},
      remove: {className: 'editor-opacity'},
      history: {className: 'editor-opacity'}
    };

    return(
      <div className="editor-base">
        <Editor
          toolbarOnFocus
          editorClassName=''
          toolbar={toolbar}
        />
      </div>
    );
  }
```
And my classes:

```
.editor-buttons {
  color: #999;
  margin-right: 16px;
}

.editor-opacity {
  opacity: 0.45;
  filter: alpha(opacity=45);
}
```
I'm added opacity to the inline components. Later i can show you the final result and my custom css (i'm modified the default css to). Right now i'm working in another thing but soon i will return to draft and this plugin.

Good look :)

**Comment by hmontes** [comment]
Ah. I forget. To integrate to sass.

1. Copy th
1. Copy all the css content (node_modules/react-draft-wysiwyg/dist/react-draft-wysiwyg.css) to a new file. In my case. "style/sass/plugins/draft/_wysiwyg.scss"
2. Cut the final lines (From 989 line aprox. Where the comments begin), paste in http://unminify.com/ and remove the comments.
3. Paste the result in another file. "style/sass/plugins/draft/_draft.scss". This is the default draft css.
4. Add the files to your main.scss (@import 'plugins/draft/blablabla). Both files (_wysiwyg and draft).
5. Add the new classes on top of your _wysiwyg.scss

So. You have to unminified classes for total control of the plugin. Later, if you go to production, sass automatically compress the files for you.
