### ISSUE TITLE
Headers like button

### ISSUE THREAD

**Issue by hmontes** [jpuri/react-draft-wysiwyg#201]
Hi

I try to convert your default theme to something like that: http://codepen.io/Kiwka/pen/YNYvyG

But i have a question. Can i set a buttons for the headers (H1, H2, etc) instead of a dropdown menu?

Thanks

**Comment by jpuri** [comment]
Yes you can do this using this value in toolbar property: https://github.com/jpuri/react-draft-wysiwyg/blob/master/js/src/config/defaultToolbar.js#L46

**Comment by hmontes** [comment]
Can i replace the inline images (B, I, U, etc) with a text in a span?

**Comment by jpuri** [comment]
nopes they take icon, may be you can add icon with text 'Bold', ....

**Comment by hmontes** [comment]
good idea. I'll try.

Thank you for your effort :)

**Comment by hmontes** [comment]
Last question. Can i remove the "Normal" button in headers (Normal, h1, h2, ...)? The idea is. If nothing is pressed (any header button) the default behavior is a normal text.

**Comment by jpuri** [comment]
yes it shows in those options which  you pass in array: https://github.com/jpuri/react-draft-wysiwyg/blob/master/js/src/config/defaultToolbar.js#L47

docs also mention this

**Comment by hmontes** [comment]
I have a problem.

```
class TextArea extends React.Component {

  render() {
    const toolbar = {
      options: ['blockType', 'inline', 'link', 'embedded', 'image', 'remove', 'history'],
      inline: {
        options: ['bold', 'italic', 'underline', 'code']
      },
      blockType: {
        inDropdown: false
      }
    };

    return(
      <div className="editor-base">
        <Editor
          toolbar={toolbar}
        />
      </div>
    );
  }
}
```

The console shows an error: Uncaught TypeError: Cannot read property 'className' of undefined

But if i remove the "inline" options in the toolbar variable:

```
const toolbar = {
      options: ['blockType', 'inline', 'link', 'embedded', 'image', 'remove', 'history'],
      blockType: {
        inDropdown: false
      }
    };
```

The app works. What is the problem?

**Comment by hmontes** [comment]
Apparently. Is the "code" option the problem. Maybe is an old function documented. :)

**Comment by jpuri** [comment]
true :)

**Comment by hmontes** [comment]
WARNING: DraftEntity.create will be deprecated soon!
Please use "contentState.createEntity" instead. 

When i test the image function (i put from a link).

Sorry for use this issue. But i'm helping to improve your awesome WYSIWYG :)

**Comment by jpuri** [comment]
Thanks, yep I know this warning, I will fix it soon 👍
