### ISSUE TITLE
How can i pass a custom class to a blockquote?

### ISSUE THREAD

**Issue by hmontes** [jpuri/react-draft-wysiwyg#202]
Hi again.

I want to pass a class to the blockquote. How can i make that?

```
<div class="myQuoteClass">
  <p>This is a paragraph</p>
</div>
```
Thanks

**Comment by jpuri** [comment]
Hey,

You can do css styling for for tag `blockquote` if you need something more specific then add class to editor or dev enclosing editor and `.classEnclosing > blockquote`.

**Comment by hmontes** [comment]
How?

Can i inject a class to a H3 tag too?

(The final Text. NO THE TOOLBAR)

**Comment by jpuri** [comment]
```
blockquote {
  height: 50px;
  width: 50px;
}
```

Same for `h3`.

**Comment by hmontes** [comment]
Fine. But can i pass a custom css?

```
<blockquote class="myClass">
 ....
</blockquote>
```

Thank you for your patience :)

**Comment by jpuri** [comment]
Nopes :(

**Comment by hmontes** [comment]
No problem. I'll try to style the code.

Thanks :)
