### ISSUE TITLE
Unordered list and left/center/right align not working as expected

### ISSUE THREAD

**Issue by volkandkaya** [jpuri/react-draft-wysiwyg#203]
While testing the wysiwyg I found if I use ul and left align it breaks and doesn't show the bullet points from ul.

**Comment by jpuri** [comment]
Thanks for reporting 😄 . I will check and fix it.

**Comment by jpuri** [comment]
Fix has been moved to master, I will soon test more and release it.

**Comment by jpuri** [comment]
Fix released in `react-draft-wysiwyg@1.7.4`.
