### ISSUE TITLE
what does "file:..." mean in package.json ?

### ISSUE THREAD

**Issue by RifeWang** [jpuri/react-draft-wysiwyg#207]
what does "file:..." mean?  i downloaded your exmple and npm start but got the error "cannot find the file or dirctory".
this is the part of your /doc/package.json:
```
"draftjs-to-html": "file:../../draftjs-to-html",
"draftjs-to-markdown": "file:../../draftjs-to-markdown",
```

**Comment by jpuri** [comment]
Hey @RifeWang,

There are relative dependencies in docs. You can replace with latest versions of draftjs-to-html, and draftjs-to-markdown from npm.

**Comment by RifeWang** [comment]
thank you for your help!
