### ISSUE TITLE
adding a mention in the same paragraph as other text deletes everything after the mention

### ISSUE THREAD

**Issue by luisrudge** [jpuri/react-draft-wysiwyg#209]
repro: 
![editor](https://cloud.githubusercontent.com/assets/941075/22848333/caffad0c-efda-11e6-9798-8a41c8b0fa9e.gif)

**Comment by jpuri** [comment]
@luisrudge: I will check this soon.

**Comment by jpuri** [comment]
@luisrudge: I have moved fix to master branch. I will release it after some testing.

**Comment by jpuri** [comment]
Fix released in `react-draft-wysiwyg@1.7.4`.

**Comment by luisrudge** [comment]
Thanks @jpuri
