### ISSUE TITLE
tabIndex={-1} does not work

### ISSUE THREAD

**Issue by dderr** [jpuri/react-draft-wysiwyg#210]
Can not set tabIndex to -1 due to the tabIndex={0} on line 396 of src/components/Editor/index.js

Can this be removed for use this.props.tabIndex instead?

![image](https://cloud.githubusercontent.com/assets/585448/22851899/b3bdd874-eff5-11e6-8204-bc2c9cf68e2d.png)

**Comment by jpuri** [comment]
Thanks @dderr for reporting, I have moved to fix to master branch and will soon release.

**Comment by jpuri** [comment]
Fix released in `react-draft-wysiwyg@1.7.4`.
