### ISSUE TITLE
Running Example Failure: cannot find draftjs-to-html and draftjs-to-markdown

### ISSUE THREAD

**Issue by whamtet** [jpuri/react-draft-wysiwyg#213]
Hi Jyoti,

It appears from `config/webpack.dev.config.js` that you are directly linking repositories of `draftjs-to-html` and `draftjs-to-markdown`.  This caused a confusing 'not found' error for new users when running

    npm run start

without the linked repositories.

**Comment by jpuri** [comment]
Oh... I will remove it from there. Thanks a lot for pointing this.

**Comment by whamtet** [comment]
Thanks for the library!!

**Comment by jpuri** [comment]
😄 
fix is in repo now 👍
