### ISSUE TITLE
CSS for text input missing?

### ISSUE THREAD

**Issue by mikeLspohn** [jpuri/react-draft-wysiwyg#226]
I spent around 30 minutes trying to figure out why the plugin wasn't working for me, then I realized it was. There was no border around the contenteditable area, so I didn't even realize it was there and just thought I was doing something wrong. Is there default css that is missing for that?

**Comment by jpuri** [comment]
Hey @mikeLspohn: check `Styling Editor` section here: https://jpuri.github.io/react-draft-wysiwyg/#/docs

**Comment by IAMBESTMAN** [comment]
import Style from './less/richText.css';
render() {
    const { editorState } = this.state;
    return (
      <Row>
        <Editor
          editorState={editorState}
          editorClassName={Style.editorStyle}
          onEditorStateChange={this.onEditorStateChange}
        />
      </Row>
    );

**Comment by IAMBESTMAN** [comment]
import Style from './less/richText.css';
render() {
    const { editorState } = this.state;
    return (
      <Row>
        <Editor
          editorState={editorState}
          wrapperClassName="wrapper-class"
          editorClassName={Style.editorStyle}
          toolbarClassName="toolbar-class"
          onEditorStateChange={this.onEditorStateChange}
        />
      </Row>
    );

**Comment by IAMBESTMAN** [comment]
import Style from './less/richText.css';
`
render() {
    const { editorState } = this.state;
    return (
      <Row>
        <Editor
          editorState={editorState}
          editorClassName={Style.editorStyle}
          onEditorStateChange={this.onEditorStateChange}
        />
      </Row>
    );
  }
`

**Comment by abhisheksoni27** [comment]
Facing the same issue. Why is there no default border around the textarea?

I am importing the CSS file, by the way and everything else renders perfectly.

`import "react-draft-wysiwyg/dist/react-draft-wysiwyg.css";`

**Comment by jpuri** [comment]
@abhisheksoni27 : some users want to use it as full page editor. This is reason it has no borders by default.
