### ISSUE TITLE
Impossible to disable Hashtag

### ISSUE THREAD

**Issue by Amitom** [jpuri/react-draft-wysiwyg#239]
All is in the title but despite hashtag props is not defined, the Editor transforms #xxx to an hashtag.

:/

**Comment by jpuri** [comment]
Not for me
![screen shot 2017-03-14 at 11 19 40 pm](https://cloud.githubusercontent.com/assets/2182307/23914720/d2c52904-090c-11e7-8c58-17936a979de6.png)

**Comment by Amitom** [comment]
Visually it isn't, but in the generated html there is a link for me :/
![react-wysiwyg-hashtag](https://cloud.githubusercontent.com/assets/7102987/23914935/db3560c6-08bd-11e7-8ae4-78ee22add917.png)

**Comment by jpuri** [comment]
Check readme @Amitom: https://github.com/jpuri/draftjs-to-html

If you are passing a not-null `hashConfig` parameter it will generate hashtag in result.

**Comment by Amitom** [comment]
Doesn't work :(

draftToHtml(convertToRaw(currentContent)) <= NOK
draftToHtml(convertToRaw(currentContent), null) <=NOK

**Comment by jpuri** [comment]
On what versions are you, its working as expected in latest docs.

**Comment by Amitom** [comment]
Hum ... my bad I'm currently with 0.6.2 version of "draftjs-to-html", upgrade resolves my issue, sorry :/
