### ISSUE TITLE
V1.8.0 font family placeholder is "PingFang SC"

### ISSUE THREAD

**Issue by xaviertung** [jpuri/react-draft-wysiwyg#253]
V1.8.0 font family placeholder is "PingFang SC", is it a bug?

**Comment by jpuri** [comment]
@xaviertung: Font family dropdown now shows default font-family applied to editor.

**Comment by xaviertung** [comment]
@jpuri It happens by default config on V1.8, when switched to V1.7.9 all is OK.

**Comment by jpuri** [comment]
Yep by default it will show the font-family active in editor. This is behavior by Microsoft word.

**Comment by xaviertung** [comment]
@jpuri This is my demo:```
<Editor
						editorState={editorState}
						onEditorStateChange={this.onEditorStateChange.bind(this)}
						toolbarClassName="demo-toolbar"
						wrapperClassName="demo-wrapper-medium"
						editorClassName="demo-editor"
						toolbar={{
						  options: ['inline', 'blockType', 'fontSize', 'fontFamily', 'remove', 'history'],
						  inline: {
							options: ['bold', 'italic', 'underline', 'strikethrough'],
						  },
						}}
						/>
```
On V1.8.0 is shown "PingFang SC", and on V1.7.9 like you said.

**Comment by jpuri** [comment]
Hey @xaviertung `react-draft-wysiwyg@1.8.1` has the fix.

**Comment by xaviertung** [comment]
@jpuri Thank you to take my advice.

**Comment by jpuri** [comment]
Thanks a lot for advice @xaviertung and sorry for the delay :)
