### ISSUE TITLE
editorState.getImmutable is not a function

### ISSUE THREAD

**Issue by xiaoqian9** [jpuri/react-draft-wysiwyg#255]
![image](https://cloud.githubusercontent.com/assets/20238870/24134510/ced759b0-0e3f-11e7-974d-8df4aeca2430.png)

**Comment by xiaoqian9** [comment]
Does anyone know?

**Comment by jpuri** [comment]
Hey @xiaoqian9, which version of DraftJS are you using ?

**Comment by xiaoqian9** [comment]
@jpuri Draft v0.10.0

**Comment by grandMasterHash** [comment]
I am also experiencing this issue. I've basically followed the guide in the [draft.js docs for creating a controlled component](https://draftjs.org/docs/quickstart-api-basics.html#controlling-rich-text). I am also using draft v0.10.0
However I'm using `React.createClass` for creating my component instead of creating a subclass of `React.Component` and then using `getInitialState` to set an empty `EditorState`. Not sure if that should make a difference.

**Comment by dannymulvihill** [comment]
Same issue here. Also following the docs linked in @grandMasterHash's comment above. I logged out editorState in the onChange method and found that it looked like a ContentState object rather than EditorState. It turns out that the object passed as argument to onChange is `RawDraftContentState`.  I mucked around converting that back to a valid ContentState object, but that still did not work. 

Turns out the solution was to use onEditorStateChange property when creating the Editor instead of onChange.  Here is the code snippet from the docs: (https://jpuri.github.io/react-draft-wysiwyg/#/docs)

`onEditorStateChange = (editorState) => {
  this.setState({
    editorState,
  });
}
render() {
  const { editorState } = this.state;
  return (<Editor
    editorState={editorState}
    onEditorStateChange={this.onEditorStateChange}
  />)
}`

**Comment by grandMasterHash** [comment]
Thanks for catching that, @dannymulvihill !
I will give that a shot.

**Comment by SherlockStd** [comment]
Hi, I'm having a similar issue, I tried to use your comments and examples from the docs to solve the problem but I just can't make it work.

I'm trying here to store the `RawDraftContentState` object from the editor in the parent component so I can switch between multiples editor contents.

Here is my code:
```javascript
import React, { Component } from 'react'
import { Editor } from 'react-draft-wysiwyg'
import 'react-draft-wysiwyg/dist/react-draft-wysiwyg.css'
import { EditorState, convertToRaw, convertFromRaw } from 'draft-js'

class Notepad extends Component {
  constructor (props) {
    super(props)
    // pull datas from parent component if available in props
    const editorState = props.editorState ? convertFromRaw(props.editorState) : EditorState.createEmpty()
    this.state = {
      editorState
    }

    this.onEditorStateChange = this.onEditorStateChange.bind(this)
  }

  onEditorStateChange (editorState) {
    const rawCurrentContent = convertToRaw(editorState.getCurrentContent())
    this.setState({
      editorState
    })

    // push datas to parent component
    this.props.editorStateChanged(rawCurrentContent)
  }

  render () {
    const { editorState } = this.state
    return (
      <Editor
        editorState={editorState}
        wrapperClassName='demo-wrapper'
        editorClassName='demo-editor'
        onEditorStateChange={this.onEditorStateChange}
      />
    )
  }
}

export default Notepad
```

And here is the error:
```
Uncaught TypeError: editorState.getImmutable is not a function
    at Function.set (EditorState.js?6eae:78)
    at t.H.createEditorState (react-draft-wysiwyg.js?a021:6)
    at t.value (react-draft-wysiwyg.js?a021:6)
    at eval (ReactCompositeComponent.js?063f:347)
    at measureLifeCyclePerf (ReactCompositeComponent.js?063f:75)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js?063f:346)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js?063f:257)
    at Object.mountComponent (ReactReconciler.js?c56c:45)
    at ReactDOMComponent.mountChildren (ReactMultiChild.js?e1f8:236)
    at ReactDOMComponent._createInitialChildren (ReactDOMComponent.js?922a:703)
```

Please help me on this I don't know what to do, this is mandatory for our project.
Thanks in advance !

**Comment by rizwankhangouri** [comment]
I am also getting same error-
TypeError: editorState.getImmutable is not a function
  76 | };
  77 | 
  78 | EditorState.set = function set(editorState, put) {
> 79 |   var map = editorState.getImmutable().withMutations(function (state) {
  80 |     var existingDecorator = state.get('decorator');
  81 |     var decorator = existingDecorator;
  82 |     if (put.decorator === null) {

**Comment by elmoss** [comment]
it does't support react ^16.1.1 ?

**Comment by indefinitelee** [comment]
what is the highest version of react supported? are hooks supported?

**Comment by flashtheman** [comment]
Did anyone find out more?

**Comment by rryando** [comment]
> it does't support react ^16.1.1 ?

it does support hooks, i'm using react ^16.13.1 and everything workout well,

if you're using hooks, make sure to set the state like this
```
  const [editorState, setEditorState] = useState(EditorState.createEmpty())

  const onEditorStateChange = (editorState) => {
    setEditorState(editorState)
  }
```

and don't forget to import the EditorState from draft-js
```
import { Editor } from 'react-draft-wysiwyg';
import { EditorState } from 'draft-js';
import 'react-draft-wysiwyg/dist/react-draft-wysiwyg.css';
```

on the render method
```
<Editor
  editorState={editorState}
  toolbarClassName="toolbarClassName"
  wrapperClassName="wrapperClassName"
  editorClassName="editorClassName"
  onEditorStateChange={onEditorStateChange}
/>
```

**Comment by kanjalkarMplus** [comment]
State

`
const [editorState, setEditorState] = useState(EditorState.createEmpty())
`


On change

`
const onEditorStateChange = (editorState) => {
    setEditorState(editorState)
}
`


To get current value in string

`
editorState.getCurrentContent().getPlainText()
`

**Comment by poojashelar224** [comment]
**zxzCxcxz******

**Comment by jmsn123** [comment]
> > it does't support react ^16.1.1 ?
> 
> it does support hooks, i'm using react ^16.13.1 and everything workout well,
> 
> if you're using hooks, make sure to set the state like this
> 
> ```
>   const [editorState, setEditorState] = useState(EditorState.createEmpty())
> 
>   const onEditorStateChange = (editorState) => {
>     setEditorState(editorState)
>   }
> ```
> 
> and don't forget to import the EditorState from draft-js
> 
> ```
> import { Editor } from 'react-draft-wysiwyg';
> import { EditorState } from 'draft-js';
> import 'react-draft-wysiwyg/dist/react-draft-wysiwyg.css';
> ```
> 
> on the render method
> 
> ```
> <Editor
>   editorState={editorState}
>   toolbarClassName="toolbarClassName"
>   wrapperClassName="wrapperClassName"
>   editorClassName="editorClassName"
>   onEditorStateChange={onEditorStateChange}
> />
> ```

This worked for me

**Comment by vanitha6** [comment]
> onEditorStateChange

Yes, It is

**Comment by felipenmoura** [comment]
I took me quite some annoying hours to solve it...but I figured it out.

I was setting the editorState with the contentState...

```
const contentState = stateFromMarkdown( valueInMD );
const editorState = EditorState.createWithContent( contentState );
setEditorState( editorState );
```

Documentation could have helped more.
I hope this helps other people facing the same situation.
