### ISSUE TITLE
Clicking on image upload box does not open file browser!

### ISSUE THREAD

**Issue by ducnvhn** [jpuri/react-draft-wysiwyg#256]
I try to click on Image upload box which does not open the file browser to browse the file as demo page. Drag and drop works as expected. Anyone else have same issue ? _**_react-draft-wysiwyg": "^1.7.4",_**_

**Comment by jpuri** [comment]
@ducnvhn : it works on latest version `react-draft-wysiwyg@1.8.3`.

**Comment by ducnvhn** [comment]
updated to @1.8.3 but still cannot open the file browser (Google Chrome / Firefox / Android browser..).

**Comment by jpuri** [comment]
Hey @ducnvhn: do you face same issue in demo also, I am wondering if something else on you page is blocking it.

**Comment by ducnvhn** [comment]
works as expected on Demo page. Have no idea why. Cannot see any error in console. Drag and Drop still work but clicking not. I have uploaded it [here](https://vstack.herokuapp.com) . you can try it here.

**Comment by ducnvhn** [comment]
Sorry @jpuri . I manage to upgrade and it works now. Thank you .

**Comment by jpuri** [comment]
👍
