### ISSUE TITLE
if i modify, fontsize will add much 12！

### ISSUE THREAD

**Issue by GoFighting** [jpuri/react-draft-wysiwyg#258]
![Uploading image.png…]()

**Comment by GoFighting** [comment]
![image](https://cloud.githubusercontent.com/assets/13616686/24230118/4fd43032-0fb8-11e7-8442-b09074219b40.png)

**Comment by GoFighting** [comment]
![image](https://cloud.githubusercontent.com/assets/13616686/24230126/567ac496-0fb8-11e7-9f4e-a7b28ac2b580.png)
like this

**Comment by jpuri** [comment]
Plz @GoFighting check with the latest version, this issue is fixed.

**Comment by jpuri** [comment]
Closing the issue.
