### ISSUE TITLE
CSS issue on .rdw-dropdown-selectedtext

### ISSUE THREAD

**Issue by andychinka** [jpuri/react-draft-wysiwyg#260]
As my default color on link is white i.e `a {    color: white}`

So I cannot see the selected font-size in the UI (the background is white also)

It would be nice to add the color style to .rdw-dropdown-selectedtext

**Comment by jpuri** [comment]
Hey @andychinka,

Try to use this class : https://github.com/jpuri/react-draft-wysiwyg/blob/master/js/src/config/defaultToolbar.js#L54

**Comment by jpuri** [comment]
@andychinka: I hope your issue got fixed, can I close it ?
