### ISSUE TITLE
Add a default font size

### ISSUE THREAD

**Issue by NoZiL** [jpuri/react-draft-wysiwyg#261]
It seems that toolbar props have no defaults for lists (e.g. from non styled text, the chosen font size, style, or font-family are the first of the respective arrays)

**Comment by jpuri** [comment]
Hey @NoZiL, active font-size and font-family are selected in dropdown, make sure that the font size/family you apply to editor class is present in drop-down options.

By default active block type is normal which is paragraph.

Plz let me know if you need more details.

**Comment by NoZiL** [comment]
Oh ok, there is no default inline style applied, it takes the style applied to p in my app.

Thank you and great job !

**Comment by jpuri** [comment]
Hey @NoZiL, closing the issue.
