### ISSUE TITLE
Diabling the textbox

### ISSUE THREAD

**Issue by Srisuk** [jpuri/react-draft-wysiwyg#262]
Hi I want to disable the textbox.
The content inside the text box is visible but the user cannot edit it and make it like READ ONLY.

Kindly help to resolve this.

**Comment by roychoo** [comment]
There is a '''readOnly''' prop you can use.

**Comment by Srisuk** [comment]
Thanks :)

**Comment by jpuri** [comment]
Hey @Srisuk , should I go ahead to close this issue ?
