### ISSUE TITLE
Change Toolbar Modal Text

### ISSUE THREAD

**Issue by nadinestpierre** [jpuri/react-draft-wysiwyg#263]
Hiya, 
Is there a way to change the text for the tool bar?
I.E when you click on the link button it says Link Title and Link Target - Is there a way to change this??

**Comment by jpuri** [comment]
@nadinestpierre: Not right now, though I plan to do this change.

**Comment by jpuri** [comment]
@nadinestpierre: you can not user localization property also not this, plz check doc.

release version: `react-draft-wysiwyg@1.9.2`

**Comment by rakibsxyz** [comment]
hey! is there any way to edit the modal text now?
