### ISSUE TITLE
Use of Math.random to get wrapperId breaks server side rendering

### ISSUE THREAD

**Issue by nss213** [jpuri/react-draft-wysiwyg#266]
Using Math.random to get the wrapperId results in a nondeterministic rendering. This breaks server side rendering since the DOM cannot be reconciled on the client. Suggestion: allow the wrapperId to be passed in on the props.

**Comment by jpuri** [comment]
Hey @nss213: I agree to your suggestion. Would you like to create a PR for this change ?

**Comment by nss213** [comment]
I started doing this, but it seems like the only use of `wrapperId` is so that `ModalHandler` can get a reference to the wrapper DOM node using `getElementById` so that it can add a click handler. It seems like this could be avoided by using a `ref` or by setting an `onClick` handler on the actual wrapper `div`, no? Perhaps I am misunderstanding?

**Comment by Reggino** [comment]
@nss213 I ran into this too... The use of `ref` seems proper here...

**Comment by jpuri** [comment]
`wrapperId` can now be passed as prop.
