### ISSUE TITLE
how can i set link target="_blank"

### ISSUE THREAD

**Issue by GoFighting** [jpuri/react-draft-wysiwyg#267]

**Comment by jpuri** [comment]
You can not atm :( though I plan to add this option.

**Comment by gregBerthelot** [comment]
Should be fixed here https://github.com/jpuri/react-draft-wysiwyg/pull/281

**Comment by jpuri** [comment]
Its fixed now, default option can be specified here: https://github.com/jpuri/react-draft-wysiwyg/blob/master/js/src/config/defaultToolbar.js#L108.
