### ISSUE TITLE
Why I cannot use the method of file upload?  

### ISSUE THREAD

**Issue by chunhsiao** [jpuri/react-draft-wysiwyg#268]
Hi, 
I have using the configuration code, but why not show the method of file upload?

`image: {
            uploadEnabled: true,
        }`

![image](https://cloud.githubusercontent.com/assets/12069539/24496601/4515d8cc-156b-11e7-9000-390be4a818b5.png)

**Comment by jpuri** [comment]
@chunhsiao, you also need to provide a call back for file upload, for details plz check docs.

**Comment by chunhsiao** [comment]
@jpuri Thanks..

**Comment by jpuri** [comment]
Hey @chunhsiao,

I am closing the issue, feel free to re-open or drop comments in case you face any more issues.
