### ISSUE TITLE
How to transform Link into plain text

### ISSUE THREAD

**Issue by MaDejing** [jpuri/react-draft-wysiwyg#270]
If '< a >' tag is contained in paste text, how can i transform the Link into plain text?
<img width="328" alt="2017-04-01 11 43 22" src="https://cloud.githubusercontent.com/assets/12246865/24575142/72e9326a-16d0-11e7-8566-de38d629640c.png">

**Comment by jpuri** [comment]
Editor is not great at handling pasted content atm, but you can create your own draftjs hook and use editor as controlled component.

Let me know if you have issues / queries in doing that.

**Comment by MaDejing** [comment]
@jpuri Hi, jpuri, thanks for your help.
I find a property named stripPastedStyles, and i give a 'true' value, then it works.
<img width="452" alt="2017-04-05 4 14 25" src="https://cloud.githubusercontent.com/assets/12246865/24696132/fe9b5e30-1a1a-11e7-8a5a-1d148b5643f0.png">

**Comment by jpuri** [comment]
Sounds good, closing this issue !
