### ISSUE TITLE
ConvertFromHtml Image has problem

### ISSUE THREAD

**Issue by MaDejing** [jpuri/react-draft-wysiwyg#271]
I just upload a image file like this
<img width="614" alt="2017-04-01 11 48 54" src="https://cloud.githubusercontent.com/assets/12246865/24575208/c6b39f88-16d1-11e7-8402-94ab0e49b9b5.png">

Then I use convertFromHtml to get the new editstate.
When I edit the rich text, I cannot select anything.

<img width="1012" alt="2017-04-01 11 48 31" src="https://cloud.githubusercontent.com/assets/12246865/24575188/77f33f3e-16d1-11e7-8cc5-0a521cf96e96.png">
and the html becomes to
<img width="873" alt="2017-04-01 11 56 57" src="https://cloud.githubusercontent.com/assets/12246865/24575226/5805b192-16d2-11e7-8dab-367c3916eaa5.png">

PS: I use draft-js-export-html to get the html.

**Comment by jpuri** [comment]
Hey @MaDejing try to use https://github.com/jpuri/html-to-draftjs to create editor state.

**Comment by MaDejing** [comment]
Hey @jpuri i used html-to-draftjs, and it works. Thanks for your help.

**Comment by jpuri** [comment]
Closing the issue.
