### ISSUE TITLE
setting EditorState property makes react-draft-wysiwyg not working.

### ISSUE THREAD

**Issue by jasonfoy99** [jpuri/react-draft-wysiwyg#274]
The following is source code. draft-js version is 0.10.0 and react-draft-wysiwyg version is 1.9.0.

If I remove the editorState property from Editor component, I can edit things. Adding this property somehow makes the component unusable. Any kind of styling such as bolding or underlining does not work and back/delete keys seem to be disabled.

I guess I missed something but I don't know what it is.

	import React, {Component, PropTypes} from 'react';
	import { convertToRaw,EditorState,ContentState } from 'draft-js';
	import { Editor } from 'react-draft-wysiwyg';
	import './styles/my-react-draft-wysiwyg.css';

	export default class RichTextEditor extends Component {

	    state = {
	    	editorState: EditorState.createEmpty()
	    }
	    
        onEditorStateChange = (index, editorState) => {
	    } 

   	   render() {
	    	return (
	      		<Editor 
	      			editorState={this.state.editorState}
	      			onEditorStateChange={this.onEditorStateChange}
	      		/>
	    	);
	   }
	}

**Comment by jpuri** [comment]
@jasonfoy99 : you have turned editor into a controlled component, make sure you keep `editorState` updated in your component state.

```
    onEditorStateChange = (editorState) => {
      this.setState({ editorState });
    } 

```

**Comment by jasonfoy99** [comment]
I actually had removed that line. When I use this.setState({ editorState }), I cannot even type anything. When I debug it, the editorState is always undefined. I have no idea what is going on. 

Here is what i want to do, I would like to initialize the component with certain presaved editorState. After i am done with editing, I would like to save to my store. Can you kindly tell me what is the best approach to do it? Thanks in advance.

**Comment by jasonfoy99** [comment]
To be more accurate, when the callback onEditorStateChange is called, the editorState is always undefined.

**Comment by jasonfoy99** [comment]
sorry, it is my stupid mistake, the signature of my callback funtion is wrong.

**Comment by jpuri** [comment]
Closing the issue.
