### ISSUE TITLE
Allow externals decorators

### ISSUE THREAD

**Issue by acidio** [jpuri/react-draft-wysiwyg#276]
Hi @jpuri, I would like to create a new component for Internal links and for it will be necessary to create a new decorator and a new component into the customToolbarButtons. I saw that we to not have the possibility to add a new decorator, am I wrong?

**Comment by jpuri** [comment]
Hey @acidio: You are right its not possible atm. But its not big change to add this. I will try to do this over the weekend - so hopefully on Monday you have it.

**Comment by acidio** [comment]
Thank you to answer so fast :)

In this meantime, I forked the project and add the property if do you it's good I can send a PR.

Here is: https://github.com/code-berlin/react-draft-wysiwyg/commit/1b087f7b3b189ef9c186298fa678a8e9d6a2ab0f

I also added options for the user decide if the link should open in the main or in a new window.
https://github.com/code-berlin/react-draft-wysiwyg/commit/d64e8edd44886f6eeb231f8f678395add32e8751

Thanks.

**Comment by jpuri** [comment]
Great, if you can create these PRs (or single PR) I will be happy to make a quick release over the weekend for you.

**Comment by acidio** [comment]
@jpuri the PR with decorators: https://github.com/jpuri/react-draft-wysiwyg/pull/280

**Comment by jpuri** [comment]
`react-draft-wysiwyg@1.9.2` has the change. Property name I have changed to customDecorators.

Thanks 👍
