### ISSUE TITLE
TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by scho7623** [jpuri/react-draft-wysiwyg#282]
When running unit test, an error is thrown here:
https://github.com/jpuri/react-draft-wysiwyg/blob/d600280472627a07ca413d8f65d12a50a659325e/js/src/event-handler/modals.js#L15

`document.getElementById(wrapperId);` is returning `null`, and throws an error `TypeError: Cannot read property 'addEventListener' of null`

Do we need null check here?

**Comment by jpuri** [comment]
Hi @scho7623 : I do not get this issue. Test cases are not able to get document, this ideally should not happen since I have configured `jsdom`. Can you plz check `jsdom` dependency is installed correctly.

**Comment by scho7623** [comment]
@jpuri: I'm running my tests using `jest`, and `jsdom` is installed as a dependency of `jest`.

**Comment by jpuri** [comment]
I also faced similar issue with JEST in another project, I am not sure looks like it needs somemore configurations. I used mocha here:

- https://github.com/jpuri/react-draft-wysiwyg/blob/master/config/test-setup.js

- https://github.com/jpuri/react-draft-wysiwyg/blob/master/package.json#L69

**Comment by scho7623** [comment]
may be It could be a problem in `jest`?

**Comment by jpuri** [comment]
It probably requires some jest configuration, closing this issue for now.

**Comment by wangmeijian** [comment]
How do you solve the problem behind it?

**Comment by wangmeijian** [comment]
How do you solve it?
