### ISSUE TITLE
Can't use the internationalization

### ISSUE THREAD

**Issue by kuhippo** [jpuri/react-draft-wysiwyg#285]
Thank you very much for the work of the author.But I found that there are problems in actual use.
1. Can't use the internationalization in making source file I see related documents, but not of NPM download
2. The icon is not aligned in actual use

**Comment by kuhippo** [comment]
I feel the need to add  CSS a{color: black} and a:hover{color: black}, or you will and theme library conflict

**Comment by jpuri** [comment]
@kuhippo : I could not understand the issues, can you plz add code examples or screen shots.
