### ISSUE TITLE
layout of colorPicker 

### ISSUE THREAD

**Issue by nanke-** [jpuri/react-draft-wysiwyg#287]
![image](https://cloud.githubusercontent.com/assets/2994668/25007482/41af513a-2093-11e7-84b3-58875928078e.png)

is there any solutions to fix it?

**Comment by alfaslash** [comment]
This problem is caused by using rule`box-sizing: border-box`.
If you override rule `box-sizing: content-box` for editor the problem will be solved.

**Comment by jpuri** [comment]
Latest release `react-draft-wysiwyg@1.9.7` fixes this color picker issue.
