### ISSUE TITLE
`o.getCurrentContent(...).createEntity is not a function` when creating a link

### ISSUE THREAD

**Issue by palmerev** [jpuri/react-draft-wysiwyg#290]
<img width="1257" alt="screen shot 2017-04-15 at 8 17 59 pm" src="https://cloud.githubusercontent.com/assets/8763349/25068443/ebeb59b0-2218-11e7-91ab-8a6ded245848.png">

Whenever I try to create a link using the link icon / menu in the default toolbar, I get the error shown above.

Using draft-js 0.9.1 and react-draft-wysiwyg 1.9.3

**Comment by jpuri** [comment]
Hey @palmerev : plz try with latest draft version. This seems to be working well in docs: https://github.com/jpuri/react-draft-wysiwyg/blob/master/docs/package.json#L64

**Comment by palmerev** [comment]
@jpuri It's working now with draft-js@0.10.0 and react-draft-wysiwyg@1.9.4

Thank you.
