### ISSUE TITLE
French, Chinese and Russian Translation of new labels.

### ISSUE THREAD

**Issue by jpuri** [jpuri/react-draft-wysiwyg#291]
Can someone plz help with these translations:

1. French: https://github.com/jpuri/react-draft-wysiwyg/blob/master/js/src/i18n/fr.js#L37

2. Russian: https://github.com/jpuri/react-draft-wysiwyg/blob/master/js/src/i18n/ru.js#L37

3. Chinese: https://github.com/jpuri/react-draft-wysiwyg/blob/master/js/src/i18n/zh.js#L37

**Comment by mguijarr** [comment]
Hello :)
See PR #292 for french.
Hope this helps !

**Comment by jpuri** [comment]
Thanks @mguijarr , it does 👍

**Comment by jpuri** [comment]
I still need help with Chinese, can someone plz check.

**Comment by jpuri** [comment]
Thanks to all contributors :)
