### ISSUE TITLE
How to remove icons from toolbar?

### ISSUE THREAD

**Issue by gyarasu** [jpuri/react-draft-wysiwyg#295]
Hello.
Thanks for your grate component!

I have an question.
I want to know how to remove icons which are not needed from toolbar.

In my page, I don't need 'emoji' in toolbar like below image.
![customtoolbar](https://cloud.githubusercontent.com/assets/4948588/25112037/9cd63580-2429-11e7-9559-1aeeb0aee6cf.png)

**Comment by jpuri** [comment]
@gyarasu: Toolbar is highly configurable. You can use property `toolbar`, check this: https://github.com/jpuri/react-draft-wysiwyg/blob/master/docs/src/components/Demo/index.js#L136

This is default configuration: https://github.com/jpuri/react-draft-wysiwyg/blob/master/js/src/config/defaultToolbar.js

**Comment by gyarasu** [comment]
@jpuri 
I got it!

To be honest, I had a problem that image's defaultSize option doesn't work.
I solved the problem by updating the module from 1.7.3 to version 1.9.4.

Thank you very much.

**Comment by vladluca** [comment]
I've followed the demos and docs, but I am still unable to remove the emoji from the toolbar. Any help would be great, thanks.

**Comment by shivarajalagond** [comment]
@vladluca : I hope you figured it out. 
Someone looking to remove options from toolbar,

In the render part of Editor,
<Editor
          toolbar ={
              {
                options:['inline', 'link', 'list', 'image' ],  // This is where you can specify what options you need in 
                                                                           //the toolbar and appears in the same order as specified    
                inline:                                                                              
                {
                  options:['bold', 'italic', 'underline']  //  this can be specified as well, toolbar wont have 
                                                                          //strikethrough, 'monospace', 'superscript', 'subscript' 
                },
                image : 
                  { 
                    alignmentEnabled: false,
                    uploadCallback: this.UploadImageCallBack,
                    alt: { present: true, mandatory: false },
                    previewImage: true
                  }  
            } 
          }
          editorState = { this.state.value }
          onEditorStateChange={ this.handleChange }
        />

On the same line, it would be possible to configure the toolbar as you want.

[Document ](https://jpuri.github.io/react-draft-wysiwyg/#/docs?_k=jjqinp)  --> Default toolbar options

**Comment by Rohitprabha** [comment]
use the following format to remove unwanted icons/buttons.


<Editor
                  editorState={editorState}
                  onEditorStateChange={handleEditorChange}
                  toolbar={{
                    options: ["inline", "list", "link", "history"],
                    list: {
                      options: ["unordered", "ordered"],
                    },
                  }}
                  wrapperClassName="wrapper-class"
                  editorClassName="editor-class"
                  toolbarClassName="toolbar-class"
                />

**Comment by Rohitprabha** [comment]
> I've followed the demos and docs, but I am still unable to remove the emoji from the toolbar. Any help would be great, thanks.

<Editor
                  editorState={editorState}
                  onEditorStateChange={handleEditorChange}
                  toolbar={{
                    options: ["inline", "list", "link", "history"],
                    list: {
                      options: ["unordered", "ordered"],
                    },
                  }}
                  wrapperClassName="wrapper-class"
                  editorClassName="editor-class"
                  toolbarClassName="toolbar-class"
                />

**Comment by Rohitprabha** [comment]
> I've followed the demos and docs, but I am still unable to remove the emoji from the toolbar. Any help would be great, thanks.

use the following format to remove unwanted icons/buttons.

<Editor
editorState={editorState}
onEditorStateChange={handleEditorChange}
toolbar={{
options: ["inline", "list", "link", "history"],
list: {
options: ["unordered", "ordered"],
},
}}
wrapperClassName="wrapper-class"
editorClassName="editor-class"
toolbarClassName="toolbar-class"
/>
