### ISSUE TITLE
How to custom render Mention

### ISSUE THREAD

**Issue by lovebum91** [jpuri/react-draft-wysiwyg#296]
Hi, Please tell me. 
How can I custom render suggestion in Mention. I want to display as image below:
Linhk: https://ibb.co/ewN5d5

**Comment by jpuri** [comment]
Sorry @lovebum91 , this is not supported atm :(

**Comment by raduGaspar** [comment]
@jpuri did you manage to add support for custom rendering on mentions?

**Comment by trungdunghbvn** [comment]
sdsdds @jpuri

**Comment by wli-dev3** [comment]
+1

**Comment by lovebum91** [comment]
> Sorry @lovebum91 , this is not supported atm :(

**Comment by mchaledg19** [comment]
How is the status of this?

**Comment by vmc08** [comment]
Shit i need this, 2020
