### ISSUE TITLE
Styling bug for underline

### ISSUE THREAD

**Issue by chungchi300** [jpuri/react-draft-wysiwyg#298]
![react draft wysiwyg](https://cloud.githubusercontent.com/assets/5248427/25124320/ef4cec76-245d-11e7-88b7-83102ac8d2d2.png)

If we convert the above draftjs to html, we get
![advboom](https://cloud.githubusercontent.com/assets/5248427/25124379/1f365e18-245e-11e7-90f5-2dc30597ddff.png)

It is caused by the draft-js-to-html interpreted the draft js state to html wrongly.Is any fix for it?

**Comment by jpuri** [comment]
I see, I will fix this issue in draftjs-to-html.

Thanks a lot for mentioning this issue.

**Comment by jpuri** [comment]
`draftjs-to-html@0.7.2` has the fix.

**Comment by jpuri** [comment]
Closing the issue, feel free to re-open if you still face issue.
