### ISSUE TITLE
Errors in console.

### ISSUE THREAD

**Issue by smendozaisf** [jpuri/react-draft-wysiwyg#299]
I'm having this two errors when using the package:

`Warning: AutosizeInput: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

and

`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

This is my code:

```
onEditorStateChange = (editorState) => {
    this.setState({
      editorState,
    });
  }

<Editor
editorStyle={styles.editor}
editorState={editorState}
onEditorStateChange={this.onEditorStateChange}
/>
```

I'm using:
`"draft-js": "^0.10.0"`
`"react-draft-wysiwyg": "^1.9.4"`
`    "react": "^15.5.4"`

**Comment by jpuri** [comment]
This should be fixed in latest release `react-draft-wysiwyg@1.9.7`.
