### ISSUE TITLE
Get all mentions from editorState

### ISSUE THREAD

**Issue by alfaslash** [jpuri/react-draft-wysiwyg#304]
Can I any way to get all  mentions from the editorState?

**Comment by jpuri** [comment]
@alfaslash : you need to parse editor state for Mention entities - there is no direct way for this.

**Comment by alfaslash** [comment]
Thank you, @jpuri 
I solved the problem so:
```
const entityMap = convertToRaw(contentState).entityMap;
const mentions = [];

Object.values(entityMap).forEach(entity => {
	if (entity.type === 'MENTION') {
		mentions.push(entity.data);
	}
});
```

**Comment by malavshah9** [comment]
Thanks @alfaslash  , this helped me.
