### ISSUE TITLE
warning in console

### ISSUE THREAD

**Issue by buxuku** [jpuri/react-draft-wysiwyg#306]
`Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them. Read more at http://fb.me/use-check-prop-types`

**Comment by sachintha88** [comment]
Hi @jpuri,
I too encountered the same issue. 
Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them. Read more at http://fb.me/use-check-prop-types
    in e (created by Editor)

I suspect this 'e' is somewhere in Editor which is react-draft-Wysiwyg. 
Digging into the issue I found this, 

[](https://facebook.github.io/react/warnings/dont-call-proptypes.html)

**Comment by tammomueller** [comment]
Same here.
Based on some debugging this seems to be related to the onChange property.

**Comment by jpuri** [comment]
The issue has been fixed by the PR: https://github.com/jpuri/react-draft-wysiwyg/pull/307

I will soon release the change.

**Comment by jpuri** [comment]
This should be fixed in latest release `react-draft-wysiwyg@1.9.7`.

**Comment by geekus** [comment]
Does not seem like it is fixed. I am still getting the warning. Just did a clean install, and verified that I have the latest, v1.9.8.

```
Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them. Read more at http://fb.me/use-check-prop-types
```

**Comment by buxuku** [comment]
YES,I have the latest, v1.9.8.This is still the case

**Comment by sachintha88** [comment]
Yes, Bug is still there.

**Comment by sachintha88** [comment]
@buxuku can you re-open the issue so that we can clearly see the improvements?

**Comment by buxuku** [comment]
@sachintha88 I do not have permission to re-open it ,so i have submit a new issue. #319

**Comment by trymbill** [comment]
Having the same issue running 1.9.8

**Comment by watsy0007** [comment]
having the same issue running 1.10.0 @jpuri
