### ISSUE TITLE
Onblur callback lacking editorState

### ISSUE THREAD

**Issue by shane805** [jpuri/react-draft-wysiwyg#308]
Here is the gist of what I'm trying to do in my React component:

```
makeEditor(fieldName = '') {
    return (
          <Editor
            id={slugify(fieldName, '_')} // makes all lowercase, replaces space with _
            onBlur={this.onEditorChange}
          />
    )
  }

onEditorChange(event, content, id) {
    const html = draftToHtml(content);
    this.setState({
      [id]: html
    });
  }

render() {
(<div>
  {this.makeEditor('Instructions')}
  {this.makeEditor('Notes')}
</div>)
}
```

Curious to see if anyone has any ideas on how I can accomplish this with the current version, if not I can make a PR for the changes that I made to support this.

The main issue that I'm running into is that I want to avoid using onChange to update state in my component because it updates too often. It really only needs to update after the user is done making changes. 

Using onBlur would solve this issue, but it doesn't seem to provide a parameter that can be used to get the current content, only the React synthetic event. Digging around in that event I could only find what appeared to be a reference to the Editor class itself, not the instance. Is there maybe some static method that I could use to get the editorState from the event?

Additionally, I would like to be able to set a `name` or `id` for my editor and have that available in the `onblur` event callback to support what I'm doing in `onEditorChange`.

**Comment by shane805** [comment]
Going to split this up into two separate issues.

**Comment by masagarino** [comment]
Did you solve this one?

**Comment by jpuri** [comment]
onBlur now has state: https://github.com/jpuri/react-draft-wysiwyg/issues/630
