### ISSUE TITLE
click "add" errors html.trim is not a function 

### ISSUE THREAD

**Issue by skiffyin** [jpuri/react-draft-wysiwyg#311]
1.click "add" errors html.trim is not a function 

2.click "editor" warning "Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them".Then close editor's window,Click "add" errors "Cannot read property 'trim' of undefined"

**Comment by jpuri** [comment]
Hello @skiffyin:

Can you plz mention where exactly you get this error.

**Comment by skiffyin** [comment]
thanks ,the error solved
