### ISSUE TITLE
Text color is lost after converting raw content / HTML back to EditorState

### ISSUE THREAD

**Issue by jasonfoy99** [jpuri/react-draft-wysiwyg#317]
I typed "this is very interesting thing" and make the text green color in Editor and then saved the following raw content using convertToRaw:  JSFiddle: https://jsfiddle.net/wc4cxnvx/
```
{
    entityMap:{},
    blocks:[{"key":"5bbf7","text":"this is very interesting thing",
"type":"unstyled",
"depth":0,
"inlineStyleRanges":[{"offset":0,"length":30,"style":"color-rgb(26,188,156)"}],
"entityRanges":[],
"data":{}}]
    }
```
Its translated Html using draftjs-to-html:
` <p><span style=\"color: rgb(26,188,156);\">this is very interesting thing</span></p>`

I tried to restore editor state using both raw content and HTML, neither shows text color in editor. For each case, only plain "this is very interesting thing" without green color was shown.

The code I was using to restore to editorstate:

1) From raw:
editorState = EditorState.createWithContent(convertFromRaw(raw));

2) From Html:

         let htmlContent = convertFromHTML(html);
         let editorState = EditorState.createWithContent(ContentState.createFromBlockArray(htmlContent.contentBlocks, htmlContent.entityMap));

Is this a bug??

**Comment by jasonfoy99** [comment]
A typo for restoring editor state using HTML
2) From Html:

```
         let htmlContent = convertFromHTML(html);
         let editorState = EditorState.createWithContent(ContentState.createFromBlockArray(htmlContent.contentBlocks, htmlContent.entityMap));

```

**Comment by jasonfoy99** [comment]
This issue is gone after upgrading to latest 1.9.8 version.

**Comment by SecMao** [comment]
I have also crashed on this problem, may I ask your solution to fix it? Now I'm using 1.10.0

**Comment by jasonfoy99** [comment]
The issue was fixed for me when using 1.9.8 version. Not sure of 1.10.0.

**Comment by Edrosos** [comment]
+1 on this issue. When changing color from the editor, the change is immediately visible. However, after restoring state from the saved html output, the color is lost. Currently using version 1.12.13

**Comment by t880216t** [comment]
it will be lost ,when i use convertFromHTML,but it ok on convertFromRaw.

**Comment by jaspersnelwebcenter** [comment]
I also encounter this issue. Does anyone have a code snippet working?

**Comment by Jasperscheper** [comment]
I also encounter this issue. Can anyone provide a working code snippet?

I am using v1.14.7

**Comment by taj567** [comment]
EditorState.createWithContent(
              ContentState.createFromBlockArray(convertFromHTML(hrmlcontent))
            )


use this one loosing all the styles like alignments & font family.
