### ISSUE TITLE
how to add math formula support in Editor

### ISSUE THREAD

**Issue by gmchaturvedi1** [jpuri/react-draft-wysiwyg#322]
Hi,

your module is awesome and fulfil my most requirements but i am new to draftjs and want help to add math formula support for my app as it is for educational domain.

thanks & Regards
gmchaturvedi

**Comment by jpuri** [comment]
Hi @gmchaturvedi1: You requirement is not very clear. How exactly do you want to add math formula. May be if you can share design it would help me understand.

**Comment by gmchaturvedi1** [comment]
We just want that our user can add math formula in editor .I just saw a
plugin in draftjs plugin editor katex and ma5hjax. Can we add those plug8ns
here .kindly suggest?

**Comment by jpuri** [comment]
@gmchaturvedi1 : it will be hard to use these plugins as such. But react-draft-wysiwyg does allows customization. You can write custom block types and custom toolbar options.

**Comment by jpuri** [comment]
Closing the issue as its not in scope for wysiwyg.

**Comment by NikhilP99** [comment]
@jpuri Can you please tell me how to use/integrate these plugins in the editor? I want to add a custom option which will take LaTeX/MathML as input and render the mathematical equation in the editor box.

**Comment by danya870** [comment]
@NikhilP99 Tell me, did you manage to add the opportunity input and edit LaTeX in this editor?

**Comment by NikhilP99** [comment]
> @NikhilP99 Tell me, did you manage to add the opportunity input and edit LaTeX in this editor?

I did manage to add an option in editor which opened a separate  input box where you can type in LaTeX or MathML. This did not render inside the editor box but a different section on the webpage.

**Comment by danya870** [comment]
@NikhilP99 Is there a code to see how you did?

**Comment by NikhilP99** [comment]
> @NikhilP99 Is there a code to see how you did?

Sorry, that was during an internship, company has the ownership of the code now.

**Comment by danya870** [comment]
@NikhilP99  Got it. Thanks for the info.

**Comment by NorweskiDrwal** [comment]
@danya870 I will be looking into adding this to the editor
poke me in a month and I'll let you know how it's going

**Comment by mohit497** [comment]
@NorweskiDrwal  were you able to add the math extension in the editor

**Comment by huangruzhe** [comment]
@NorweskiDrwal can you tell me how to add add the math extension? it it bother me a lot, thank you.

**Comment by vrajpal-jhala** [comment]
Hi everyone,

I've implemented an easy workaround to add math formula support in react-draft-wysiwyg. I've added MathJax custom toolbar button which appends LaTex syntax in the editor, which can be rendered as math symbols using MathJax library. You can check out the demo [here](http://vrajpaljhala.me/rdw-mathjax/). It doesn't add direct support of editing math equation, but it's an easy workaround if anyone is looking for something similar. Hope it helps you guys!

For the advance use case, one can add presets/macros having predefined formulas in the MathJax toolbar.

Thanks @jpuri and the contributors for working on this awesome project!
