### ISSUE TITLE
Title parameter for toolbar buttons

### ISSUE THREAD

**Issue by kimihub** [jpuri/react-draft-wysiwyg#325]
Hi !
I've added a feature to config a title on each toolbar's component.
Here is the PR if you think it can be implemented :

https://github.com/jpuri/react-draft-wysiwyg/pull/324

**Comment by jpuri** [comment]
Also, it would be useful to have title support internationalization.

**Comment by kimihub** [comment]
Do you mean translations into the file src/config/defaultToolbar.js ?

**Comment by jmarcelof** [comment]
@kimihub, I think jpuri meant getting the titles' values from src/i18n in [this style.](https://github.com/jpuri/react-draft-wysiwyg/blob/master/js/src/components/Controls/FontFamily/Component/index.js#L65)

**Comment by jpuri** [comment]
https://github.com/jpuri/react-draft-wysiwyg/pull/399 fixes the issue.
