### ISSUE TITLE
embedded links not working.

### ISSUE THREAD

**Issue by gufranmirza** [jpuri/react-draft-wysiwyg#328]
hii
Why embedded links are not working, whenever entering a embedded link of youtube or twitter nothing seems to appear. 
![screenshot from 2017-05-22 21 17 33](https://cloud.githubusercontent.com/assets/17959487/26317241/7984cb48-3f34-11e7-8bc2-68bf145b4e93.png)

**Comment by jpuri** [comment]
Plz refer this: https://github.com/jpuri/react-draft-wysiwyg/issues/155

**Comment by gufranmirza** [comment]
Thanks a lot for quick response.
One last question if i want to add the embedded link as 

"
<iframe width="560" height="315" src="https://www.youtube.com/embed/uVrunT-VxNo" frameborder="0" allowfullscreen></iframe>
"

it also does not work ,
Can you put option for HTML input, So all the embedded links like iframe or backquote can be added directly.
Thanks a lot...

**Comment by jpuri** [comment]
@gufranmirza 👍 
Check this section "Editor with embedded links" here https://jpuri.github.io/react-draft-wysiwyg/#/demo

I will think about the other option you mentioned above, and if it fits the editor use cases.

**Comment by gufranmirza** [comment]
@jpuri thanks.
