### ISSUE TITLE
Firefox error: t.options.includes is not a function

### ISSUE THREAD

**Issue by Liz303** [jpuri/react-draft-wysiwyg#329]
This error is preventing my app from running in Firefox. Is there a workaround for this?

**Comment by jpuri** [comment]
Hi @Liz303 ,

Which version of editor are you using ?

**Comment by Liz303** [comment]
npm list shows that I have react-draft-wysiwyg@1.10.0

**Comment by Liz303** [comment]
This seems to be resolved. Or it's not appearing anymore so I'm closing this.
