### ISSUE TITLE
defaultEditorState cannot set style?

### ISSUE THREAD

**Issue by josephMG** [jpuri/react-draft-wysiwyg#330]
Hi everyone:

I try to set style to defaultEditorState. I follow [sampleEditorContent](https://github.com/jpuri/react-draft-wysiwyg/blob/master/docs/src/util/sampleEditorContent.js) in the example, and I set style color to DOM as below: 
`
    const contentBlocks = convertFromHTML('<p></p>'+ 
      '<strong style=\"color: rgb(26,188,156);\">TestTest</strong>' +
      '<p></p>'
    );
`

But I got following result:
![output jpg](https://cloud.githubusercontent.com/assets/6859129/26338536/5c47f512-3fb3-11e7-8fc1-41ab60d95034.jpg)

There is no color..., Can someone give me hint?
Thanks.

**Comment by jpuri** [comment]
Hello @josephMG,

`convertFromHTML` supports not all html tags and attributes. You can try out this library `html-to-draftjs`. But again it supports only the html generated by the editor.

Also, I always recommend using raw content state for saving in DB - its much better than saving HTML.

**Comment by josephMG** [comment]
Hi @jpuri 

Thank for your reply. I will figure out other ideas to pass through or solve it.
