### ISSUE TITLE
Case issue in imports prevents running/building on linux

### ISSUE THREAD

**Issue by lavoiedn** [jpuri/react-draft-wysiwyg#338]
When trying to run the demo (`npm run start`) on Linux (tested with 4.10.13-1-ARCH) or another OS with a case-sensitive file system, the following error is thrown:

> ERROR in ./js/src/renderer/index.js
Module not found: Error: Can't resolve '../renderer/Image' in '/home/lavoiedn/git/react-draft-wysiwyg/js/src/renderer'
 @ ./js/src/renderer/index.js 11:13-41
 @ ./js/src/components/Editor/index.js
 @ ./js/src/components/index.js
 @ ./js/src/index.js
 @ ./js/playground/index.js
 @ multi ./js/playground/index

I'll submit a pull request with a potential fix shortly.

**Comment by jpuri** [comment]
I expect issues to be fixed now, plz re-open if you are still getting problem.
