### ISSUE TITLE
How to change the behavior when I press enter key

### ISSUE THREAD

**Issue by gyarasu** [jpuri/react-draft-wysiwyg#340]
Hi!

In this component, it makes new paragraph(`<p>`tag) to press enter key.
On the other hand, when I press shit + enter, it makes just new line(`<br />`tag).

I want to replace these key bind. Is it possible?
Do you have any idea?

Thanks!

**Comment by jpuri** [comment]
Hi @gyarasu ,

You can pass `handleReturn` as property to editor. Almost all the props of DraftJS are supported by the editor. https://draftjs.org/docs/api-reference-editor.html#handlereturn

**Comment by gyarasu** [comment]
Thanks, @jpuri .
I got it:)

**Comment by paulhan221** [comment]
@gyarasu do you have an example of successfully overwriting the handleReturn method by any chance?

**Comment by gyarasu** [comment]
@paulhan221 
you can pass your own function to `handleReturn`.

`handleReturn={this.myHandleReturn}`

```
class MyEditor extends Component {
  myHandleReturn(e) {
    console.log('hogehoge')
  }

  render() {
    return (
      <div>
        <div>
          <Editor
           ...
            handleReturn={this.myHandleReturn}
            ...
          />
        </div>
      </div>
    );
  }
}
```

**Comment by mikmiksai** [comment]
Hi, I try to use @gyarasu solution, but I'm getting error for **handleReturn**

![image](https://user-images.githubusercontent.com/45330227/124720340-a4bed880-df3a-11eb-8da4-52d63a7332df.png)

**Comment by ritsritika121** [comment]
even after using this handleReturn ,  it makes new paragraph(<p>tag) to press enter key. how can we stop that behviour.
@jpuri @gyarasu
