### ISSUE TITLE
React refs must have owner

### ISSUE THREAD

**Issue by Lichwa** [jpuri/react-draft-wysiwyg#341]
When running example code from [getting started](https://github.com/jpuri/react-draft-wysiwyg#getting-started):

```javascript
import { Editor } from 'react-draft-wysiwyg';
import 'react-draft-wysiwyg/dist/react-draft-wysiwyg.css';
<Editor
  editorState={editorState}
  toolbarClassName="home-toolbar"
  wrapperClassName="home-wrapper"
  editorClassName="home-editor"
  onEditorStateChange={this.onEditorStateChange}
  uploadCallback={uploadImageCallBack}
/>
```

I'm getting this error in console:
![image](https://cloud.githubusercontent.com/assets/7413177/26459619/5b51665a-4177-11e7-8280-ba12158957c1.png)

It's only happening when trying to render Editor component.

**Comment by hawkins** [comment]
This error recently started happening to me too - not sure what changed or when it happened.

**Comment by luckykun** [comment]
This error happening to me too

**Comment by jpuri** [comment]
This seems to be trouble in way package has been added and used in the application, not related to editor code. Since latest version already works well in docs - I am sure its ok.

**Comment by luckykun** [comment]
@jpuri    @Lichwa   

I have solved this problem.

we can view it using the `npm ls react` command:

Two different versions of the react package were introduced.

Just install the same version manually.

**Comment by jpuri** [comment]
Great 👍
