### ISSUE TITLE
button Cancel in modal upload image not work

### ISSUE THREAD

**Issue by tanmynguyen** [jpuri/react-draft-wysiwyg#343]
<img width="1181" alt="screen shot 2017-05-26 at 09 59 35" src="https://cloud.githubusercontent.com/assets/11315567/26478962/2e392a58-41fa-11e7-8756-797299dd2ab7.png">
Hi team!
Button cancel in modal upload image not call function so it not worked?

**Comment by 282159468** [comment]
me too 
get this bug

**Comment by sgolovine** [comment]
Found the issue. In `js/src/components/Controls/Image/index.js`. On line 83 you have `doCollpase={this.doCollpase}` when it should be `doCollpase={this.doCollapse}`

**Comment by jpuri** [comment]
Thanks @tanmynguyen , @sgolovine : here is the fix: https://github.com/jpuri/react-draft-wysiwyg/commit/a66cbad96a25962d2013d4090dbb4fb8e124735c

It will soon be released.
