### ISSUE TITLE
How to optimize the size of the webpack package

### ISSUE THREAD

**Issue by chinacoolboyzz** [jpuri/react-draft-wysiwyg#348]
How to optimize the size of the webpack package

**Comment by Xuhao** [comment]
Looks there's now to do this currently. 
npm package expose the dist version, so, we have to import the whole :(

![webpack bundle analyzer 2017-06-08 17-01-02](https://user-images.githubusercontent.com/324973/26920779-aadaf4c0-4c6c-11e7-9151-de0961aec4bd.png)

**Comment by mguijarr** [comment]
@Xuhao wow how did you make this map of the files? Very interesting !

**Comment by Xuhao** [comment]
@mguijarr https://github.com/th0r/webpack-bundle-analyzer

**Comment by Pensarfeo** [comment]
We are also facing this problem, any solutions?

**Comment by ibudisteanu** [comment]
Why the react-draft-wysiwyg.js is so large? Definitely there is a bug making the distribution so large. It can not be large than react-relay  or... react-dom!

**Comment by ibudisteanu** [comment]
My LE is right. The problem of having a such large bundle from React-Draft-WYSIWYG is that the draftjs package(module) is imported two times. Once in the React-draft-wysiwyg and another time in the Draftjs-Utils. I have deleted the node_module (package) of Draftjs-Utils and downloaded it manually and included manually in the React-Draft-WYSIWYG source code. This reduced by a lot the code, removing the duplicate import of draft.js code

![image](https://user-images.githubusercontent.com/17750489/27397795-2c0cc584-56c0-11e7-9f5b-fffdce2f1897.png)


![image](https://user-images.githubusercontent.com/17750489/27397896-8fe2c626-56c0-11e7-9d24-8b253b8334bf.png)

**Comment by jpuri** [comment]
Very nice finding, thanks @ibudisteanu ,

I also looked into it, its actually not draftjs but immutableJs that is increasing bundle size: https://github.com/jpuri/draftjs-utils/blob/master/package.json
I will fix this also.

Related issue: https://github.com/jpuri/react-draft-wysiwyg/issues/379

**Comment by jpuri** [comment]
Just published version `1.10.2`, changing Immutable to peer dependency. Wysiwyg size as low as 250kb already 😄

**Comment by jpuri** [comment]
I have also been thinking of breaking editor into modules which can be installed independently as needed. This will result in bundle size of about 100-150 kb.

**Comment by josser** [comment]
Is there any workaround or fix for the issue described by @ibudisteanu?

**Comment by Flaeron** [comment]
Found this issue after saw how large my bundle size with react-draft-wysiwyg 😕

**Comment by michalpokojski** [comment]
Any news about reducing bundle size ?

**Comment by arufian** [comment]
Another workaround is to change `react-draft-wysiwyg`'s `package.json` main from:

```json
"main": "dist/react-draft-wysiwyg.js",
```

into
```json
"main": "src/Editor/index.js",
```

It cut off the size around **200kb**

**before**
![image](https://user-images.githubusercontent.com/480889/47980874-eb663000-e10c-11e8-9c9c-ab51d2bfe3ad.png)

**after**
![image](https://user-images.githubusercontent.com/480889/47980832-be198200-e10c-11e8-8d65-f9a807d2de2a.png)

**Comment by gajrajantino** [comment]
> ```json
> src/Editor/index.js
> ```

Did anyone try this ?
