### ISSUE TITLE
ColorPicker Demo

### ISSUE THREAD

**Issue by dutch92** [jpuri/react-draft-wysiwyg#349]
https://github.com/jpuri/react-draft-wysiwyg/blob/master/docs/src/components/Demo/ColorPic/index.js#L36
BlockPicker doesn't have property _value_ rather property _color_
`<BlockPicker color={color} onChangeComplete={this.onChange} />`

**Comment by jpuri** [comment]
This PR will fix it: https://github.com/jpuri/react-draft-wysiwyg/compare/fix/small?expand=1

It will soon be merged.
