### ISSUE TITLE
Text color lost after converting from html string to editor state

### ISSUE THREAD

**Issue by SecMao** [jpuri/react-draft-wysiwyg#350]
Hi @jpuri,
May the text color lost issue reappear in the new version 1.10.0?
I cannot get the correct result while converting from html string like 
`'<p>ab<span style="color: red;">cdefg</span></p>'`, 
it's never display the color.
And the line-cross or under-line play well.
And the raw object convert to the correct result too.
I have checked some code in function `extractInlineStyle` finding that object style cannot get the 'color-' in `_tail` property.
![qq 20170605165455](https://cloud.githubusercontent.com/assets/26298277/26777712/cc23c0c0-4a10-11e7-974d-9f1585dcc92b.png)
![qq 20170605165510](https://cloud.githubusercontent.com/assets/26298277/26777747/e0fa92c6-4a10-11e7-96d4-cd8397d8b543.png)

**Comment by jpuri** [comment]
Hi @SecMao ,

I am looking into this.

**Comment by jpuri** [comment]
Hi @SecMao ,

Plz use this lib for generating editor content: https://github.com/jpuri/html-to-draftjs I have tested it works well.
