### ISSUE TITLE
how to set default value

### ISSUE THREAD

**Issue by ok713** [jpuri/react-draft-wysiwyg#357]

**Comment by ddelrio1986** [comment]
```javascript
import React, { Component } from 'react'
import { EditorState, ContentState, convertFromHTML } from 'draft-js'
import { Editor } from 'react-draft-wysiwyg'

class MyEditor extends Component {
  constructor(props) {
    super(props)
    this.state = {
      editorState: EditorState.createWithContent(
        ContentState.createFromBlockArray(
          convertFromHTML('<p>My initial content.</p>')
        )
      ),
    }
  }

  render() {
    return <Editor editorState={this.state.editorState} />
  }
}

export default MyEditor
```

**Comment by jpuri** [comment]
Thanks @ddelrio1986 , 

@ok713 I hope that helps, I am closing the issue - plz feel free to re-open if you need more information.

**Comment by revoltaxz** [comment]
in the case how do I get the last value from the database and enter in the editor?

**Comment by frankFree** [comment]
just use defaultEditorState
![image](https://user-images.githubusercontent.com/15231312/33472004-15cbce12-d6ab-11e7-8be2-8425a7db76d7.png)

**Comment by justinlazaro-ubidy** [comment]
textAlign center not working on defaultEditorState? anyone have an idea about this? thanks.

**Comment by justinlazaro-ubidy** [comment]
@ddelrio1986 cant type on wysiwyg

```
import React, { Component } from 'react'
import { EditorState, ContentState, convertFromHTML } from 'draft-js'
import { Editor } from 'react-draft-wysiwyg'

class MyEditor extends Component {
  constructor(props) {
    super(props)
    this.state = {
      editorState: EditorState.createWithContent(
        ContentState.createFromBlockArray(
          convertFromHTML('<p>My initial content.</p>')
        )
      ),
    }
  }

  render() {
    return <Editor editorState={this.state.editorState} />
  }
}

export default MyEditor
```

**Comment by jpuri** [comment]
@justinlazaro-ubidy: to make editor an un-controlled component you need to use `defaultEditorState`. Here you have made it a controlled component.

**Comment by ddelrio1986** [comment]
@jpuri is right. You need to still add a normal onChange event handler to handle typing within the component just like with any other controlled input component.

**Comment by wdse005** [comment]
import React, { Component } from 'react'
import { EditorState, ContentState, convertFromHTML } from 'draft-js'
import { Editor } from 'react-draft-wysiwyg'

class MyEditor extends Component {
  constructor(props) {
    super(props)
    this.state = {
      editorState: EditorState.createWithContent(
        ContentState.createFromBlockArray(
          convertFromHTML('<p>My initial content.</p>')
        )
      ),
    }
  }

  render() {
    return <Editor editorState={this.state.editorState} />
  }
}

export default MyEditor




it works and I can get data into editor, but when I type something then it auto undo all content and not able to write something else

**Comment by waheedsaifi** [comment]
sdfdsfdsfsdfsdfdsfsdfsd

**Comment by raihan-muhammad** [comment]
how about set default value in react hooks? please help

**Comment by rsnsmf** [comment]
> ```js
> import React, { Component } from 'react'
> import { EditorState, ContentState, convertFromHTML } from 'draft-js'
> import { Editor } from 'react-draft-wysiwyg'
> 
> class MyEditor extends Component {
>   constructor(props) {
>     super(props)
>     this.state = {
>       editorState: EditorState.createWithContent(
>         ContentState.createFromBlockArray(
>           convertFromHTML('<p>My initial content.</p>')
>         )
>       ),
>     }
>   }
> 
>   render() {
>     return <Editor editorState={this.state.editorState} />
>   }
> }
> 
> export default MyEditor
> ```

How with typescript ?
<img width="776" alt="Screen Shot 2021-05-10 at 06 20 18" src="https://user-images.githubusercontent.com/77366531/117590028-d2182180-b157-11eb-968a-ea20713e11c8.png">

**Comment by RoySegall** [comment]
For anyone that need an example with hooks:


```js
import {useEffect, useState} from "react";
import {EditorState, convertFromHTML, ContentState} from "draft-js";
import { Editor as DraftEditor } from 'react-draft-wysiwyg';
import "react-draft-wysiwyg/dist/react-draft-wysiwyg.css";
// This is a dependacny which eventually takes to the blocks and converts to full html.
import draftToHtml from 'draftjs-to-html'

export const CustomEditor = ({changeContentCallback, value}) => {
  const [editorState, setEditorStage] = useState( EditorState.createEmpty());
  useEffect(() => {
    setEditorStage(EditorState.createWithContent(
      ContentState.createFromBlockArray(
        convertFromHTML(value)
      )
    ));
  }, []);

  return  <Editor
      editorState={editorState}
      wrapperClassName="draft-wrapper"
      editorClassName="demo-editor"
      onContentStateChange={(contentState) => {
        changeContentCallback(draftToHtml(contentState));
      }}
      onEditorStateChange={(editorState) => {setEditorStage(editorState)}}
    />
}
```

**Comment by ghazale-javaheri** [comment]
is there any way to set default value without <p></p> , i want it would be just an empty string ''?

**Comment by WelltonQ** [comment]
> existe alguma maneira de definir o valor padrão sem `<p></p>`, eu quero que seja apenas uma string vazia ''?

value.replace(/(<([^>]+)>)/gi, "");

**Comment by buskerone** [comment]
Found a solution with hooks:

```TypeScript
import {
  EditorState,
  convertToRaw,
  ContentState,
  convertFromHTML
} from "draft-js"

const YourComponent = ({ props }: YourComponentProps) => {
  const [editorState, setEditorState] = useState(() => {
    const blocksFromHTML = convertFromHTML(data)
    const contentState = ContentState.createFromBlockArray(
      blocksFromHTML.contentBlocks,
      blocksFromHTML.entityMap
    )

    return EditorState.createWithContent(contentState)
  }
)
 ...
```

**Comment by buskerone** [comment]
> how about set default value in react hooks? please help

Please check if the solution above works for you.

**Comment by Naser4100** [comment]
> Found a solution with hooks:
> 
> ```ts
> import {
>   EditorState,
>   convertToRaw,
>   ContentState,
>   convertFromHTML
> } from "draft-js"
> 
> const YourComponent = ({ props }: YourComponentProps) => {
>   const [editorState, setEditorState] = useState(() => {
>     const blocksFromHTML = convertFromHTML(data)
>     const contentState = ContentState.createFromBlockArray(
>       blocksFromHTML.contentBlocks,
>       blocksFromHTML.entityMap
>     )
> 
>     return EditorState.createWithContent(contentState)
>   }
> )
>  ...
> ```

This solution works for me. Thank you.

**Comment by Saqib92** [comment]
Not able to Edit by doing: 

```
EditorState.createWithContent(
     ContentState.createFromBlockArray(
          convertFromHTML(res.data.page_content)
     )
)
```

**Comment by friskomayufid** [comment]
> Found a solution with hooks:
> 
> ```ts
> import {
>   EditorState,
>   convertToRaw,
>   ContentState,
>   convertFromHTML
> } from "draft-js"
> 
> const YourComponent = ({ props }: YourComponentProps) => {
>   const [editorState, setEditorState] = useState(() => {
>     const blocksFromHTML = convertFromHTML(data)
>     const contentState = ContentState.createFromBlockArray(
>       blocksFromHTML.contentBlocks,
>       blocksFromHTML.entityMap
>     )
> 
>     return EditorState.createWithContent(contentState)
>   }
> )
>  ...
> ```

Thankyou so much!

**Comment by hfabio** [comment]
Works, but lost all formatting :(

> Found a solution with hooks:
> 
> ```ts
> import {
>   EditorState,
>   convertToRaw,
>   ContentState,
>   convertFromHTML
> } from "draft-js"
> 
> const YourComponent = ({ props }: YourComponentProps) => {
>   const [editorState, setEditorState] = useState(() => {
>     const blocksFromHTML = convertFromHTML(data)
>     const contentState = ContentState.createFromBlockArray(
>       blocksFromHTML.contentBlocks,
>       blocksFromHTML.entityMap
>     )
> 
>     return EditorState.createWithContent(contentState)
>   }
> )
>  ...
> ```

**Comment by Deepak9811** [comment]
import React, { Component } from 'react';
import { EditorState, convertToRaw, ContentState, convertFromHTML } from 'draft-js';
import draftToHtml from 'draftjs-to-html';
import dynamic from 'next/dynamic';
import "react-draft-wysiwyg/dist/react-draft-wysiwyg.css";

const Editor = dynamic(
    () => import('react-draft-wysiwyg').then(mod => mod.Editor),
    { ssr: false }
)

let htmlToDraft = null;
if (typeof window === 'object') {
    htmlToDraft = require('html-to-draftjs').default;
}

export default class EditorConvertToHTML extends Component {
    constructor(props) {
        super(props);
        this.state = {
            editorState: EditorState.createEmpty(),
            contentState: ""
        }
    }

    componentDidMount() {

        const html = '<p>Hey this <strong>editor</strong> rocks d😀</p>';
        const contentBlock = htmlToDraft(html);
        console.log(contentBlock)
        if (contentBlock) {
            const contentState = ContentState.createFromBlockArray(contentBlock.contentBlocks);
            const editorState = EditorState.createWithContent(contentState);
            console.log(editorState)
            this.setState(
                {
                    editorState: EditorState.createWithContent(
                        ContentState.createFromBlockArray(
                            convertFromHTML(html)
                        )
                    )
                }
            )
        }



    }

    onEditorStateChange = (editorState) => {
        this.setState({
            editorState,
        });
    };

    render() {
        const { editorState } = this.state;
        console.log(this.state.editorState.getCurrentContent())
        return (
            <div>
                <Editor
                    editorState={editorState}
                    wrapperClassName="demo-wrapper"
                    editorClassName="demo-editor"
                    onEditorStateChange={this.onEditorStateChange}
                />
                <textarea
                    disabled
                    value={draftToHtml(convertToRaw(editorState.getCurrentContent()))}
                />
            </div>
        );
    }
}

**Comment by rexconsul** [comment]
@

> Works, but lost all formatting :(
> 
> > Found a solution with hooks:
> > ```ts
> > import {
> >   EditorState,
> >   convertToRaw,
> >   ContentState,
> >   convertFromHTML
> > } from "draft-js"
> > 
> > const YourComponent = ({ props }: YourComponentProps) => {
> >   const [editorState, setEditorState] = useState(() => {
> >     const blocksFromHTML = convertFromHTML(data)
> >     const contentState = ContentState.createFromBlockArray(
> >       blocksFromHTML.contentBlocks,
> >       blocksFromHTML.entityMap
> >     )
> > 
> >     return EditorState.createWithContent(contentState)
> >   }
> > )
> >  ...
> > ```

Did you find a workaround on this to also keep the formatting? Thanks in advance

**Comment by siddheeq93** [comment]
how to add inline styles to the html code 
![image](https://user-images.githubusercontent.com/87798917/179501954-789ba1c1-85c1-48fb-b995-f52254d2ece0.png)
cant we do like this?

**Comment by Anikets08** [comment]
Putting it here in case anyone who wants to have default value coming from the backend ( to mock db I've used the localStorage )

```
  const [editorContent, setEditorContent] = React.useState(
    EditorState.createEmpty()
  );

  useEffect(() => {
    let rawContent = localStorage.getItem("editorRawContent");
    let parsedRawContent = JSON.parse(rawContent);
    if (parsedRawContent) {
      setEditorContent(
        EditorState.createWithContent(convertFromRaw(parsedRawContent))
      );
    }
  }, []);

 <Editor         
       editorState={editorContent}
       onEditorStateChange={(e) => {
       setEditorContent(e);
       localStorage.setItem(
       "editorRawContent",
        JSON.stringify(convertToRaw(e.getCurrentContent()))
            );
       }}
  />
```

**Comment by pejman-hkh** [comment]
> how to add inline styles to the html code ![image](https://user-images.githubusercontent.com/87798917/179501954-789ba1c1-85c1-48fb-b995-f52254d2ece0.png) cant we do like this?


Also, I have this problem. Did you find any solutions?
