### ISSUE TITLE
Improve docs because even the most basic things are confusing

### ISSUE THREAD

**Issue by hackhat** [jpuri/react-draft-wysiwyg#358]
For example I wanted to remove some icons from the toolbar, but from this page alone https://jpuri.github.io/react-draft-wysiwyg/#/docs I can't figure out.

For example `Here is the complete toolbar property object...` contains a link to https://github.com/jpuri/react-draft-wysiwyg/blob/master/js/src/config/defaultToolbar.js , but how I will let the Editor know I want to pass those options.

After wasting some time in the source code I found https://github.com/jpuri/react-draft-wysiwyg/blob/master/js/playground/index.js which seems to need to set to `<Editor toolbar={defaultConfig}/>` from above file.

Is very hard to use this lib and would be nicer with better docs so we don't have to read the source code to figure out how things work.

Thanks

**Comment by jpuri** [comment]
Hey @hackhat ,

I am challenged atm by lack for time to maintain the project. I plan to soon increase time for it.

**Comment by hackhat** [comment]
Thanks

**Comment by jpuri** [comment]
I have added some storied for reference here: https://github.com/jpuri/react-draft-wysiwyg/tree/master/stories

I plan to soon improve docs also.

**Comment by hackhat** [comment]
Thanks

**Comment by jpuri** [comment]
Improved docs are deployed now, plz share your feedbacks.

**Comment by hackhat** [comment]
Thanks
