### ISSUE TITLE
Warning: a `span` tag (owner: `DraftEditorLeaf`) was passed a numeric string value for CSS property `fontSize` (value: `48`) 

### ISSUE THREAD

**Issue by xayaraj** [jpuri/react-draft-wysiwyg#361]
Passed in my wrapped React component Editor as React.ReactElement property to another React component. Saw the warning below when the react-draft-wysiwyg editor was rendered. 

Warning: a `span` tag (owner: `DraftEditorLeaf`) was passed a numeric string value for CSS property `fontSize` (value: `48`) which will be treated as a unitless number in a future version of React.

**Comment by xayaraj** [comment]
Somehow I can not reproduce the problem by itself. Close the issue

**Comment by gugadev** [comment]
@xayaraj @jpuri I have this problem when I try to give a fixed font to some text. Similar warning happen with images too:

> warning.js:36 Warning: a `img` tag (owner: `n`) was passed a numeric string value for CSS property `height` (value: `400`)

Always pass the unit (`px`) should fix this.

**Comment by jpuri** [comment]
I will check and fix this soon. Thanks for reporting @xayaraj , @gugadev .

**Comment by AndreyMiloserdov** [comment]
Get this error too 
> Warning: a span tag (owner: DraftEditorLeaf) 
On version "react-draft-wysiwyg": "^1.10.12"

Just do the next:
`<EditorWithToolbar
          editorState={this.state.editorState}
          onEditorStateChange={this.actions.onEditorStateChange}/>`

Type 4 lines with colored text, copy 3 lines and try to paste.
