### ISSUE TITLE
When changing the text alignment the text jumps up

### ISSUE THREAD

**Issue by hackhat** [jpuri/react-draft-wysiwyg#363]
Step 1: type something

![image](https://user-images.githubusercontent.com/11173732/27588792-40bacc9e-5b41-11e7-9021-cd973fdd9d0d.png)

Step2: Press to left align

![image](https://user-images.githubusercontent.com/11173732/27588819-596d8614-5b41-11e7-9e60-772149b7646d.png)

Result: text jump up;

Expected result: text should stay in the same place.

Notes: the same happens if you centre or right align.

Possible fix: Remove the margin from the class: `.public-DraftStyleDefault-block`, but I'm not sure what else will affect.

Also I've noticed that when you align adds the css `.rdw-left-aligned-block > div` which contains `display:inline`

Another example:

1: Press enter where pointed:
![image](https://user-images.githubusercontent.com/11173732/27589092-1883d1fc-5b42-11e7-9fa2-4c9f313a9011.png)
2:  Notice the gap
![image](https://user-images.githubusercontent.com/11173732/27589103-23b7600c-5b42-11e7-9447-8850d265810d.png)
3: Press the left align:
![image](https://user-images.githubusercontent.com/11173732/27589109-2e757fec-5b42-11e7-91f1-3e7f7d055c89.png)
4: Different gap now

**Comment by jpuri** [comment]
@hackhat : thanks for pointing this out. I will soon fix this.

**Comment by jpuri** [comment]
This PR will fix issue: https://github.com/jpuri/react-draft-wysiwyg/pull/373
It will soon be merged.
