### ISSUE TITLE
Restore editor state from markdown?

### ISSUE THREAD

**Issue by hackhat** [jpuri/react-draft-wysiwyg#364]
I've noticed there is a html to editor restore option `HTML to Editor Content conversion
Add-on library html-to-draftjs provides the option to convert HTML generated by react-draft-wysiwyg back to draftJS ContentState which can be used to initialize the Editor.` but what about markdown to editor?

Tried https://www.npmjs.com/package/draftjs-md-converter but didn't work.

**Comment by hackhat** [comment]
I just looked into your profile on github hoping for something like this and I found this: https://github.com/jpuri/draft-js-import-markdown

I will try, should work. Maybe you would like to update your docs to reflect this.

**Comment by hackhat** [comment]
Ok, so I managed to make it work with `EditorState.createWithContent(stateFromMarkdown(homework.description))` to restore the editor from a markdown input. Now the problem is that centring text like this this example results in restoring this text `<span style="text-align:center;">centre text</span>`

When I save looks like this:

![image](https://user-images.githubusercontent.com/11173732/27640070-1c701928-5c10-11e7-9161-9f153e21831d.png)

When restored:

![image](https://user-images.githubusercontent.com/11173732/27640055-0dcdb592-5c10-11e7-90c6-49de8dd2fe09.png)

**Comment by hackhat** [comment]
Also `__Underline__` is restored as `**Underline**`, seems quite broken.

**Comment by jpuri** [comment]
Hi @hackhat ,
Above repo is extracted from here: https://github.com/sstur/draft-js-import-markdown. I never published it to npm, the one I have I only used for a personal project.

Also, `https://github.com/jpuri/draftjs-to-markdown` is quite configurable. You would be able to change above markdown syntax for underline.

**Comment by ythecombinator** [comment]
Hey @hackhat, is there anything else you needed to make it work?

I have tried with three different converters:

- https://github.com/sstur/draft-js-utils/tree/master/packages/draft-js-import-markdown
- https://github.com/kadikraman/draftjs-md-converter
- https://github.com/Rosey/markdown-draft-js

And I always get the editor with markdown code:

<img width="616" alt="screen shot 2019-02-05 at 15 07 54" src="https://user-images.githubusercontent.com/2644563/52294345-d7260f00-2957-11e9-99f6-d7b74de6f801.png">

Here's what I tried

```js
// draft-js-import-markdown
const contentState1 = stateFromMarkdown(body);
const editorState1 = EditorState.createWithContent(contentState1);

// draftjs-md-converter
const rawData2 = mdToDraftjs(body);
const contentState2 = convertFromRaw(rawData2);
const editorState2 = EditorState.createWithContent(contentState2);

// markdown-draft-js
const rawData3 = markdownToDraft(body);
const contentState3 = convertFromRaw(rawData3);
const editorState3 = EditorState.createWithContent(contentState3);
```

And then:

```js
<Editor editorState={editorState} ... />;
```

Anything I'm missing? @jpuri

**Comment by jpuri** [comment]
@ythecombinator : editor will display the content passed to it correctly, can you plz check here what content is getting generated by these markdown parsing libraries and share that ?

**Comment by jpuri** [comment]
Good to know you got this fixed 😄

**Comment by Abhiramborige** [comment]
@ythecombinator can you please share the whole code,
I am not able to render markdown in the Editor component, have tried similar to how you shown here

**Comment by Abhiramborige** [comment]
> Hey @hackhat, is there anything else you needed to make it work?
> 
> I have tried with three different converters:
> 
> * https://github.com/sstur/draft-js-utils/tree/master/packages/draft-js-import-markdown
> * https://github.com/kadikraman/draftjs-md-converter
> * https://github.com/Rosey/markdown-draft-js
> 
> And I always get the editor with markdown code:
> 
> <img alt="screen shot 2019-02-05 at 15 07 54" width="616" src="https://user-images.githubusercontent.com/2644563/52294345-d7260f00-2957-11e9-99f6-d7b74de6f801.png">
> 
> Here's what I tried
> 
> ```js
> // draft-js-import-markdown
> const contentState1 = stateFromMarkdown(body);
> const editorState1 = EditorState.createWithContent(contentState1);
> 
> // draftjs-md-converter
> const rawData2 = mdToDraftjs(body);
> const contentState2 = convertFromRaw(rawData2);
> const editorState2 = EditorState.createWithContent(contentState2);
> 
> // markdown-draft-js
> const rawData3 = markdownToDraft(body);
> const contentState3 = convertFromRaw(rawData3);
> const editorState3 = EditorState.createWithContent(contentState3);
> ```
> 
> And then:
> 
> ```js
> <Editor editorState={editorState} ... />;
> ```
> 
> Anything I'm missing? @jpuri

This one please

**Comment by PThangDev** [comment]
`{username: "PThangDev", password: 12345}`
