### ISSUE TITLE
TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by audriuss** [jpuri/react-draft-wysiwyg#365]
Faced the same issue as https://github.com/jpuri/react-draft-wysiwyg/issues/282
"When running unit test, an error is thrown here:
https://github.com/jpuri/react-draft-wysiwyg/blob/d600280472627a07ca413d8f65d12a50a659325e/js/src/event-handler/modals.js#L15

document.getElementById(wrapperId); is returning null, and throws an error TypeError: Cannot read property 'addEventListener' of null"

Using jsdom + mocha. 

Seems that when https://github.com/jpuri/react-draft-wysiwyg/blob/d600280472627a07ca413d8f65d12a50a659325e/js/src/components/Editor/index.js#L115 is called: 
componentDidMount(): void {
   this.modalHandler.init(this.wrapperId);
}
->
https://github.com/jpuri/react-draft-wysiwyg/blob/d600280472627a07ca413d8f65d12a50a659325e/js/src/event-handler/modals.js#L15
const wrapper = document.getElementById(wrapperId); 

the DOM is ready, but not necessarily attached to the document. So in unit test using jsdom I am facing this and getting 'TypeError: Cannot read property 'addEventListener' of null' because the dom is not attached to the document. 
(similar issue: https://github.com/facebook/react/issues/2763).

And React encourage use ref instead of getElementById because of this. Maybe you could change getElementById to refs?

**Comment by jpuri** [comment]
Hi @audriuss : The editor has some complex event handling that required using `document.getElementById`. For me locally this setup works well for unit test coverage: https://github.com/jpuri/react-draft-wysiwyg/blob/master/config/test-setup.js.

**Comment by audriuss** [comment]
@jpuri Thank you for the fast response. I am using jsdom-global to enable DOM in Node, which basically do very similar thing that you have done in test-setup.js. Also tried to use same approach as you, but still with no success. Will try to find the way to use the editor in unit test. Thank you.

**Comment by jpuri** [comment]
Closing this issue.
