### ISSUE TITLE
Not import 'react-draft-wysiwyg.css';

### ISSUE THREAD

**Issue by vineet-agrawal96** [jpuri/react-draft-wysiwyg#366]
I want to use react-draft-wysiwyg plugin to my app. But showing following error:-
./src/App.js
Module not found: Can't resolve 'react-draft-wysiwyg.css'

Thanks

**Comment by jpuri** [comment]
@vineet-agrawal96 : try something like this: https://github.com/jpuri/react-draft-wysiwyg/blob/master/docs/src/index.js#L8

**Comment by vineet-agrawal96** [comment]
Thanks @jpuri for the reply. Issues is solved.

**Comment by vineet-agrawal96** [comment]
Would you tell me please? How to use color picker for the editor.

**Comment by vineet-agrawal96** [comment]
Hi Jpuri,

Would you tell me please how to use this plugin to my project?

**Comment by jpuri** [comment]
Hi @vineet-agrawal96 ,

Here is example for color-picker: https://github.com/jpuri/react-draft-wysiwyg/tree/master/docs/src/components/Demo/ColorPic

**Comment by vineet-agrawal96** [comment]
Hi @jpuri,

I got the error when I'm using plugin.  I'm attaching file for reference
![react app](https://user-images.githubusercontent.com/16913925/27820913-0710e42e-60be-11e7-9882-88d558682856.png)
.

**Comment by jpuri** [comment]
Hi @vineet-agrawal96 ,

This may be some build issue in your application. Can you plz check - let me know if problem continues.

**Comment by jpuri** [comment]
Closing the issue, feel free to re-open if issue continues.
