### ISSUE TITLE
Code Block support

### ISSUE THREAD

**Issue by chiedo** [jpuri/react-draft-wysiwyg#367]
Is there any way we could get code block support to do the equivalent of

```
var x,
    y,
    z;
```

Currently it looks like there is only inline code support.

**Comment by jpuri** [comment]
Yes @chiedo : code block support is not present atm. But yep something I will consider adding soon.

**Comment by chiedo** [comment]
Thanks @jpuri 

Great work!

**Comment by chiedo** [comment]
Hey @jpuri 

Is this a particularly difficult task and is there any reason this wasn't done initially?

Just curious. If it isn't particularly difficult, is there any direction you could give me in regards to how to add this feature? I can go ahead and write the code if you save me some time by pointing me in the right direction.

Thanks!

**Comment by jpuri** [comment]
@chiedo : I think setting block type and adding custom block renderer should do it. I will see if I can get time - I will add this soon.

**Comment by chiedo** [comment]
OK cool! Thank you @jpuri I appreciate your hard work.

**Comment by ChuckIrvine** [comment]
I am also looking for an editor with code block support. Specifically, I'd like to be able to create a code block and then paste code into it from the clipboard. FYI - this doesn't seem to be supported by draftjs. If you go to [https://draftjs.org/] and try to paste code into a code block you'll see that it's not working correctly. Since this editor is based on draftjs, the implementation in react-draft-wysiwyg may not work either.

**Comment by jpuri** [comment]
@ChuckIrvine : DraftJS is an extensible editor framework. We can definitely build this support on top of drafts - like other custom features built in this editor. Right now you cause inline code, it can even be styled in light gray using css. It can go to multiline with `Shift-Enter`.

I will try to soon spare some time for developing code-block.

**Comment by ChuckIrvine** [comment]
Thanks so much, Jyoti!

**Comment by haharu** [comment]
Really need the extendable block renderer, thank you @jpuri

**Comment by jpuri** [comment]
I am working on code block support right now and will very soon release it.

**Comment by jpuri** [comment]
Released `react-draft-wysiwyg@1.10.8` with support for code blocks.

**Comment by chiedo** [comment]
Thank you @jpuri :)

Any docs on how to enable it?

**Comment by chiedo** [comment]
Never mind! I found it! It's under the dropdown with the h1 tags. Any reason it isn't right next to the {} symbol?

I think that may be a better user experience.
