### ISSUE TITLE
how to change draft to html with custom rule 

### ISSUE THREAD

**Issue by liSong5713** [jpuri/react-draft-wysiwyg#375]
in my project ,when i finish  upload image then parse draft  to html  , i want to  get 
`  "<p><img src='url' /></p>"`

  , but now it is 
`"<img  src` ='url'   style....  />" `
  . please help me  !

**Comment by jpuri** [comment]
Hi,
There is no support for customized conversion atm, you can implement your own on top of this: https://github.com/jpuri/draftjs-to-html

**Comment by jpuri** [comment]
This can do the work for you: https://github.com/jpuri/draftjs-to-html/blob/master/js/block.js#L322
