### ISSUE TITLE
Getting error "Cannot read property 'focus' of undefined" in console

### ISSUE THREAD

**Issue by hkedia321** [jpuri/react-draft-wysiwyg#376]
![image](https://user-images.githubusercontent.com/17807257/27840556-8fc556d4-6117-11e7-9103-43fa5d6d547e.png)
Whenever I click on the editor, this error appears in console. Because of this error, the page becomes unscrollable and other buttons stop responding to clicks. Please help fix this bug.
My Editor component:
`  <Editor
              hashtag={{}}
              editorState={this.state.questionEditorState}
              toolbarClassName="demo-toolbar"
              wrapperClassName="demo-wrapper"
              editorClassName="demo-editor"
              onEditorStateChange={this.handleQuestionChange}
              />`

**Comment by jpuri** [comment]
Ah I am sorry,

Though it works well in the docs: https://jpuri.github.io/react-draft-wysiwyg/#/
which version of editor are you using ?

**Comment by jpuri** [comment]
Is this still an issue ?

**Comment by hkedia321** [comment]
It started working fine when I re installed the package. Thank you.

**Comment by sahiljaidka224** [comment]
This is still an issue

**Comment by sahiljaidka224** [comment]
Still an issue

**Comment by ArtemMaximum** [comment]
The same problem for me. Has anyone found a solution?

**Comment by ArtemMaximum** [comment]
I'm noticed that the error appears in console when editor called in the HOC:

`export class EditableWYSIWYG extends Component {
    // some code here...
    render() {
        const { buildEditor, onChange } = this.props;
        return <div>{buildEditor(this.state.value, this.onChange)}</div>
    }
}
`

And that how I use it:
`<EditableWYSIWYG
      value={someString}
      onDone={onDoneFunction}
      buildComponent={(value, onChange) => {
        return (
          <Editor
            onEditorStateChange={onChange}
            editorState={getInitialEditorState(value)}
          />
        )
      }}
    >
`

I use next packages:
    on  node 9.11.1 (npm 6.13.0)

    "react": "^15.5.4",
    "react-dom": "15.5.4",
    "react-draft-wysiwyg": "^1.14.0",
    "draft-js": "^0.10.5",
    "draftjs-to-html": "^0.8.4",
    "html-to-draftjs": "^1.4.0",

@jpuri Could you please give me some solution?
