### ISSUE TITLE
Adding an alt field to the image upload

### ISSUE THREAD

**Issue by chiedo** [jpuri/react-draft-wysiwyg#380]
Would there be an easy way to add an alt field to the images we upload?

On top of that, it would be cool if we could make that field required.

**Comment by jpuri** [comment]
Sure @chiedo , I will add this soon and I will keep it configurable to make  the field mandatory.

**Comment by chiedo** [comment]
Great!

Thanks

**Comment by jpuri** [comment]
PR: https://github.com/jpuri/react-draft-wysiwyg/pull/400

**Comment by chiedo** [comment]
Thank you @jpuri you are incredible! :)

**Comment by jpuri** [comment]
Thanks 😄
