### ISSUE TITLE
[Bug] ColorPickerComponent variable name 'bgcolor'

### ISSUE THREAD

**Issue by volkandkaya** [jpuri/react-draft-wysiwyg#382]
react-draft-wysiwyg/js/src/components/Controls/ColorPicker/Component/index.js

Line 48 currentStyle: 'bgcolor'

Everywhere else uses 'bgColor', spent a while trying to figure out why 'bgColor' wasn't working when creating a custom colorpicker.

**Comment by jpuri** [comment]
Hi @volkandkaya ,

This is used to set current state of color picker, color or background-color. Its like this at other places also check like 78.

**Comment by volkandkaya** [comment]
Why is it all lower case?

**Comment by jpuri** [comment]
Nothing specific just to differentiate from other variable. Background color should be working for you. Plz feel free to re-open the issue if that is not the case.
