### ISSUE TITLE
Uncaught Error: addComponentAsRefTo(...)

### ISSUE THREAD

**Issue by huadong** [jpuri/react-draft-wysiwyg#387]
1、init
Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded

2、focus
react-draft-wysiwyg.js?8b40:6 Uncaught TypeError: Cannot read property 'focus' of undefined

**Comment by jpuri** [comment]
I am not sure whats causing these errors, others are also reporting this, can you plz share the version of React, Draft and Editor that you are using. And your code snippet.

Also plz check out docs and version and code there - it works well.

**Comment by huadong** [comment]
I have created a test project [https://github.com/huadong/wysiwyg-test](url).

**Comment by jpuri** [comment]
Thanks a lot @huadong , I will take a look at it today and will get back to you.

**Comment by jpuri** [comment]
This may help you: https://github.com/huadong/wysiwyg-test/pull/1

**Comment by huadong** [comment]
Add this config to webpack.config.js in my project will fix it.
```javascript
    externals: {
        'jquery': 'jQuery',
        'react': 'React',
        'react-dom': 'ReactDOM',
        // 'redux': 'Redux',
        // 'lodash': '_',
        // 'moment': 'moment',
        // 'immutable': 'Immutable',
        // 'draft-js': 'Draft',
    },
```
Are there other solutions except using the react and react-dom as externals module for webpack?

example: [huadong/wysiwyg-test#1](https://github.com/huadong/wysiwyg-test/pull/1)

**Comment by jpuri** [comment]
Hey @huadong ,

For me it worked well after the changes I have done in the PR were added.

**Comment by huadong** [comment]
It seems that the webpack packages react twice. one in react-draft-wysiwyg and the other one in my chunk.

> nodejs v8.1.3
> npm 5.1.0
> webpack 3.1.0

![exception](https://user-images.githubusercontent.com/2927763/28054083-21e7d752-6646-11e7-9e8d-86258e589435.png)

**Comment by jpuri** [comment]
@huadong : hoe are you adding dependency in your package.json for `react-draft-wysiwyg` ?

**Comment by jpuri** [comment]
Is this still an issue ?

**Comment by newql** [comment]
Add this config to webpack.config.js in my project will fix it. 
resolve: {
    alias: {
        react: path.resolve(path.join(__dirname, '../../node_modules', 'react'))
    }
}

use to set a alias to same react source code.

**Comment by jpuri** [comment]
I am not sure why is this required.

**Comment by zheeeng** [comment]
I just met this problem. Solved it by typing 'yarn'. BTW 'npm install' is ok too.
