### ISSUE TITLE
ToolbarHidden rendering

### ISSUE THREAD

**Issue by Fi1osof** [jpuri/react-draft-wysiwyg#389]
Good day!

https://github.com/jpuri/react-draft-wysiwyg/blob/master/src/Editor/index.js#L408-L428

Have logical error. OnBlur toolbar do destroy and removes all components, listeners and processes. In this case brokes image uploading and etc. 
http://joxi.ru/EA4NeMZfw9qDnm
http://joxi.ru/5mdkp83sk5nvMr

I thin right do like display: none; and add !readOnly condition. I mean if redactor not readOnly, render toolbar with display:none if hidden. In this case all components will be initialized.

**Comment by jpuri** [comment]
Ah I see your point - `display:none` would be better. Nice catch - I will fix it.

**Comment by Fi1osof** [comment]
Not at all!

**Comment by jpuri** [comment]
PR has the fix, it will soon be released.

**Comment by Fi1osof** [comment]
Thanks!
