### ISSUE TITLE
Module not found 'draft-js'

### ISSUE THREAD

**Issue by leoc1f3r** [jpuri/react-draft-wysiwyg#390]
Followed the docs and got this.

```
Error in ./~/react-draft-wysiwyg/dist/react-draft-wysiwyg.js
Module not found: 'draft-js' in /node_modules/react-draft-wysiwyg/dist

 @ ./~/react-draft-wysiwyg/dist/react-draft-wysiwyg.js 6:497-516
```

**Comment by jpuri** [comment]
Hi @leoc1f3r , its one of the peer dependency of the project. You need to have it in you project.

**Comment by jpuri** [comment]
These are the peer dependencies: https://github.com/jpuri/react-draft-wysiwyg/blob/master/package.json#L58

**Comment by agrcrobles** [comment]
So if using npm in any existing - working web project ( with react - react-dom ) just doing:
```
npm i --save draft-js react-draft-wysiwyg
```

Should be enough since immutable is already peer of draft-js.

**Comment by jpuri** [comment]
`immutable` is peer for react-draft-wysiwyg also.

**Comment by liamtarpey** [comment]
Would be nice to have this mentioned in the installation documentation ;)
