### ISSUE TITLE
Am I missing something? (draft-js)

### ISSUE THREAD

**Issue by anthonycmain** [jpuri/react-draft-wysiwyg#392]
#340 
Im getting this warning when installing from NPM

requires a peer of draft-js@^0.10.x but none was installed

Which then results in a compile time error:

ERROR in ./~/react-draft-wysiwyg/dist/react-draft-wysiwyg.css
Module parse failed: /REDACTED/node_modules/react-draft-wysiwyg/dist/react-draft-wysiwyg.css Unexpected token (11:0)

and

ERROR in ./~/react-draft-wysiwyg/dist/react-draft-wysiwyg.js
Module not found: Error: Cannot resolve module 'draft-js'

**Comment by jpuri** [comment]
You need these peer dependencies to be installed in your project: https://github.com/jpuri/react-draft-wysiwyg/blob/master/package.json#L58

**Comment by jpuri** [comment]
I hope the issue was fixed, please re-open is you are still facing problem.
