### ISSUE TITLE
Lots of toolbar icons not working when multiple editors are rendered

### ISSUE THREAD

**Issue by mlippens** [jpuri/react-draft-wysiwyg#393]
When rendering two Editor components, the toolbar does not work anymore for multiple options on all but the first rendered component. This can also be reproduced on the demo using Chrome 59.

I have not made a complete list, but amongst others the color picker, image upload, embed, link, etc are affected by this, while others like font size, listings, etc seem to work fine.

**Comment by jpuri** [comment]
They seems to work here: https://jpuri.github.io/react-draft-wysiwyg/#/demo

Here is the code: https://github.com/jpuri/react-draft-wysiwyg/tree/master/docs/src/components/Demo

**Comment by mlippens** [comment]
Hi @jpuri,

I also tried this out on the demo page, but I have the same results on Chrome 59 and Firefox 49. The first editor on the top of the demo page works perfectly and renders the color picker, but any subsequent editor does not react anymore on clicking the color picker icon.

**Comment by jpuri** [comment]
You are right @mlippens , thanks for reporting this. I will fix it very soon.

**Comment by jpuri** [comment]
Just released `1.10.5` with the fix 👍
