### ISSUE TITLE
emoji add fontSize draftToHtml  �  why？

### ISSUE THREAD

**Issue by Pillar-Zhang** [jpuri/react-draft-wysiwyg#395]
example: <p>😫</p>

add fontSize 

output 

 <p><span style="font-size: 24px;">�</span>�</p>

**Comment by jpuri** [comment]
Hi @Pillar-Zhang : since it works here: https://jpuri.github.io/react-draft-wysiwyg/#/demo

It looks to me like encoding of your page is not supporting unicodes correctly.

**Comment by jpuri** [comment]
Any luck with the issue, this does not appears to be issue with the editor. Should I go ahead to close this ?

**Comment by Pillar-Zhang** [comment]
ok

**Comment by willbuckingham** [comment]
Sorry, if it's bad form to reply to closed issues, but I had a very similar problem and can add more information...

I noticed the same thing when we had an emoji and made it larger, once converted from draft to html, it would be a: `<span style="font-size:48px;">�</span>�</p>`

I feel like I saw somewhere when going thru different libraries and files, that when a selection is modified its length is taken into account, however i think with the addition of an emoji character the length is not properly accounted for... 

Examp: if you make the text "asdf 😍 asdf"
and then make that all 72px tall, you end up with everything 72px except the last 'f':
`<p><span style="font-size:72px;">asdf 😍 asd</span>f</p>`

Hopefully this helps, thanks for a great library.

**Comment by LevanArabuli** [comment]
Doesn't work on demo page either, look at HTML, there are weird ��.

<img width="1377" alt="screen shot 2018-06-28 at 12 09 06" src="https://user-images.githubusercontent.com/10230040/42021649-3778d51c-7acc-11e8-9cf0-864494c9009b.png">

**Comment by yousefMostafayi** [comment]
same problem.
does anyone find any solution?
