### ISSUE TITLE
new toolbar button

### ISSUE THREAD

**Issue by wiredots01** [jpuri/react-draft-wysiwyg#396]
is there a way i can add a new toolbar button?

**Comment by jpuri** [comment]
@wiredots01 : plz check this example: https://github.com/jpuri/react-draft-wysiwyg/tree/master/stories/CustomToolbar

**Comment by jpuri** [comment]
I hope that helps, closing the issue - feel free to re-open if needed.

**Comment by wiredots01** [comment]
thanks for the quick reply.
the sample is using make a bold text. How about i will add text like "⭐"

**Comment by jpuri** [comment]
Hi @wiredots01: you can use these methods of drafts https://draftjs.org/docs/api-reference-modifier.html on editor state.

**Comment by wiredots01** [comment]
`/* @flow */
import React from 'react';
import PropTypes from 'prop-types';
import styled from 'styled-components';
import { Modifier } from 'draft-js';
import icon from './staricon.svg';

const StarWrapper = styled.div`
  display: flex;
  align-items: center;
  margin-bottom: 6px;
  position: relative;
`;

const StarIconWrapper = styled.div`
  border: 1px solid #F1F1F1;
  padding: 2px;
  margin: 0px;
  height: 20px;
`;

const StarIcon = styled.img`
  width: 20px;
  margin-top: -10px;
`;


export class Mystar extends React.Component { // eslint-disable-line react/prefer-stateless-function
  static propTypes = {
    onChange: PropTypes.func,
    editorState: PropTypes.object,
    contentState: PropTypes.object,
  };

  onInsert = () => {
    const { editorState, contentState, onChange } = this.props;
    const start = editorState.getCurrentContent();
    const newState = Modifier.insertText(contentState, start, 'asdfasdfasdf');
    if (newState) {
      onChange(newState);
    }
  }

  stopPropagation = (event) => {
    event.stopPropagation();
  };

  render() {
    return (
      <StarWrapper>
        <StarIconWrapper
          onClick={this.onInsert}
          className="demo-icon-wrapper"
        >
          <StarIcon
            className="demo-icon"
            src={icon}
            alt=""
          />
        </StarIconWrapper>

      </StarWrapper>
    );
  }
}

export default Mystar;
`

it seems its not working properly... any advice?

**Comment by jpuri** [comment]
Please refer this: https://draftjs.org/docs/api-reference-modifier.html#inserttext

Looks like  your parameters to method `insertText` are wrong.
