### ISSUE TITLE
Custom toolbar

### ISSUE THREAD

**Issue by mathieumg** [jpuri/react-draft-wysiwyg#4]
Really promising project you have here! We've been looking to part ways with Summernote for a while now and this might just be it. Would you be open to having a way to configure the toolbar through props a bit like it's done in Summernote: http://summernote.org/deep-dive/#custom-toolbar-popover

Thanks!

**Comment by jpuri** [comment]
Thanks @mathieumg: yeh it very close to what you have in summer-note. I already plan to work on super-script, sub-script and remove-style.

Exactly what other configurations are you looking for ?

**Comment by mathieumg** [comment]
A way to indicate what toolbars and what buttons to display, something similar to Summernote, approach could be different I imagine:

```js
<Editor
  toolbar={[
    // [groupName, [list of button]]
    ['style', ['bold', 'italic', 'underline', 'clear']],
    ['font', ['strikethrough', 'superscript', 'subscript']],
    ['fontsize', ['fontsize']],
    ['color', ['color']],
    ['para', ['ul', 'ol', 'paragraph']],
    ['height', ['height']]
  ]}
/>
```

**Comment by jpuri** [comment]
That looks very useful, I will do it - soon after 1.0. My priority first is to release a well documented 1.0.

**Comment by mathieumg** [comment]
Awesome, no hurry of course! :grin:

**Comment by jpuri** [comment]
This change will be very useful I think and thus I plan to include it in 1.0.

My plan for it is that toolbar will be divided into groups (division will not be visible in UI):

1. Inline styles - BOLD, ITALIC, UNDERLINE, STRIKE-THROUGH, CODE
2. Block type
3. Font size
4. Font Family
5. List - ordered, un-ordered, indent, outdent
6. Color
7. Link - add link, remove link
8. Image
9. History - undo, redo

It should be possible for user to:
1. Show / Hide any of above group or any option inside the group.
2. Show the group inside dropdown - this is already present for most of groups above.
3. Change icon images.

@mathieumg , @theLordz: plz share your suggestion and feedbacks.

**Comment by jpuri** [comment]
Prop to customize toolbar will be simple JS object:

toolbar = {
  inline: {
    visible: true,
    inDropdown: true,
    bold: { visible: true, icon: 'xxx.png', },
    italic: { visible: true, icon: 'xxx.png', },
    underline: { visible: true, icon: 'xxx.png', },
    strikeThrough: { visible: true, icon: 'xxx.png', }
    monospace: { visible: true, icon: 'xxx.png', }
  },
  blockType: { visible: true, },
  fontSize: { visible: true, icon: 'xxx.png', }
  fontFamily: { visible: true, }
  list: {
    visible: true,
    inDropdown: true,
    unordered: { visible: true, icon: 'xxx.png', },
    ordered: { visible: true, icon: 'xxx.png', },
    indent: { visible: true, icon: 'xxx.png', },
    outdent: { visible: true, icon: 'xxx.png', }
  },
  ...
}

All `visible` properties will be true by default and all `inDropdown` will be false.

**Comment by mathieumg** [comment]
Very good start! :tada: What I liked about the array approach is that the developers can also reorder the groups and the buttons within each group however they see fit. For instance:

```js
toolbar = [
  ['inline', [
    'visible',
    // omitted instead of inDropdown: false,
    {type: 'bold', icon: 'xxx.png'},
    // etc.
  ],
  'fontFamily', // different order than in yours
  'blockType',
  // etc.
],
```

I also kept `toolbar` as the prop name, it's pretty descriptive already as props are always a form of "config" when we think about it. Just my two cents, tell me what you think! :)

**Comment by jpuri** [comment]
@mathieumg: I am not sure if I would prefer implicit ordering using array or rather explicit ordering using a field `position`. I have created a new issue for ordering https://github.com/jpuri/react-draft-wysiwyg/issues/19, I actually want to release a stable 1.0 soon. But if time permits I will include it in 1.0.

**Comment by jpuri** [comment]
I am thinking it might actually be better to get rid of `{visible: false}` and show only those options which user asks for.

**Comment by jpuri** [comment]
I think the approach I would prefer is:
- by default all toolbar options will be shown if user passes toolbar property only those options will be shown which are present in configuration property
- toolbar options will not be show in drop-down unless explicitly specified
- default icons will be used unless over-ridden

Thus configuration will look like:

```
toolbar = {
  inline: {
    inDropdown: true,
    options: {
      bold: { icon: 'xxx.png' },
      italic: { icon: 'xxx.png' },
      underline: { icon: 'xxx.png' },
      strikeThrough: { icon: 'xxx.png' },
      monospace: { icon: 'xxx.png' }
    }
  },
  blockType: { },
  fontSize: { icon: 'xxx.png' }
  fontFamily: { }
  list: {
    inDropdown: true,
    options: {
      unordered: { icon: 'xxx.png' },
      ordered: { icon: 'xxx.png' },
      indent: { icon: 'xxx.png' },
      outdent: { icon: 'xxx.png' }
    }
  },
  textAlign: {
    inDropdown: true,
    options: {
      left: { icon: 'xxx.png' },
      center: { icon: 'xxx.png' },
      right: { icon: 'xxx.png' },
      justify: { icon: 'xxx.png' }
    }
  },
  colorPicker: { icon: 'xxx.png' }
  link: {
    inDropdown: true,
    options: {
      addLink: { icon: 'xxx.png' },
      removeLink: { icon: 'xxx.png' },
    }
  },
  image: { 
    icon: 'xxx.png',
    fileUpload: true,
    url: true,
  },
  history: {
    inDropdown: true,
    options: {
      undo: { icon: 'xxx.png' },
      redo: { icon: 'xxx.png' },
    }
  }
}
```

I also like the idea of using `toolbar` rather than `toolbarConfig`. I also see some advantages of using array but I think simple object gives more flexibility.

Thanks a ton of your useful input - please share your feedbacks.

**Comment by jpuri** [comment]
Finally I have arrived on this configuration:
https://github.com/jpuri/react-draft-wysiwyg/blob/toolbar_customization/js/src/config/defaultToolbar.js

It looks much generic and also extensible to me.

**Comment by mathieumg** [comment]
Cool! So `options` can be used to change the order if need be. Looks good!

**Comment by jpuri** [comment]
I actually want to avoid implicit ordering based on position, later I plan to add additional fields `position, ...` like `icon` right now.

Ordering will not be supported right now.

**Comment by jpuri** [comment]
@mathieumg: basic support for customizing toolbar is now in master branch. I will work to add more options to it later.

Thanks a lot for  your nice suggestions 👍

**Comment by mathieumg** [comment]
Awesome, thanks! Did you want me to close this issue?

**Comment by jpuri** [comment]
I think it can be closed. I added any other issue for allowing ordering of options in toolbar.

Please share more suggestions for improving the editor.

**Comment by AndreyMiloserdov** [comment]
At this moment i can't create own toolbar with custom blocks, for example it will cause error:

```
{
  options: ['textIndent', 'list'],

  textIndent: {
    inDropdown: false,
    className: undefined,
    component: undefined,
    dropdownClassName: undefined,
    options: ['indent', 'outdent'],
    indent: { className: undefined },
    outdent: { className: undefined },
  },

  list: {
    inDropdown: false,
    className: undefined,
    component: undefined,
    dropdownClassName: undefined,
    options: ['unordered', 'ordered'],
    unordered: { className: undefined },
    ordered: { className: undefined },
  },
}
```
because 'textIndent' not supported. How can we make fully custom toolbar like this:
![screen](https://user-images.githubusercontent.com/26063680/31710689-71a62dec-b3fe-11e7-8287-0b2a737f8503.png)
?

**Comment by jpuri** [comment]
@AndreyMiloserdov : can you plz share exactly what error / result do you get for above code snippet.

**Comment by AndreyMiloserdov** [comment]
![screen shot 2017-10-25 at 17 39 42](https://user-images.githubusercontent.com/26063680/32004938-b12fecf2-b9ab-11e7-8ce7-e184cfabbcde.png)

**Comment by AndreyMiloserdov** [comment]
Another problem in src/controls/TextAlign/Component/index.js
`<div className={classNames('rdw-text-align-wrapper', className)} aria-label="rdw-textalign-control">`
no any `currentState ` in the className property: can't set  custom icon for selected style, only default image as icon, no any css possibility for this

Same for the list buttons.

**Comment by ericnkatz** [comment]
@jpuri how does one disable something like fontFamily in the current configuration model?

**Comment by jpuri** [comment]
Yes @ericnkatz , toolbar property can be used to remove toolbar options.

**Comment by kshitijbhatnagar97** [comment]
@jpuri what if we want to show "B(bold)" "I(italics)" and the rest of the inline functionalities in a dropdown 
instead of having the whole inline as dropdown

**Comment by kbhatnagar97** [comment]
First of all, really love the library! 
@jpuri what if we want to show "B(bold)" "I(italics)" and the rest of the inline functionalities in a dropdown instead of having the whole inline as dropdown

**Comment by kbhatnagar97** [comment]
@jpuri also, why can't we customise the drop-down icon for toolbar icons it seems to take the first option of the subarray (i.e) If I wan to but inline in a drop-down shouldn't I have an option to add an icon for the drop-down instead of using "Bold" as the icon just because it is the first function

**Comment by vishwanath-yadav** [comment]
@jpuri Can we insert link to custom toolbar values like we do in summernote?

**Comment by ivanudovin-roonyx** [comment]
Hey! Nice tool! Is there any prop to change inDropdown direction? My editor is at the bottom of the page and when I press the Link option it goes out of the window. 
So the default dropdown goes down, can I change it to the up? @jpuri

**Comment by passionatedeveloper223** [comment]
Hi, I want to add a new button in toolbar and when press that button it shows my customized window.
In that window, users can select multiple images and press okay button, it will add images to edit box.
*** We could get those image urls (those images already uploaded on cloud) ***

Can I add my customized button in toolbar?

**Comment by harrisyn** [comment]
@passionatedeveloper223 
https://jpuri.github.io/react-draft-wysiwyg/#/docs?_k=jjqinp

**Comment by sac10nikam** [comment]
> Prop to customize toolbar will be simple JS object. The object below list all the options but user needs to provide only those where he wants to override the defaults. Default value of `visible` will be true and `inDropdown` will be false. By default for icons current images (as shown in docs) will be used:
> 
> ```
> toolbarConfig = {
>   inline: {
>     visible: true,
>     inDropdown: false,
>     bold: { visible: true, icon: 'xxx.png', },
>     italic: { visible: true, icon: 'xxx.png', },
>     underline: { visible: true, icon: 'xxx.png', },
>     strikeThrough: { visible: true, icon: 'xxx.png', }
>     monospace: { visible: true, icon: 'xxx.png', }
>   },
>   blockType: { visible: true, },
>   fontSize: { visible: true, icon: 'xxx.png', }
>   fontFamily: { visible: true, }
>   list: {
>     visible: true,
>     inDropdown: true,
>     unordered: { visible: true, icon: 'xxx.png', },
>     ordered: { visible: true, icon: 'xxx.png', },
>     indent: { visible: true, icon: 'xxx.png', },
>     outdent: { visible: true, icon: 'xxx.png', }
>   },
>   textAlign: {
>     visible: true,
>     inDropdown: true,
>     left: { visible: true, icon: 'xxx.png', },
>     center: { visible: true, icon: 'xxx.png', },
>     right: { visible: true, icon: 'xxx.png', },
>     justify: { visible: true, icon: 'xxx.png', }
>   },
>   colorPicker: { visible: true, icon: 'xxx.png', }
>   link: {
>     visible: true,
>     inDropdown: true,
>     addLink: { visible: true, icon: 'xxx.png', },
>     removeLink: { visible: true, icon: 'xxx.png', },
>   },
>   image: { 
>     visible: true, 
>     icon: 'xxx.png',
>     fileUpload: true,
>     url: true,
>   },
>   history: {
>     visible: true,
>     inDropdown: true,
>     undo: { visible: true, icon: 'xxx.png', },
>     redo: { visible: true, icon: 'xxx.png', },
>   }
> }
> ```

@jpuri I have one requirement where I just want to keep an image icon and that too in the center of the textarea.
And keep the 4 icons which are used for image resizing.. after selecting the image..

Any suggestions?

I tried to pass below given properties but no luck..
I am following - https://formio.github.io/formio.js/app/examples/wysiwyg.html

components: [
      {
        type: 'textarea',
        label: 'Upload an Image',
        wysiwyg: {
          theme: 'snow',
          // modules: {
          //   toolbar: false,
          // },
          modules: {
            toolbar: [
              ['image'],
            ],
          },
          placeholder: 'Upload an image...',
        },
        validate: {
          required: true
        },
        key: 'content',
        input: true,
        inputType: 'text'
      },
];

Any example of https://formio.github.io/formio.js/app/examples/custombuilder.html for the WYSIWYG  editor
