### ISSUE TITLE
I suggest it can customize the configuration font, color, size, etc., as well as multi-language support

### ISSUE THREAD

**Issue by MinJieLiu** [jpuri/react-draft-wysiwyg#40]
I suggest it can customize the configuration font, color, size, etc., as well as multi-language support

**Comment by jpuri** [comment]
Hi,

I do not understand it correctly. Are you mentioning some new requirements or listing existing features ?

**Comment by MinJieLiu** [comment]
a some new requirements

**Comment by jpuri** [comment]
All this is already there @MinJieLiu, I think I can close this issue - plz suggest.

**Comment by jpuri** [comment]
Closing it for now.
