### ISSUE TITLE
using ref in new Editor

### ISSUE THREAD

**Issue by nadunindunil** [jpuri/react-draft-wysiwyg#406]
Hi,
I am extending the editor to add new custom blocks and i faced a problem when I use

```
this.refs.editor.focus();
```

where actually ref is editor,
```
<div >
     <Editor 
          ref = "editor"
          editorState={editorState}
          onEditorStateChange={this.onEditorStateChange}
        />
</div>
```

and the error is -
**TypeError: this.refs.editor.focus is not a function**

could you please help me with this problem?

**Comment by jpuri** [comment]
Hello @nadunindunil ,

Editor atm does not supports ref property. But from your request I think I should add it soon.

**Comment by nadunindunil** [comment]
Hi @jpuri ,
thank you very much for your quick reply! 
will you add the ref for editor soon ?

there is another problem which I came across when I was using the **react-draft-wysiwyg** ,

- before I add the plugin I could create an exact same type block by pressing the "enter" button.(as an example I created a todo block and when the cursor is inside the todo block I could simply create another one by pressing the enter key)
- but after **react-draft-wysiwyg** added I couldn't find a way to achieve that. (**and I need this feature for my project**)

question is - doesn't **react-draft-wysiwyg** support that feature? if so anyway to fix that?
or am I doing something wrong when using the plugin? 

Thank you.

**Comment by jpuri** [comment]
@nadunindunil : yes I will add ref soon.

On Enter key press react-draft-wysiwyg inserts a paragraph. You can change it by passing property `handleReturn`. It will be passed to the editor as here: https://github.com/jpuri/react-draft-wysiwyg/blob/master/src/Editor/index.js#L450

**Comment by nadunindunil** [comment]
@jpuri , 
Thank you very much that's all I wanted to know.

**Comment by PrimeLens** [comment]
Hi @nadunindunil    I was able to set focus by using an internal method.   see code here
https://github.com/jpuri/react-draft-wysiwyg/issues/476
hope it helps

**Comment by Santosh-13** [comment]
> Hello @nadunindunil ,
> 
> Editor atm does not supports ref property. But from your request I think I should add it soon.

@jpuri , Do we support passing the ref now? 
My requirement is to show suggestions / autocomplete while the user is typing. Is there a way i can use react-draft-wysiwyg to achieve this without using refs?
