### ISSUE TITLE
why not list draftjs and immutable as prod dependencies?

### ISSUE THREAD

**Issue by PrimeLens** [jpuri/react-draft-wysiwyg#409]
Just wondering why,  as I noticed they are not in
```
"dependencies": {
}

```
but are listed in 

```
"devDependencies": {
} 
```

**Comment by jpuri** [comment]
@PrimeLens : these are peer dependencies. I was facing some issues in making `drafts` dependency - it requires an instance of react to be initialized thus I found it was breaking client application when I made it dependency.
I made `immutablejs` peer dependency to avoid in bundle size increase coz of it. I expect most applications using the editor to already have this dependency.

**Comment by PrimeLens** [comment]
:)
