### ISSUE TITLE
Adding link and image throws error 

### ISSUE THREAD

**Issue by CassieCHM** [jpuri/react-draft-wysiwyg#414]
The error occured when I add  link or image target , it throws : r.getCurrentContent(...).createEntity is not a function in react-draft-wysiwyg.js ,I followed your first demo's steps but it didn't work. Is there anyone can sovle it?

**Comment by jpuri** [comment]
@CassieCHM : which version of draft-js are you using. Previous versions where giving this issue.

**Comment by jpuri** [comment]
@CassieCHM : does the problem still exists ?

**Comment by CassieCHM** [comment]
@jpuri I found the same mistake in other issues, so I've chosen the right version of draft.js and  solved this problem. Thanks for yuor attention~

**Comment by jpuri** [comment]
Sounds good 😄
