### ISSUE TITLE
react-draft-wysiwyg set defaultValue

### ISSUE THREAD

**Issue by Q-Angelo** [jpuri/react-draft-wysiwyg#417]
我想设置默认值 如果我采用convertFromHTML  但是有个问题 图片 会变成一个链接显示 这个我该如何解决 ，我的代码：
[](url)
```javascript
         editorState: EditorState.createWithContent(
                ContentState.createFromBlockArray(
                    convertFromHTML(this.props.discription)
                )
            )
```

**Comment by Q-Angelo** [comment]
````HTML
<p>这是一段文章内容。。。</p>
<img src="http://127.0.0.1:3000/uploads/1501943082769b0e097.jpg" alt="undefined" style="float:none;height: auto;width: auto"/>

例如上面这个图片会变成像下面一个链接而不是一个图片来展示  For example, the img image above,Will become a link . How do I solve this problem
http://127.0.0.1:3000/uploads/1501943082769b0e097.jpg 

````

**Comment by jpuri** [comment]
@Q-Angelo : how are you converting html to editor content. Is there a specific lib that you are using ?

**Comment by Q-Angelo** [comment]
my code:

```
import { Editor } from 'react-draft-wysiwyg';
import { EditorState, ContentState, convertFromHTML } from 'draft-js'

class Wysiwyg extends Component {
    constructor(props) {
        super(props)
        this.state = {
            editorContent: undefined,
            contentState: rawContentState,
            editorState: EditorState.createWithContent(
                ContentState.createFromBlockArray(
                    convertFromHTML(this.props.discription)
                )
            )
        }
    }

 return (
  <Editor
              editorState={editorState}
             ....
          />
 )
}
````

**Comment by jpuri** [comment]
Support of `convertFromHTML` for generating drafts editor state is limited. You can try this lib: https://github.com/jpuri/html-to-draftjs. Also, not that it will be able to handle only HTML generated by wysiwyg editor itself.

**Comment by Q-Angelo** [comment]
@jpuri  thank you

**Comment by lemonxxy** [comment]
@jpuri  I update the image but how can I show the imgae in text area?
![image](https://user-images.githubusercontent.com/28467452/34138658-a1420db8-e4ab-11e7-90a7-1f2382a5ffb0.png)
  ` xhr.addEventListener('load', () => {
        const response = JSON.parse(xhr.responseText);
        resolve( { data: { link: response.data[0].origin}});
      });`

**Comment by caominhtung1992** [comment]
you need add 👍 :
 previewImage: true,
sampale:
<Editor
     toolbar={{
            image: { 
                   previewImage: true,
              }
           }}                                       
      />
