### ISSUE TITLE
best way to have toolbar render on bottom?

### ISSUE THREAD

**Issue by PrimeLens** [jpuri/react-draft-wysiwyg#422]
Client wants toolbar underneath.
Is there a current way to do this?
My backup plan is to use flexbox `flex-direction: column;` and `order 1 2`

**Comment by jpuri** [comment]
@PrimeLens : there is no direct way to do it. But you can use toolbarClass property to achieve it.

**Comment by PrimeLens** [comment]
ok thanks!
I ended up going for this instead. Code pasted at the bottom for others

```
.wrapperClass { display: flex; flex-direction: column; }
.editorClass { order: 1; }
.toolbarClass { order: 2; }
```

**Comment by hubgit** [comment]
`.wrapperClass { display: flex; flex-direction: column-reverse }` would have the same effect.

Is there a way to get the toolbar menus to open upwards instead of downwards, though?

**Comment by PrimeLens** [comment]
yes.  just override css.   get rid of top by resetting it to its default which is auto.  then set a bottom

    {
        top: auto;
        bottom: 10px;
    }
