### ISSUE TITLE
Text alignment for multiline

### ISSUE THREAD

**Issue by masquel** [jpuri/react-draft-wysiwyg#425]
If text is one line, center and right text alignment works great.
But if text is more then one line, text alignment is always left.

![image](https://user-images.githubusercontent.com/6623392/29404175-108a3eea-8343-11e7-93a1-f617cf92330f.png)

It happends because of  `.public-DraftStyleDefault-ltr` which is inside of `.rdw-center-aligned-block` or `.rdw-right-aligned-block` and has `text-align:left`.

Result text is aligned well, but this styles doesn't appear in editor.

**Comment by dadepl** [comment]
Hi, any news on that?

**Comment by aureobeck** [comment]
@dadepl it's necessary to set `width: 100%` in the `public-DraftStyleDefault-block`class as well

**Comment by justinlazaro-ubidy** [comment]
Having an issue here, hope it will fix. 

also got an temporary fix.

```
.rdw-center-aligned-block > .public-DraftStyleDefault-block > span { 
  text-align: center;
  width: 100%; 
  display: block;
}

.rdw-right-aligned-block > .public-DraftStyleDefault-block > span {
  text-align: right;
  width: 100%;
  display: block;
}
```

**Comment by jpuri** [comment]
Release `1.12.9` has the fix.

**Comment by codeaid** [comment]
Still having this issue with 1.12.9. Creating an empty editor, typing several lines of text into it and none of the alignment buttons do anything. 

I see that there's a `.rdw-justify-aligned-block` div wrapping around the paragraph containing another one with `.public-DraftStyleDefault-ltr` defining `text-align: left;`. If I remove the attribute everything works as expected. 

If I save and reload the text after e.g. right aligning it then it reverts to left aligned.

**Comment by jpuri** [comment]
@codeaid: Can you plz check that you are using new css file also.

**Comment by codeaid** [comment]
@jpuri - I'm pretty sure it was. I saw the `display: block-inline` in the styles when I inspected some elements. I'm afraid I've switched to using `react-quill` since I posted the message.

**Comment by vyachekg** [comment]
Still reproduced. 1.12.11

**Comment by Louie-Healthsite** [comment]
@jpuri - Still exists in 1.12.13
Resorted to CSS workaround from @justinlazaro-ubidy 
Something that you're working on?

**Comment by Spyron1234** [comment]
Facing issue for paragraph. It is not getting center aligned. Any necessary cautions for CSS or any other workaround? Please help.
