### ISSUE TITLE
draftToHTML with Code Blocks

### ISSUE THREAD

**Issue by chiedo** [jpuri/react-draft-wysiwyg#427]
Thanks so much for adding code block support!

Sadly, the code block html is not showing up when using 

```draftToHtml(convertToRaw(editorContent.getCurrentContent()))```

All I get is a blank where the code blocks were in the editor.

Any ideas?

**Comment by chiedo** [comment]
Isolated the issue down to the draftToHTML function. I'll post in that repo!

**Comment by chiedo** [comment]
https://github.com/jpuri/draftjs-to-html/issues/20

**Comment by jpuri** [comment]
I will very soon (by tomorrow) release new versions of draftjs-to-html, drafts-to-markdown and html-to-drafts.

**Comment by chiedo** [comment]
Thank you!

**Comment by jpuri** [comment]
New versions of supporting libs:
```
draftjs-to-html@0.7.5
draftjs-to-markdown@0.4.4
html-to-draftjs@0.1.0-beta15
```
