### ISSUE TITLE
Can't copy and paste into code block

### ISSUE THREAD

**Issue by chiedo** [jpuri/react-draft-wysiwyg#429]
Currently you can't copy and paste into a code block which would make it really difficult to embed large blocks of code.

**Comment by jpuri** [comment]
@chiedo : Where are you copying content ? It works for me if I copy from VS code, but I see some scenario can break.

**Comment by chiedo** [comment]
From my package.json file. Let me try something else.

**Comment by chiedo** [comment]
It looks like anything with a newline causes it to break.

**Comment by jpuri** [comment]
Yes blocks do not support new line but it works for `\n` character. Thus `Shift+Enter` will create new link in code-block and not Enter.
I need to write paste handler it seems for this.

**Comment by chiedo** [comment]
That sounds right to me! :)

Is that something that you think will be challenging or is that an easy task?

**Comment by jpuri** [comment]
Yes I will check this paste issue soon.

**Comment by chiedo** [comment]
Thanks! 😃

**Comment by FindChenLinJie** [comment]
i can't paste the images into a code block , how can i solve it ?

**Comment by jpuri** [comment]
Sorry I know this issue exists for multiple lines of code, I will prioritize it to fix it soon.

**Comment by jpuri** [comment]
Release `react-draft-wysiwyg@1.10.9` fixes the issue.

**Comment by chiedo** [comment]
THANK YOU!!!!!!!!!
