### ISSUE TITLE
Image upload issue

### ISSUE THREAD

**Issue by dmitrydyachenko** [jpuri/react-draft-wysiwyg#43]
Hi! When I click on "Image upload" button, then choose "URL" tab, then try to put a focus on "Enter url" input, it disappears and is replaced by "Drop the file or click to upload". Please, help. Thank you.

**Comment by jpuri** [comment]
@dmitrydyachenko: thanks a lot for reporting it. I could replicate it - its apparently a small issue. I will fix it really quick - hopefully by tomorrow.

**Comment by jpuri** [comment]
Hi @dmitrydyachenko,

It got delayed as I was on vacation last week. But I just fixed the issue and make release `0.2.5`.

I am closing this issue. Thanks

**Comment by ZeroCho** [comment]
Please update online demo too!

**Comment by jpuri** [comment]
Yep sure, I am doing some more work on documentation today and will update by EOD.

**Comment by dmitrydyachenko** [comment]
Thank you, @jpuri. It was really helpful.

**Comment by dmitrydyachenko** [comment]
But why have you removed drag and drop functionality for image, @jpuri ?

**Comment by jpuri** [comment]
Oh that is not intentional, did I broke it - let me check @dmitrydyachenko

**Comment by jpuri** [comment]
Oh this functionality is optional and configurable, its shown only if users provide function to upload photos. In demo page you will see some demo have it and others not.

**Comment by dmitrydyachenko** [comment]
Sorry, I can not see any examples with such functionality on the demo page: https://jpuri.github.io/react-draft-wysiwyg/#/demo?_k=bj923j, @jpuri. Thanks.

**Comment by jpuri** [comment]
Oh I found, I had done some code changes today and missed to update docs for  that, doing that now.

Thanks a lot for pointing out.

**Comment by jpuri** [comment]
Docs are fixed now.
