### ISSUE TITLE
Address block support

### ISSUE THREAD

**Issue by haharu** [jpuri/react-draft-wysiwyg#430]
Hello,

I need a new type of block with element `<address>` as wrapper

such like `<span> I am currently on the way to <address> 1600 Amphitheatre Parkway, Mountain View, CA, 94043 </address>.<span>`

In order to specify which part of text should be treated as address (for mobile app)

I will send pr to both `draftjs-to-html` and this repo, probably should also modify `draftjs-utils` according to this issue.
https://github.com/facebook/draft-js/issues/1211

but I cannot decide the style in editor, so I do need your help in `draftjs-utils` @jpuri 

Thanks!

**Comment by jpuri** [comment]
Hey @haharu ,

I was looking at this: https://www.w3.org/TR/html4/struct/global.html#h-7.5.6
Looks like address is not a block level tag. I do not  think we should include it in blocks.

I would rather prefer to create a custom toolbar option for a tag like this.

**Comment by haharu** [comment]
hi @jpuri,

thanks for your advice, I will close this issue and pr.
