### ISSUE TITLE
Disabling the toolbar buttons is not disabling the corresponding keyboard shortcut

### ISSUE THREAD

**Issue by nivibhat** [jpuri/react-draft-wysiwyg#437]
If I disable the underline option from the toolbar, I would like the corresponding keyboard shortcut also needs to be disabled, but currently it is not disabling the keyboard shortcut.

**Comment by jpuri** [comment]
Thanks for bringing up this issue, keyboard shortcuts are actually not added by the editor but they are  a feature of underlying draft editor. I will check and add a fix ti disable those also.

**Comment by nivibhat** [comment]
Hello,

Thank you.
Could you please update me the timeline of fixing this issue? ..   

Thanks
Nivi

**Comment by jpuri** [comment]
Hi @nivibhat ,
More and more users are complaining about it. I plan to fix this in about a week or so.

**Comment by jpuri** [comment]
`react-draft-wysiwyg@1.10.11` fixes the issue.

**Comment by Billie-Angelov** [comment]
currently on version: 1.14.7. Disabling the "BOLD" for example, still allows me to Ctrl + B
