### ISSUE TITLE
is there any callback when image deleted?

### ISSUE THREAD

**Issue by xkguq007** [jpuri/react-draft-wysiwyg#438]
first of all, sorry for bad english.

I tested and I can upload image through uploadCallback. (Very easy to follow through docs)
However, I don't know how I can check which images are deleted.

I'm using serverless framework, so I upload to s3 right away,
The flow what I've thinking is
image upload to tmp(each per user) s3 directory -> return the url -> post finished -> move actually used images to other directory(NOT tmp) -> truncated tmp dir.

Is there the other way to solve this ?
Because my flow looks unreasonable.
If deletedCallback is exists, handling uploaded file will be easy much more.
Just send delete method when deltedCallback is invoked.

**Comment by jpuri** [comment]
Hey @xkguq007 : there is not such callback, a work around could be that one editor state change you can check if Image entity with a particular src url no longer exists.

**Comment by xkguq007** [comment]
@jpuri 
Thanks for reply! it will be help
