### ISSUE TITLE
Formatting tools cannot format font size

### ISSUE THREAD

**Issue by MinJieLiu** [jpuri/react-draft-wysiwyg#44]
Formatting tools cannot format font size

**Comment by jpuri** [comment]
It works for me in docs:

![screen shot 2016-11-10 at 7 27 32 pm](https://cloud.githubusercontent.com/assets/2182307/20179392/f1269a7e-a77b-11e6-9928-d51371b8b462.png)

**Comment by jpuri** [comment]
@MinJieLiu: do you still face the issue or should I close it ?

**Comment by MinJieLiu** [comment]
It can not format the color and font size
![https://minjieliu.github.io/assets/issures-image/2.png](https://minjieliu.github.io/assets/issures-image/2.png)

**Comment by jpuri** [comment]
@MinJieLiu: I see it formatted in image above, can you help me understand the issue.

**Comment by jpuri** [comment]
Closing as there is no reply, if required issue can be re-opened.
