### ISSUE TITLE
Unable to open editor in edit mode in IE 11

### ISSUE THREAD

**Issue by alksharm** [jpuri/react-draft-wysiwyg#448]
Hi,
In IE11, I am unable to open the editor to edit the content that was created and saved earlier. 

Getting below error -
Object doesn't support property or method 'find'

Line to which error is pointing to -
this.blocksTypes.find(function(e){return e.style===a})

I have already tried using polyfills Array.prototype.find and array-find, but still the same issue.

Please suggest.

Thanks,
Alka

**Comment by jpuri** [comment]
Hey @alksharm , can you plz share the whole stack trace, that will help me identify the issue.

**Comment by alksharm** [comment]
Thanks @jpuri for your response. It turned out that the browser was unable to understand the polyfill for a different reason. Closing the issue.

**Comment by jpuri** [comment]
Thanks @alksharm , it will help anyone else using editor in IE 👍

**Comment by rjaydadula** [comment]
Hi @jpuri ,
I found same issue in IE11.

![ie11](https://user-images.githubusercontent.com/5228074/41237235-9fdea172-6dc5-11e8-9c14-8346c5c7b0d7.JPG)


It seems that it does not support method find.
I found some .js that is located in \__test\__ folder and in dist-> react-draft-wysiwyg.js


Hope it will be updated soon.

Thanks!
