### ISSUE TITLE
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>

### ISSUE THREAD

**Issue by orditeck** [jpuri/react-draft-wysiwyg#45]
I'm getting this warning. 

`Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>. See DraftEditorContents > p > ... > DraftEditorBlock > div.`

The problem is this `<p>` here https://github.com/jpuri/react-draft-wysiwyg/blob/master/js/src/components/Editor/index.js#L151

![](http://i.imgur.com/9dqniHn.png)

Pull request coming soon.

**Comment by jpuri** [comment]
Hi @orditeck,

Thanks a lot for the PR. One of the reason that I kept it <p> and not <div> is that generated HTML and MarkDown use syntax for <p>, thus I preferred <p> in editor also to preserve exact styling of margins.

But <div> may just work well and also fix the warning. I will merge the PR and check. Thanks a ton 😄 

~ Jyoti

**Comment by jpuri** [comment]
Hello @orditeck,

Thinks got little delayed as I was on vacation. But I have to undo the these changes. The reason being that the generated mark-down and HTML use <p> tag thus to keep things consistent I would prefer to use <p> tag in editor also.

Plz share your thoughts about it.

**Comment by orditeck** [comment]
@jpuri I'm sorry but I don't understand why you want to keep the `<p>` as the main tag. There is multiple `<div>` in that `<p>`, and it's not allowed, which is why this warning is showing. 

Is there any reason for this?

**Comment by jpuri** [comment]
@orditeck: WYSIWYG editor typically use <p> for normal text paragraphs and I would not prefer to deviate from it also you can see in output <p> tags are used for paragraphs.

Should I go ahead to close this issue ?

**Comment by jpuri** [comment]
Closing the issue as there is no response.

**Comment by vhmth** [comment]
Hey @jpuri I think it's fine to use `<p>` within the content block, but I think we should definitely not nest divs inside the `<p>` tag. This is semantically incorrect and will result in error logs for any application that uses this wonderful library.

What issues would result from us transitioning from `<p>` to `<div>` or ensuring that `<p>` does not nest `<div>`s within it? How large would that transition be? If you look at a lib like [Medium.js](https://github.com/jakiestfu/Medium.js), they use `<div>`s and I'm starting to see that it may because of this issue.

**Comment by jpuri** [comment]
@orditeck , @vhmth : I am convinced about fixing this 😄 . I will redo changes of your pr, thanks a lot @orditeck , @vhmth.

**Comment by vhmth** [comment]
https://www.opentest.co/share/bc85f010c0a511e693d2c326b54ba9c0

**Comment by bonniecool** [comment]
@jpuri  I reinstall this package and we still get the warning "Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>"

Red warning color is not good for an application. Please tell us if you pursue to continue using <p> instead of <div>

Thanks!

**Comment by vhmth** [comment]
@bonniecool look at her comment right above mine.

**Comment by bonniecool** [comment]
@vhmth thanks! :-D

**Comment by jpuri** [comment]
Hey @vhmth, @bonniecool: 

These changes are already in develop and I will release this week. I am trying to slow down little on development cycles and releasing only well tested code.

**Comment by jpuri** [comment]
The fix has been release in in version `react-draft-wysiwyg@1.4.0`.

**Comment by vhmth** [comment]
Sweet! Seems like it works. :-)

**Comment by bnwan** [comment]
Just started to use this yesterday and getting the "Calling PropTypes validators..." warning. Any help is apprecaited. Thanks

**Comment by jpuri** [comment]
@bnwan: which version of editor are you using ?

**Comment by nguyenchanhnghia** [comment]
hi @jpuri i'm using react-draft-wysiwyg@1.10.7 and this bug still continue :(, what solution for this bug. Thanks. sr my poor English :)
