### ISSUE TITLE
Indent and outdent not working

### ISSUE THREAD

**Issue by gopinath-sixt** [jpuri/react-draft-wysiwyg#451]
Hi 

In Editor, Indent and Outdent is not working.

Actual Result:
-- Clicking on Indent icon and outdent icon has no effect on content of the Editor.

Expected Result:
--Indent icon and outdent icon should work as expected.

**Comment by jpuri** [comment]
Hey @gopinath-sixt , indent and outdent options atm work only on lists. I will soon make fix to disable these if current selection is not a list.

**Comment by gopinath-sixt** [comment]
Hi @jpuri , I tried to use the indent and outdent in the list also, it is not working :(

**Comment by jpuri** [comment]
Latest version of editor `react-draft-wysiwyg@1.10.10` has the fix to enable indent / outdent only when it can work. Check [here](https://jpuri.github.io/react-draft-wysiwyg).

I will work in task of text indenting also later.

**Comment by gopinath-sixt** [comment]
@jpuri Thank a lot for your best support. it's working for list 👍

**Comment by jpuri** [comment]
Thanks for reporting the issue @gopinath-sixt , I have created another task to take case of test indentation: https://github.com/jpuri/react-draft-wysiwyg/issues/474

**Comment by belief-cyf** [comment]
@jpuri why indent and outdent options atm work only on lists? went we edit in Microsoft word or Notepad, we can use indent and outdent in anywhere. Why don't we do that?

**Comment by jpuri** [comment]
@belief-cyf #474 is about that only

**Comment by Subha** [comment]
I still see the indent/outdent is disabled in demo page - https://jpuri.github.io/react-draft-wysiwyg/#/

How should i add support in my application?
Thank you

**Comment by jpuri** [comment]
Indent and outdent atm works for lists only.

If you want a feature that would work in all blocks you need to add a custom option for that.

**Comment by Subha** [comment]
Yes it works on the list. But i would not expect our client to know this detail. I can try it out as the custom option. Thank you

**Comment by Developer-53** [comment]
How can I indent/outdent the blocks/ paragraphs selected using Shift/ Shift + Tab? As Indent and Outdent toolbar options works only for lists.

**Comment by santhosh-umapathi-appymango** [comment]
Hi @jpuri , I tried the demo page, it does not work even on the lists.

**Comment by HassanAsghar123** [comment]
> 

How??
