### ISSUE TITLE
Usage of plugins

### ISSUE THREAD

**Issue by Andrew1024** [jpuri/react-draft-wysiwyg#456]
Why not to use plugins from [here](https://github.com/draft-js-plugins/draft-js-plugins) ? 

The problem is the current react-draft-wysiwyg is not compatible with them due to different entity naming. For example plugins use `image` and react-draft-wysiwyg use `IMAGE`.

Besides, plugins can not override the `blockRendererFn` .

Is the problem solvable or plugins are not a priority now?

**Comment by jpuri** [comment]
Plugins are based on vary different architecture, using plugin requires using the underlying editor `draft-js-plugins-editor`. I like the way editor is designed and do not want to change it to adapt to plugin architecture as used in `draft-js-plugins`.
In addition plugins do not support stuff like conversion to html, markdown, etc.

**Comment by Andrew1024** [comment]
> plugins do not support stuff like conversion to html, markdown, etc.
Where can I read about this?
