### ISSUE TITLE
How to show text value in editor?

### ISSUE THREAD

**Issue by revoltaxz** [jpuri/react-draft-wysiwyg#462]
I have a question on how can I show the current value of the Editor that is saved in my database. With which Editor property can I manipulate this data? 

Thank you !

**Comment by jpuri** [comment]
Hello @revoltaxz ,

In case your value is plain text you can use this method:
```
    import { EditorState, ContentState, convertFromHTML } from 'draft-js';
    ...
    const html = 'testing this will work';
    const contentBlock = convertFromHTML(html);
    if (contentBlock) {
      const contentState = ContentState.createFromBlockArray(contentBlock);
      const editorState = EditorState.createWithContent(contentState);
      this.state = {
        editorState,
      };
    }
```
Or is your content HTML ?

**Comment by revoltaxz** [comment]
The value is in markdown but I would like to show it in rich text format

**Comment by revoltaxz** [comment]
Problem Solved !!

```
import * as React from "react";

import { ContentBlock, ContentState, convertFromHTML, convertFromRaw, convertToRaw, EditorState } from "draft-js";
import { stateToHTML } from "draft-js-export-html";
import { stateFromMarkdown } from "draft-js-import-markdown";
import draftToMarkdown from "draftjs-to-markdown";
import { Editor } from "react-draft-wysiwyg";

interface IProps {
  editorState: any;
  notes: string;
}

interface IState {
  editorState: any;
  notes: string;
}

export default class MarkdownTextArea extends React.Component<IProps, IState> {
  constructor(props: IProps) {
    super(props);
    const markdown = props.notes;
    const contentState = stateFromMarkdown(markdown);
    if (contentState) {
      const editorState = EditorState.createWithContent(contentState);
    }
    this.state = {
      editorState,
      notes: props.notes,
    };
  }
```

**Comment by NiyazMulla** [comment]
>  if (contentBlock) {
>       const contentState = ContentState.createFromBlockArray(contentBlock);
>       const editorState = EditorState.createWithContent(contentState);
>       this.state = {
>         editorState,
>       }


what to do if  values are fetching from the local file

**Comment by minoo-cyber** [comment]
ssssssss

**Comment by minoo-cyber** [comment]
sssssss

**Comment by Enkhtsenguun** [comment]
qa

**Comment by CarolMPS** [comment]
> Hello @revoltaxz ,
> 
> In case your value is plain text you can use this method:
> 
> ```
>     import { EditorState, ContentState, convertFromHTML } from 'draft-js';
>     ...
>     const html = 'testing this will work';
>     const contentBlock = convertFromHTML(html);
>     if (contentBlock) {
>       const contentState = ContentState.createFromBlockArray(contentBlock);
>       const editorState = EditorState.createWithContent(contentState);
>       this.state = {
>         editorState,
>       };
>     }
> ```
> 
> Or is your content HTML ?

I tried this, but says "Cannot read properties of undefined (reading 'createFromBlockArray')"
