### ISSUE TITLE
Can't set multiple blanks In the article

### ISSUE THREAD

**Issue by Blackgan3** [jpuri/react-draft-wysiwyg#466]
When I wanna set multiple blanks in the article, just like this:
```js
'blank           blank'
```
but the editor will Automatic reduction to one blank, so I need your help !!!

**Comment by jpuri** [comment]
Hey @Blackgan3 , when are the blank spaces getting removed - after you re-hydrate editor with saved data ?

**Comment by Blackgan3** [comment]
when I  enter a string , I enter a lot of blank, and then I enter the string, and the middle number of Spaces becomes one

**Comment by jpuri** [comment]
Hey @Blackgan3, I will check this.

**Comment by PreYunk** [comment]
I am having the same issue, I think that its not fixed yet.
When I try to convert the editorData from raw to html the content
> word                   word
reduces to
> word word

**Comment by PreYunk** [comment]
I am having the same issue,
I don't know how to send tab spaces to editor therefore I tried giving it multiple spaces,
but those spaces were reduced to a single space on converting my editorState from raw to html
