### ISSUE TITLE
Drawing plugin?

### ISSUE THREAD

**Issue by CharlesIrvineKC** [jpuri/react-draft-wysiwyg#468]
I'm looking for an editor that would support inline drawing (e.g. shapes, lines, text, etc). Users would need to be able to open and edit drawings on subsequent edits. Is there anything like this already available? Thanks

**Comment by jpuri** [comment]
Hey @ChuckIrvine , no editor does not support this. Nor I plan to develop it any soon.

**Comment by ChuckIrvine** [comment]
Ok, Thanks Jyoti. I searched around quite a bit before I posted and couldn’t find any browser editor that supports this. I would be a very handy feature but I can imagine that it wouldn’t be easy to achieve.
