### ISSUE TITLE
Fix image alignment options proposal

### ISSUE THREAD

**Issue by copycut** [jpuri/react-draft-wysiwyg#472]
It's impossible to inspect this option popup.

Maybe, in place of using Js to render or not the alignment option popup, render it always and switch classNames. So il can be inspected in a browser. 

https://github.com/jpuri/react-draft-wysiwyg/blob/3bcd7eec5f2c008c6a555d9b5453e41b2de5e3d5/src/renderer/Image/index.js#L112

**Comment by jpuri** [comment]
Hey @copycut : you can do it by building repo locally and setting `expanded` to true [here](https://github.com/jpuri/react-draft-wysiwyg/blob/master/src/controls/ColorPicker/Component/index.js#L130)

**Comment by copycut** [comment]
Thanks! Perfect.
