### ISSUE TITLE
how to set defaultFontSize?

### ISSUE THREAD

**Issue by belief-cyf** [jpuri/react-draft-wysiwyg#475]
i want to defaultFontSize is 14px.
I try to do this in toolbar config:
![image](https://user-images.githubusercontent.com/19991842/30951673-cef0d90a-a456-11e7-9f1a-79d7d4e54ca2.png)
but is invalid,And I can't find Api in doc.
can you help me~ thk~

**Comment by jpuri** [comment]
Hey @belief-cyf :  you can use classes to style editor to do that any of `wrapperClassName, editorClassName` or `wrapperStyle, editorStyle`.

Font control in toolbar will pick the current font from the editor itself.

**Comment by belief-cyf** [comment]
thank， is working。 i will close this issue
