### ISSUE TITLE
automatically focus cursor in text area after draft wysiwyg editor renders

### ISSUE THREAD

**Issue by PrimeLens** [jpuri/react-draft-wysiwyg#476]
I was able to automatically focus cursor in text area after draft wysiwyg editor mounts, Just leaving this here for others.

```
class MyEditor extends React.Component {
  constructor(){
    super();
    this.setDomEditorRef = ref => this.domEditor = ref;
  }
  componentDidMount(){
    // as per method in https://github.com/jpuri/react-draft-wysiwyg/blob/master/src/Editor/index.js
    this.domEditor.focusEditor();
  }
  render() {
    return (
        <Editor
          ref={this.setDomEditorRef}
          {/*  other attributes etc etc */}
         />
    )
  }
```

**Comment by jpuri** [comment]
Thanks @PrimeLens 😄

**Comment by RamonBalthazar** [comment]
Please, add this to the documentation :)

**Comment by jpuri** [comment]
Done :)
Thanks @PrimeLens , @RamonBalthazar

**Comment by jpuri** [comment]
To avoid react warning I have changes property name to `editorRef`. Using `ref` still may work but is avoidable.

**Comment by t880216t** [comment]
@jpuri  Thanks for you do . And it not work when i have to write like this:
`
export default class EditableRichCell extends React.Component {
edit = () => {
    this.setState({ editable: true }, () => {
      // this.domEditor.focusEditor();
    });
  };
  render() {
    const { value, editable, editorState } = this.state;
    const setEditorReference = (ref) => {
      this.editorReferece = ref;
      ref.focusEditor();
    }
    return (
      <div className={styles.editable_cell}>
        {editable ? (
          <div
            style={{
              border: '1px solid #d9d9d9',
              borderRadius: 5,
              marginTop: 10,
              backgroundColor: '#fff',
            }}
          >
            <Editor
              editorRef={setEditorReference}
              editorState={editorState}
.
.
.
`
please help me

**Comment by NikkiMeganMoore** [comment]
@t880216t it looks like you have a typo on line 65 
`this.editorReferece = ref;` should be `this.editorReference = ref;`

Also, it looks like the function is just called "focus", not "focusEditor"

You can access it by doing this
`const setEditorReference = (ref) => {
      this.editorReferece = ref;
      ref.focusEditor();
}`

**Comment by Utsav170** [comment]
when i called this.domEditor.focusEditor(), i have encountered an error  TypeError: Cannot read property 'focusEditor' of undefined.

**Comment by atikmahbub** [comment]
can you give me an example using react hook ?  i am getting focuseditor error when trying to implement with react hook(using useRef()}

**Comment by MaxWong03** [comment]
@atikmahbub Same here. Has anyone successfully implemented focus using react hook?

**Comment by katkat100** [comment]
I was able to get focus with react hooks like this
`
const EditorRef = useRef();

useEffect(() => EditorRef?.current.focus(), [EditorRef]);

<Editor
    editorRef={(ref) => (EditorRef.current = ref)}
    ...
/>
`

**Comment by Spark3000** [comment]
Does anyone know what type to use for the ref if using Typescript?

![Screenshot 2021-09-05 at 20 30 41](https://user-images.githubusercontent.com/4939629/132148376-cbcb2fdb-54b3-4805-b6a8-54296f194506.png)

**Comment by mourrrya** [comment]
`const editorRef = useRef(null);`

`editorRef.current.focusEditor();`

` <Editor  ref={editorRef} />`

**Comment by jorgeperezn** [comment]
If it helps, you might use moveCursorToEnd()
https://draftjs.org/docs/api-reference-editor-state/#movefocustoend

If using classes

 componentDidMount() {
    this.setState({
      editorState:  EditorState.moveFocusToEnd(this.state.editorState), // EditorState imported from draft-js
    });
  }
In my case using functional components, I just wanted to add focus when creating the note from an existing text

EditorState.moveFocusToEnd(
          EditorState.createWithContent(convertFromRaw(JSON.parse(text))),
);

**Comment by jorgeperezn** [comment]
If it helps, you might use moveCursorToEnd()
https://draftjs.org/docs/api-reference-editor-state/#movefocustoend

If using classes

```
 componentDidMount() {
    this.setState({
      editorState:  EditorState.moveFocusToEnd(this.state.editorState), // EditorState imported from draft-js
    });
  }

```
In my case using functional components, I just wanted to add focus when creating the note from an existing text

```
EditorState.moveFocusToEnd(
          EditorState.createWithContent(convertFromRaw(JSON.parse(text))),
);
```

**Comment by aayush-dhakal** [comment]
1. For functional component:
a. If you want the cursor to focus at the end of the pre-existing text then:
const [state, setState] = useState({
        editorState: notes.length 
                    ? 
            EditorState.moveFocusToEnd(EditorState.createWithContent(ContentState.createFromBlockArray(htmlToDraft(notes)))) 
                    : EditorState.moveFocusToEnd(EditorState.createEmpty()),    
});

// or you can call moveFocusToEnd in useEffect as well according to your requirement
const [state, setState] = useState({
        editorState: notes.length ? EditorState.createWithContent(ContentState.createFromBlockArray(htmlToDraft(notes))) : EditorState.createEmpty(),
    });

useEffect(() => {
        setState({
                editorState: notes.length 
                    ? EditorState.moveFocusToEnd(EditorState.createWithContent(ContentState.createFromBlockArray(htmlToDraft(notes)))) 
                    : EditorState.moveFocusToEnd(EditorState.createEmpty()),
            });
    }, []);

b. If you want the cursor to focus at the very beginning of the pre-existing text then:
const editorRef = useRef(null);

useEffect(()=>{
     editorRef.current.focusEditor();
})

  <Editor
                    ref={editorRef}
                    editorState={state.editorState}
                    .....
/>


2. For the class-based component
a. If you want the cursor to focus at the end of the pre-existing text then:
componentDidMount() {
        this.setState({
            editorState:  EditorState.moveFocusToEnd(this.state.editorState),
        });
    }

b. If you want the cursor to focus at the very beginning of the pre-existing text then:
this.editorRef = React.createRef();

componentDidMount() {
        editorRef.current.focusEditor();
    }

  <Editor
                    ref={editorRef}
                    editorState={state.editorState}
                    .....
/>
