### ISSUE TITLE
Usage Example

### ISSUE THREAD

**Issue by kaushikbarodiya** [jpuri/react-draft-wysiwyg#48]
Hey @jpuri , 
I liked the text editor of demo page and I wanted to use similar kind of rich-text -editor in my project. But there is no information on How to use component after installation.
Great if you can provide some guide for the same.

Thanks

**Comment by jpuri** [comment]
Hi @kaushikbarodiya,

I am still working on the documentation of the editor. But you can check this for now: 
https://github.com/jpuri/react-draft-wysiwyg/blob/master/docs/src/components/Demo/index.js

Let me know if you need more information.

**Comment by jpuri** [comment]
Hi Plz check updated docs: https://jpuri.github.io/react-draft-wysiwyg/

Let me know if you need more help. I am closing this issue for now.

**Comment by foodaka** [comment]
@jpuri thanks for the editor, where is sample code for the editor on that page? Thanks 
https://jpuri.github.io/react-draft-wysiwyg/

**Comment by jpuri** [comment]
@foodaka : this is editor on home page: https://github.com/jpuri/react-draft-wysiwyg/blob/master/docs/src/components/Home/index.js#L24

And these are ore demo: https://github.com/jpuri/react-draft-wysiwyg/blob/master/docs/src/components/Demo/index.js
