### ISSUE TITLE
Feature request: Embed

### ISSUE THREAD

**Issue by ZeroCho** [jpuri/react-draft-wysiwyg#51]
Hello, thanks for awesome repository! This is the most perfect react editor I've ever seen!

I'd really like to embed some cool stuffs in my post, such as YouTube or Codepen.
I will be happy if you implement this feature, and this repo will be perfect.

**Comment by jpuri** [comment]
Thanks a lot. This is so motivating 😄 
Sure I am working on implementing more features and also documentation. Next thing I am planning to implement is mentions.

I am add codepen or youtube but I am not sure how it fits with wysiwyg nature of editor and conversion to HTML and markdown.

Let me  think over it.

**Comment by jpuri** [comment]
I am realizing this feature could be very useful for some users. I will soon prioritize it.

**Comment by ZeroCho** [comment]
I implemented it except for one thing. I'll make pr and please help me.

Everything is working but i cant comvert it to HTML. All i got is what i entered in Entity.create

**Comment by ZeroCho** [comment]
@jpuri please clone this. [link](https://github.com/zerocho/react-draft-wysiwyg)

**Comment by jpuri** [comment]
Look good @ZeroCho, I will take some inputs from this and I am planning to tomorrow work on embed link functionality.

**Comment by MichaelSavin** [comment]
Looks like very early prototype:

- [ ] No YouTube embed
- [ ] instead of iframes better to use [Open Graph widgets](https://github.com/draft-js-plugins/draft-js-plugins/issues/452)
