### ISSUE TITLE
CopyPaste error

### ISSUE THREAD

**Issue by AndreyMiloserdov** [jpuri/react-draft-wysiwyg#514]
There are new align values in CSS3 for the text: start. end (http://htmlbook.ru/css/text-align)
So, if create simple 4 lines without alignment (Chrome), copy ones and paste at the end of document. Pasted text will have some empty lines - place there cursor, we'll get the next error:

`react-draft-wysiwyg.js:6 Uncaught TypeError: Cannot read property 'icon' of undefined`

This is an error in the file `src/controls/TextAlign/Component/index.js`

` <img
          src={(textAlignment && config[textAlignment].icon) || getFirstIcon(config)}
          alt=""
        />`

becouse in our config for alignment no buttons "start"/"end".

Simple fix:
` src={(textAlignment && config[textAlignment] && config[textAlignment].icon) || getFirstIcon(config)}`

Correct fix: make replacement for default 'start' and 'end' values on 'left' and 'right' ones.

**Comment by jutaro** [comment]
The same problem here when pasting text into the editor. Please apply the fix.

**Comment by djthayer** [comment]
@jpuri We are also running into this issue.  As this appears to be an easy fix, could you please address this issue or at least propose a time frame for addressing this issue?  Thanks!
