### ISSUE TITLE
Editor shows previous content when creating a new modal

### ISSUE THREAD

**Issue by GaneshPandey** [jpuri/react-draft-wysiwyg#523]
I have used react-draft-wysiwyg editor for my react project. And its embeded inside Bootstrap modal.
As shown in screenshot below, when i successfully save the form the modal closes gracefully.
![modal_1](https://user-images.githubusercontent.com/3205994/32602329-d372968e-c56d-11e7-91ca-47885b850fd4.png)

Now, when i create a new project(opening a modal) as shown in screenshot. The same content on wysiwyg editor is shown. Is it issue with wysiwyg editor or Bootstrap Modal i am confused.
![modal_2](https://user-images.githubusercontent.com/3205994/32602327-d33e09b4-c56d-11e7-9a78-73236a7cd266.png)

**Comment by jpuri** [comment]
Hey @GaneshPandey , this is definitely not issue with the wysiwyg. It seems to be trouble to application state management in the app. Are you using flux or redux ?

**Comment by GaneshPandey** [comment]
@jpuri I am using redux...
repeats even if i forcefully make the state empty on constructor.

**Comment by jpuri** [comment]
@GaneshPandey , can you plz share how you are using Editor component.

**Comment by GaneshPandey** [comment]
@jpuri https://gist.github.com/GaneshPandey/0b45a9a9290443b6f661f3bc2029e033

**Comment by ruslan-tiger** [comment]
Have the same issue. How was this fixed ? Thanks
