### ISSUE TITLE
Aligning image does not work in react 16.0.0

### ISSUE THREAD

**Issue by khj809** [jpuri/react-draft-wysiwyg#530]
I tested image alignment feature in both react 15.6.2 and 16.0.0.

In 16.0.0, the tooltip [L][C][R] is shown when mouse is hovered on image, but it immediately disappears when mouse leaves the image area, which makes me not able to set alignment.

In 15.6.2 it works with no problem. (maybe same in lower versions, not tested though)

**Comment by export-mike** [comment]
@khj809 ahhh react 15 it works interesting...

**Comment by MattWillcox** [comment]
has anyone come up with a workaround for this?

**Comment by export-mike** [comment]
Hi @MattWillcox I found it to randomly work at times. on second click on the L, C, R buttons it works for me. 

I'm currently looking to move to draft-js-plugins

**Comment by MattWillcox** [comment]
This issue has been resolved in an updated version of react @jpuri 

https://github.com/facebook/react/pull/11164

**Comment by jpuri** [comment]
@MattWillcox thx
I can close the issue, editor does not bundles react with it, update will be required in code using the editor.

**Comment by hafeez1042** [comment]
Using `"react": "16.8.5"`, having the issue

**Comment by sachinit254** [comment]
Alignment is not working in first attempt also getting "Cannot read properties of null (reading 'focus')" on alignment button click
