### ISSUE TITLE
className prop not working

### ISSUE THREAD

**Issue by Joacim12** [jpuri/react-draft-wysiwyg#532]
Hello, i tried the following code: 

`<Editor
                        editorState={editorState}
                        wrapperClassName="demo-wrapper"
                        editorClassName="demo-editor"
                        onEditorStateChange={this.onEditorStateChange.bind(this)}
                        toolbar={{
                            embedded:{
                                className:"responsive",
                                defaultSize:{
                                    height:500,
                                    width:500,
                                }
                            },
                            image: {
                                className: "img-fluid",
                                uploadCallback: this.uploadImageCallBack,
                                alt: {present: true, mandatory: true}
                            }
                        }}
/>`

But when adding a image, or an embedded link, they don't have a className, am i using it wrong?

**Comment by kevinrutherford** [comment]
This fooled me too. The `className` prop applies to the "embedded" button in the editor toolbar; it doesn't affect the generated HTML document.

**Comment by jpuri** [comment]
Yep `className` is only for styling the editor component and not content. To achieve above you can add this to wrapping class like

```
.editor-wrapper > img {
...
}
```
