### ISSUE TITLE
No render toolbar on readOnly

### ISSUE THREAD

**Issue by Fi1osof** [jpuri/react-draft-wysiwyg#533]
Good day!

Is toolbar olways render even editor read only?

**Comment by gnyani** [comment]
even I see toolbar being rendered even though readOnly prop is being passed to the editor.
@jpuri  can you help with this.

**Comment by jpuri** [comment]
Property `toolbarHidden` can be used to hide toolbar.

**Comment by Fi1osof** [comment]
@jpuri it`s not useful set both readOnly and toolbarHidden, but OK. Thanks.
