### ISSUE TITLE
Set both color and bgcolor for color picker

### ISSUE THREAD

**Issue by samotoo** [jpuri/react-draft-wysiwyg#535]
Hi,

Thanks a lot for this great editor component.

I'm working on a customized color picker component. I found that the onChange prop passed can either set color or bgcolor, but I cannot find a way to set both color and bgcolor at the same time. Is there a method to implement this behavior? 

Thanks.

**Comment by jpuri** [comment]
Hey @samotoo : there is no such method. Only once property can be changes at a time.
