### ISSUE TITLE
contentState: {} doesn't work

### ISSUE THREAD

**Issue by lchunxiu** [jpuri/react-draft-wysiwyg#540]
contentState: {}  doesn't work
 object from event onContentStateChange couldn't be set to the editor

**Comment by jpuri** [comment]
Hey @lchunxiu check examples here:
https://github.com/jpuri/react-draft-wysiwyg/tree/master/stories

Initialization can be done like this also: https://github.com/jpuri/react-draft-wysiwyg/blob/master/stories/ConvertToHTML/index.js#L10

If you do not provide an initial state, editor initializes by itself.

**Comment by jpuri** [comment]
Hey @lchunxiu, are you still facing the issue ?

**Comment by lchunxiu** [comment]
I didnt reply you in time ,i am sorry!
 i try the example you offer,could not work either
couldnt find solution,so,i give up use this ;
