### ISSUE TITLE
Element ref was specified as a string (editorContainer) but no owner was set

### ISSUE THREAD

**Issue by CruelMoney** [jpuri/react-draft-wysiwyg#547]
I get this error when trying to use the editor through a package I'm creating:

`Element ref was specified as a string (editorContainer) but no owner was set. You may have multiple copies of React loaded.`

When running npm ls this is the output:
```
cra-test@0.1.0 /Projects/Nima
├─┬ cude-cms@0.2.3 -> /Projects/CUDE-CMS
│ └── react@16.2.0
└── react@16.2.0
```
Where cude-cms is the package using react-draft-wysiwyg, and cra-test is the project trying to use the editor through cude-cms. It seems that the problem is that cude-cms depends on react as well, but moving the dependency to peerdependencies makes cude-cms unable to build. 

Any takes on how to solve this?

**Comment by jpuri** [comment]
Hey @CruelMoney , this happens is you are somehow importing 2 instances of react in the application. You need to ensure react is not bundled with ur application. Check this: https://github.com/jpuri/react-draft-wysiwyg/blob/master/package.json#L63

**Comment by CruelMoney** [comment]
Alright. 
My problem is that if I don't bundle it, my library package wont build as it can't resolve react. Any resources on how to solve this? Should I somehow exclude react from the webpack config?

**Comment by jpuri** [comment]
Check this: https://github.com/jpuri/react-draft-wysiwyg/blob/master/config/webpack.config.js#L18

Its how I am building the lib.
It was still failing with Node 8, though works in Node 7.

**Comment by CruelMoney** [comment]
YES, excluding react and react-dom from the build did the trick. 
Thanks for the help, gonna close this.
