### ISSUE TITLE
Styling <pre><code> tags

### ISSUE THREAD

**Issue by mirik999** [jpuri/react-draft-wysiwyg#550]
Why Code block sets only pre tags? there is doesnt exists code tag AND each row without span tags written, what i mean ? 
it will be 

pre
code 
span - here code - span
code
pre

but editor sets only

pre
here code - br
here code - br
here code - br
pre

So i cant use highlightjs or prismjs or another package for styling Code blocks.

**Comment by jpuri** [comment]
Hey @mirik999, this is standard format for code blocks used by various other editors. Of you require some changes in the styling you can use Custom Rendering for code blocks.
Plz feel free to re-open the issue for further discussion.
