### ISSUE TITLE
previewImage

### ISSUE THREAD

**Issue by wonghoman** [jpuri/react-draft-wysiwyg#555]
hi, I want to preview image when I upload image, 
![image](https://user-images.githubusercontent.com/6296547/34195587-539d76ee-e599-11e7-96c7-921e1f21a19f.png)

 code like :
`toolbar={{
          image: {
            uploadCallback: uploadImageCallBack,
            previewImage: true,
          },
        }}`
my version is '1.12.1', but it's not work,  why? 
Whether it's not merged with #491 ? plz reply me, thank you!

**Comment by paradoxxxzero** [comment]
@jpuri is there anything I can do to see this PR hits a release?

**Comment by jpuri** [comment]
@paradoxxxzero : sorry for the delay. I will release this soon.

**Comment by jpuri** [comment]
Change has been released with `react-draft-wysiwyg@1.12.4`.
Thanks again.

**Comment by aleafo** [comment]
I have updated to 1.12.4, but it still does not work. @jpuri

**Comment by wonghoman** [comment]
@jpuri I see the effect, thank you very much!

**Comment by egemon** [comment]
@jpuri could u please add this info into docs section please? As well as to examples.

**Comment by jpuri** [comment]
Sure I am doing that @egemon.

**Comment by jpuri** [comment]
Done 👍
