### ISSUE TITLE
How to integrate with redux-form v7 ?

### ISSUE THREAD

**Issue by diegolaciar** [jpuri/react-draft-wysiwyg#556]
Anyone know how to use this component with redux form v7 ?

**Comment by diegolaciar** [comment]
Thanks

**Comment by trongbang86** [comment]
This one works for me.
```
import React from 'react';
import renderField from './renderField';
import { Editor } from 'react-draft-wysiwyg';
import htmlToDraft from 'html-to-draftjs';
import draftToHtml from 'draftjs-to-html';
import { EditorState, convertToRaw, ContentState } from 'draft-js';

class TheField extends React.Component {
    constructor(props) {
        super(props);
        const editorState = this.initEditorState();
        this.state = {
            editorState
        };
        this.changeValue(editorState);
    }

    /**
     * Initialising the value for <Editor />
     */
    initEditorState() {
        const html = '<p>Your content</p>';
        const contentBlock = htmlToDraft(html);
        const contentState = ContentState.createFromBlockArray(contentBlock.contentBlocks);
        return EditorState.createWithContent(contentState);
    }

    /**
     * This is used by <Editor /> to handle change
     */
	handleChange(editorState) {
		this.setState({editorState});
        this.changeValue(editorState);
	}

    /**
     * This updates the redux-form wrapper
     */
    changeValue(editorState) {
        const value = draftToHtml(convertToRaw(editorState.getCurrentContent()));
        this.props.input.onChange(value);
    }

    render() {
        const { editorState } = this.state;
        return (
        <div id='react-wysiwyg' className='col-xs-12'>
            <Editor   
                editorState={editorState}
                wrapperClassName="wrapper-class"
                editorClassName="editor-class"
                toolbarClassName="toolbar-class"
                onEditorStateChange={(editorState) => this.handleChange(editorState)}/>
        </div>
        );

    }
}

export default renderField(TheField);
```

Then you can use this in your redux-form

**Comment by mapkuff** [comment]
thanks @trongbang86, your code helped me so much.
btw, I added more stuff to make it support redux form initial value.

    import React from 'react';
    import { compose, withHandlers, withState, withPropsOnChange } from 'recompose';
    import { FormGroup, FormFeedback } from 'reactstrap';
    import { EditorState, ContentState, convertToRaw } from 'draft-js';
    import htmlToDraft from 'html-to-draftjs';
    import draftToHtml from 'draftjs-to-html';
    import { Editor } from 'react-draft-wysiwyg';
    
    import './WysiwygEditor.scss';
    
    const WysiwygEditor =
      (
        {
          input: { value, onChange },
          meta: { touched, error },
          editorState,
          onEditorStateChange
        }
      ) => (
        <FormGroup className="WysiwygEditor">
          {
            editorState &&
            <Editor
              editorState={editorState}
              onEditorStateChange={onEditorStateChange}
              editorClassName="editor"
              toolbarClassName="toolbar"
            />
          }
          {touched && error && <FormFeedback>{error}</FormFeedback>}
        </FormGroup>
      );
    
    export default compose(
      withState("editorState", "setEditorState", EditorState.createEmpty()),
      withPropsOnChange(
        ['input'],
        ({ input: { value }, meta: { dirty }, setEditorState }) => {
          if (dirty) {
            return;
          }
          if (!value) {
            return;
          }
          const contentBlock = htmlToDraft(value);
          const contentState = ContentState.createFromBlockArray(contentBlock.contentBlocks);
          const editorState = EditorState.createWithContent(contentState);
          setEditorState(editorState);
        }
      ),
      withHandlers({
        onEditorStateChange: ({ input: { onChange }, setEditorState }) => (editorState) => {
          setEditorState(editorState);
          const html = draftToHtml(convertToRaw(editorState.getCurrentContent()));
          onChange(html);
        },
      })
    )(WysiwygEditor);

**Comment by SanskarSans** [comment]
Has anyone been successful to use it in formik instead? I am having following problem https://stackoverflow.com/questions/60376563/state-of-draftjs-editor-is-not-preserved-when-moving-to-next-steps
