### ISSUE TITLE
Cannot get focused on textarea inside modal of custom control

### ISSUE THREAD

**Issue by Shadowman4205** [jpuri/react-draft-wysiwyg#567]
Hello, this is weird

i tried adding <textarea> on custom controll component and cannot focus on it while  if i replace it with input it is working.

you can test it with this 

```
class CustomOption extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      value: ""
    };
  }
  render() {
    return (
      <textarea
        value={this.state.value}
        onChange={e => this.setState({ value: e.target.value })}
      />
    );
  }
}

const EditorCustomToolbarOption = () => (
  <Editor
    wrapperClassName="demo-wrapper"
    editorClassName="demo-editor"
    toolbarCustomButtons={[<CustomOption />]}
  />
);
```
if you replace textarea with input you will see it is work normally
Why this happen?

**Comment by jpuri** [comment]
Editor has special handling for inputs in toolbar: https://github.com/jpuri/react-draft-wysiwyg/blob/master/src/Editor/index.js#L372

Looks like I need to add TEXTAREA also here.

**Comment by Shadowman4205** [comment]
@jpuri  are you gonna add it?
