### ISSUE TITLE
lists are rendered with blank lines between list items

### ISSUE THREAD

**Issue by ChuckIrvine** [jpuri/react-draft-wysiwyg#572]
I notice that lists are rendered with blank lines between items, which isn't standard functionality. Is there a way to override this?

Thanks

**Comment by ChuckIrvine** [comment]
I guess this isn't isn't a big deal since when the html is rendered outside of the editor, lists are single spaced. Closing.....

**Comment by jpuri** [comment]
Are you talking about line spacing between lists. You can change them using css class.
