### ISSUE TITLE
need data:image import image behavior

### ISSUE THREAD

**Issue by CharlesIrvineKC** [jpuri/react-draft-wysiwyg#573]
I am porting my web app from using TinyMCE to react-draft-wysiwyg. (Shameless plug: www.evrsity.com). When I import an image using TinyMCE, the image is included inline in the html output using <img src=data:image/... This worked out well for me since I store and retrieve editor data from my mongo database. react-draft-wysiwyg, on the other hand, requires me to essentially create a URL that I can use to embed the image using <img src="aURL". Now I have two forms of persistence - my database and the server which serves my http image requests.

It would be great if react-draft-wysiwyg could be updated to provide the inline image import option. 

Until then, my approach would be, at the point of saving the editor contents, to convert the html exported from the editor state to have the image inline by replacing the image url reference with the actual inlined image. 

Would be great if I could be some advice on whether I am on the right path with this. Thanks

**Comment by jpuri** [comment]
Hey @ChuckIrvine , is it possible that you convert it to data image in and return that from file upload method ?

**Comment by ChuckIrvine** [comment]
It seems that you would need to do this when the user saves his data. Parse the data in the editor's state, looking for the the image URL. Replace that with the base64 strings from the imported image files. Shouldn't be too difficult I would think.

I wonder if anyone can see an advantage to the current design react-draft-wysiwyg over a design where the image data is inlined into the editor's state?

**Comment by jpuri** [comment]
I am wondering why is this not possible in upload function ?

**Comment by ChuckIrvine** [comment]
I suppose that you could. If you did it then, you would do the same thing that I described at save time - right? Or would it be simpler somehow?

**Comment by riseremi** [comment]
If I understand you correctly, your task is to add an image from your device to react-draft-wysiwyg as base64. It is definitely possible to convert it in upload function as @jpuri said.

**Code example**
```js
const getFileBase64 = (file, callback) => {
  var reader = new FileReader();
  reader.readAsDataURL(file);
  // Since FileReader is asynchronous,
  // we need to pass data back.
  reader.onload = () => callback(reader.result);
  // TODO: catch an error
  reader.onerror = error => {};
};

const imageUploadCallback = file => new Promise(
  (resolve, reject) => getFileBase64(
    file,
    data => resolve({ data: { link: data } })
  )
);


<Editor
  toolbar={{
    image: {
      uploadCallback: imageUploadCallback,
      previewImage: true,
    },
  }}
  // Other props
/>
```

**Comment by caominhtung1992** [comment]
help me!
i need change data of editor with Editor have image upload 
 <Editor
     editorState={editorState}

**Comment by riseremi** [comment]
@caominhtung1992 I'm sorry, but I think you should create another issue with more detailed info about your problem. This is an issue about base64 image uploading.

**Comment by conterio** [comment]
@riseremi  so your solution works, however when we save and then go back to edit, the images are not showing up, but the base64 is still there, it's just not showing the images

**Comment by fanguangjian** [comment]
> @ChuckIrvine, if I understand you correctly, your task is to add an image from your device to react-draft-wysiwyg as base64. It is definitely possible to convert it in upload function as @jpuri said.
> 
> **Code example**
> 
> ```js
> const getFileBase64 = (file, callback) => {
>   var reader = new FileReader();
>   reader.readAsDataURL(file);
>   // Since FileReader is asynchronous,
>   // we need to pass data back.
>   reader.onload = () => callback(reader.result);
>   // TODO: catch an error
>   reader.onerror = error => {};
> };
> 
> const imageUploadCallback = file => new Promise(
>   (resolve, reject) => getFileBase64(
>     file,
>     data => resolve({ data: { link: data } })
>   )
> );
> 
> 
> <Editor
>   toolbar={{
>     image: {
>       uploadCallback: imageUploadCallback,
>       previewImage: true,
>     },
>   }}
>   // Other props
> />
> `

Great!!!

**Comment by MS44118** [comment]
hello @jpuri! 
it would be awesome to include directly the solution from @riseremi and @ChuckIrvine :

> @ChuckIrvine, if I understand you correctly, your task is to add an image from your device to react-draft-wysiwyg as base64. It is definitely possible to convert it in upload function as @jpuri said.
> 
> **Code example**
> 
> ```js
> const getFileBase64 = (file, callback) => {
>   var reader = new FileReader();
>   reader.readAsDataURL(file);
>   // Since FileReader is asynchronous,
>   // we need to pass data back.
>   reader.onload = () => callback(reader.result);
>   // TODO: catch an error
>   reader.onerror = error => {};
> };
> 
> const imageUploadCallback = file => new Promise(
>   (resolve, reject) => getFileBase64(
>     file,
>     data => resolve({ data: { link: data } })
>   )
> );
> 
> 
> <Editor
>   toolbar={{
>     image: {
>       uploadCallback: imageUploadCallback,
>       previewImage: true,
>     },
>   }}
>   // Other props
> />
> ```

**Comment by srj-dubey** [comment]
``` 
const uploadImageCallBack = (file: any): any => {
    return new Promise((resolve, reject) => {
      if (file) {
        const reader = new FileReader();
        reader.onload = (): any => {
          resolve({ data: { link: reader.result } });
        };
        reader.onerror = (er): any => {
          console.log('error: ', er);
        };
        reader.readAsDataURL(file);
      }
    });
 };
```
This is what I'm using to to add Base64 Image into the editor. This seems to work fine in Firefox, but I'm having difficulty in Chrome. Any Thoughts? @jpuri @riseremi
