### ISSUE TITLE
onBlur not firing correctly in 1.12.5

### ISSUE THREAD

**Issue by megatrond** [jpuri/react-draft-wysiwyg#581]
I think the bug was introduced in the [latest commit ](https://github.com/jpuri/react-draft-wysiwyg/commit/a8c7c7412bff69b1e42c502e7a37a472ee882879#diff-d5b6483038a12bba737ac7b6e67f678dR18)

In the `else if` block, the comparison probably should be

```javascript
((event.target.tagName !== 'INPUT' || event.target.tagName !== 'LABEL')
 +      && !this.inputFocused)
```

We'll run on 1.12.4 for now :)

**Comment by edencorbin** [comment]
same issue here, rollback fixed the issue. onFocus calls but onBlur does not in 1.12.5, at least in my application.

**Comment by atlanteh** [comment]
Same here

**Comment by uabenjamin** [comment]
same here. onBlur not fired.

**Comment by Subha** [comment]
Same issue. When will this be fixed?

**Comment by jpuri** [comment]
`react-draft-wysiwyg@1.12.7` has the fix. Thanks a lot for reporting this.
