### ISSUE TITLE
Spanish i18n

### ISSUE THREAD

**Issue by Huespal** [jpuri/react-draft-wysiwyg#590]
Really useful project :)

I've created spanish language translations file. How can I include in the project externally. Or can you just provide a new version of the library with spanish translations? Thank you.

[es.js.zip](https://github.com/jpuri/react-draft-wysiwyg/files/1659034/es.js.zip)

**Comment by Huespal** [comment]
I solved like this:
```
import es from './es.js';

[...]

<Editor
    localization={{
      locale: 'es',
      translations: es
    }}
  />
```
File es.js is in the previous comment.

**Comment by Cabezaa** [comment]
excelent proposal! ralated to #583 :)

**Comment by jpuri** [comment]
Language support added in `react-draft-wysiwyg@1.12.7` from this PR https://github.com/jpuri/react-draft-wysiwyg/pull/584.

Thanks a lot :)
