### ISSUE TITLE
Is there a way to make react-draft-wysiwyg as a single line input?

### ISSUE THREAD

**Issue by sontek** [jpuri/react-draft-wysiwyg#593]
We want to make our editor a single input (not multiline) and have an "onEnter" call that saves rather than inserts a newline.   Is this possible?

**Comment by jpuri** [comment]
Hey @sontek passing `handleReturn` as prop to the editor should do it.

**Comment by sontek** [comment]
@jpuri Thanks!  I tried that but it wasn't preventing changes.  For example:

```
                    handleReturn={() => {
                        console.log("HANDLE RETURN");
                        return false;
                    }}
```

I would get the log of "handle return" but the content  would also get a newline.

**Comment by sontek** [comment]
Hah, it needs to be `return true`

**Comment by sontek** [comment]
Thanks!
