### ISSUE TITLE
Support for relative links

### ISSUE THREAD

**Issue by rudfoss** [jpuri/react-draft-wysiwyg#601]
Hi, it seems that none of the demos support relative links. I'm unable to create a link with a url to "/test" as the url property in the state will be empty. Any plans on supporting this?

Edit: Apparently there is no support for anchor references "#anchor" either.

**Comment by rudfoss** [comment]
I've been looking through the source and it seems (though I'm not sure) that it might be due to the use of [linkify-it](https://github.com/markdown-it/linkify-it) to sanitise links. That library does not detect relative links nor does it support id anchors.

**Comment by jpuri** [comment]
Let me check, I think linkify-it can be extended for this use-case.

**Comment by rudfoss** [comment]
Hi, any update on this?

**Comment by kevinhaas** [comment]
This would be really nice.

**Comment by spchuang** [comment]
Having the same issue. What is the blocker here?

**Comment by spchuang** [comment]
seems like #342 solves this problem. Can we revisit that PR again?

**Comment by jpuri** [comment]
https://github.com/jpuri/react-draft-wysiwyg/pull/768 will be able to help here.
