### ISSUE TITLE
Center text not work

### ISSUE THREAD

**Issue by dderr** [jpuri/react-draft-wysiwyg#602]
Text centering does not work when lines wrap

Notice text is left aligned (should be centered).
![image](https://user-images.githubusercontent.com/585448/35712711-0cfe857c-0789-11e8-9528-1303f0cabe49.png)

If I delete text such that it does not wrap then it is working
![image](https://user-images.githubusercontent.com/585448/35712740-42768f1a-0789-11e8-92f8-e0e9a90ba623.png)

**Comment by soybuddha** [comment]
removed text-align: left from the `.public-DraftStyleDefault-ltr` which seems unnecessary. This allows the `rdw-center-aligned-block` styles to work

`.public-DraftStyleDefault-ltr {
  text-align: inherit;
}`
![alignment-style-change](https://user-images.githubusercontent.com/933192/35754729-202b2b54-082a-11e8-9daa-d7e6d9c0cc14.png)

**Comment by jpuri** [comment]
Also, I will add `!important` to `rdw-center-aligned-block` to help in that.

**Comment by jpuri** [comment]
Release `1.12.9` has the change I mentioned above.

**Comment by nuocgansoi** [comment]
Your fix not work. =(
Please change `public-DraftStyleDefault-ltr` to `text-align: inherit;` or another way.
