### ISSUE TITLE
Soft return instead of hard return

### ISSUE THREAD

**Issue by edencorbin** [jpuri/react-draft-wysiwyg#603]
Might be missing something simple, but any way to have every return key function as a shift return, IE a line break? I'm not wanting all the extra line space when a user hits return, and adjusting line height alone doesn't solve my issue.

**Comment by jpuri** [comment]
Hey @edencorbin : if you pass this function as prop it will override the default one: https://github.com/jpuri/react-draft-wysiwyg/blob/master/src/Editor/index.js#L460

You can refer this also https://github.com/jpuri/draftjs-utils/blob/master/js/keyPress.js

**Comment by edencorbin** [comment]
Actually isn't this the same as: https://github.com/jpuri/react-draft-wysiwyg/issues/173? Any update on the feature request?

**Comment by ayushnawani** [comment]
Hey @edencorbin, did you get the solution?

**Comment by edencorbin** [comment]
@ayushnawani I did not get a full solution, I think I did end up adjusting the line height and that's about it, not actively working on that project now.

**Comment by saksham-tj** [comment]
Is the prop "isSoftReturnDefault" is available on "react-draft-wysiwyg": "1.14.4" version?



It didn't seems to work for me.
