### ISSUE TITLE
convert rich text to plain text

### ISSUE THREAD

**Issue by edencorbin** [jpuri/react-draft-wysiwyg#611]
Any way to convert rich styled content into plain un-styled text? It's a very specific use case, but its basically an un-styled snapshot of whats in the editor (styled) that I am looking for. I could potentially iterate through the blocks, wondering if there is a simpler way.

**Comment by jpuri** [comment]
The editor supports all the functions of draftjs, but I am not sure about any such way to get text content from editor content.

**Comment by edencorbin** [comment]
I built a simple loop through content blocks and its working fine:

```
        if (content){
            let toStr = "";
            for (var i=0; i<content.blocks.length; i++){
                toStr+=content.blocks[i].text+" "
            }
            console.log(toStr);
        }
```
This is useful as I'm storing the plain text output as well as rich text for this use case.

**Comment by imjared** [comment]
I attached a ref to my WYSIWYG component then could access the plaintext as follows:

```javascript
handleSubmit() {
  const plaintext = this.wysiwyg.current.state.editorState.getCurrentContent().getPlainText();
}

...

<WYSIWYG
  content={_get(this.props.autoresponder, 'content', '')}
  ref={this.wysiwyg}
/>
```

`this.wysiwyg.current.state.editorState` is basically what we're seeing [here](https://github.com/jpuri/react-draft-wysiwyg/blob/master/stories/BasicContentState/index.js#L7-L9)
