### ISSUE TITLE
Select boxes doesn`t work with portal

### ISSUE THREAD

**Issue by manoelneto** [jpuri/react-draft-wysiwyg#620]
my portal 

```
import React, { Component } from 'react';
import { createPortal } from 'react-dom';

class ModalTest extends Component {

  constructor(props) {
    super(props);

    this.modalTarget = document.createElement("div");
    this.modalTarget.className = "modal-test-target";
  }

  getModalRoot() {
    return document.body;
  }

  componentDidMount() {
    this.getModalRoot().appendChild(this.modalTarget);
  }

  componentWillUnmount() {
    this.getModalRoot().removeChild(this.modalTarget);
  }

  render() {
    return createPortal(
      <div>
        {this.props.children}
      </div>,
      this.modalTarget
    )
  }
}

export default ModalTest;
```

my component witch uses the portal
```
import React, { Component } from 'react';

import { EditorState } from 'draft-js';
import { Editor } from 'react-draft-wysiwyg';
import 'react-draft-wysiwyg/dist/react-draft-wysiwyg.css';

import ModalTest from '../../modal/ModalTest';

class ChallengePage extends Component {

  constructor(props) {
    super(props);

    this.state = {
      editorState: EditorState.createEmpty(),
    };
  }

  onEditorStateChange = (editorState) => {
    this.setState({editorState});
  }

  render() {
    const { editorState } = this.state;

    return (
     ...
        <ModalTest>
          Editor

          <div className="panel">
            <div className="panel-body pt0 pl0 pr0 pb0">
              <Editor
                editorState={editorState}
                onEditorStateChange={this.onEditorStateChange}
              />
            </div>
          </div>
        </ModalTest>
        ...
    );
  }

}

```

but if remove `<ModalTest>` work as expected

```
          <div className="panel">
            <div className="panel-body pt0 pl0 pr0 pb0">
              <Editor
                editorState={editorState}
                onEditorStateChange={this.onEditorStateChange}
              />
            </div>
          </div>        ...
```

with portal not works: ![](https://media.giphy.com/media/23gW4Z4NFGqobnrEJl/giphy.gif)
without portal works: ![](https://media.giphy.com/media/orTBXsLNit72Y7Glvd/giphy.gif)

**Comment by jpuri** [comment]
@manoelneto : I am not sure of the reason - this may be related to the portal code. Are you getting any error in console ?

**Comment by manoelneto** [comment]
No @jpuri, no erros in console.

All my code works properly in portal.

You lib works, buy only these select doesn't.

**Comment by jpuri** [comment]
Can you plz share you code in may be a git repo, I want to see exact issue.

**Comment by Brickpsp** [comment]
maybe z-index smaller of portal.

**Comment by manoelneto** [comment]
Since the day I shared I stop work on this project. When I have time I'll try.

**Comment by jpuri** [comment]
If any of you can share a repo replicating the issue, I want to dig into it and fix this.

**Comment by dwayneparton** [comment]
I ran into this exact same issue. It seems a problem with the portal not the editor. I came across this from [Dan Abramov](https://github.com/facebook/react/issues/12355#issuecomment-410996235) and applied the concept to my portal. Basically, I set the state on componentDidMount instead of setting the elements in the constructor like: 
`
constructor(props) {
    super(props);
    this.modalTarget = document.createElement("div");
    this.modalTarget.className = "modal-test-target";
}
`
The above is almost exactly how we had it. 
Here is the portal code which is working for me.
`
import React from 'react';
import ReactDOM from 'react-dom';

class Portal extends React.Component {
	constructor(props) {
		super(props);
		this.state = {modal: null, el: null };
	}

	componentDidMount() {
		let modal = document.getElementById('root-modal');
		let el = document.createElement('div');
		modal.appendChild(el);
		this.setState({ modal, el });
	}

	componentWillUnmount() {
		this.state.modal.removeChild(this.state.el);
	}

	render() {
		const { el } = this.state;
		if (!el) {
			return null;
		}
		return ReactDOM.createPortal(this.props.children, el);
	}
}
`
Hope that helps.

**Comment by manoelneto** [comment]
Helped a lot. I stoped work in this particular project, but when I return, I'll try this approach. Thanks @dwayneparton so much.

**Comment by manoelneto** [comment]
@dwayneparton @jpuri it worked. I think read.me should be updated. But I didn't tested with new react versions

**Comment by Levon1994** [comment]
thank you @dwayneparton , in my side it also workd correctly!
