### ISSUE TITLE
EditorState and onBlur

### ISSUE THREAD

**Issue by jan0991** [jpuri/react-draft-wysiwyg#630]
I am trying to use uncontrolled input (to avoid updating/re-rendering big app for every change) and update redux store only onBlur. Problem? onBlur doesn't pass the EditorState. 

This issue was already opened but also closed without any answer: https://github.com/jpuri/react-draft-wysiwyg/issues/308

Anyone found a way to make this work?

**Comment by alfaslash** [comment]
@jan0991 
you can see my pr #643

**Comment by jpuri** [comment]
PR looks good, thx I am merging it and will soon also release.

**Comment by jpuri** [comment]
Released in version `react-draft-wysiwyg@1.12.12`.
