### ISSUE TITLE
Links urls are sliced after round brackets

### ISSUE THREAD

**Issue by Geloosa** [jpuri/react-draft-wysiwyg#638]
Hello!

I've run into a problem with links urls: 
if Link Target contains `(` or `)` symbol, an EditorState instance receives a sliced url on editor state change - all chars after `(` or `)` are sliced.

Round brackets are legal chars in urls, so it seems to be a bug. =(

**Comment by Geloosa** [comment]
The problem turned out to be in this module https://github.com/markdown-it/linkify-it

**Comment by redaben** [comment]
hey @Geloosa ! How did you solve your problem ? I'm facing the same one ...
