### ISSUE TITLE
Image upload enabled not working

### ISSUE THREAD

**Issue by tusharkhatiwada** [jpuri/react-draft-wysiwyg#639]
Hi there,
The File upload option is missing for the image. Screenshot attached.

<img width="418" alt="screen shot 2018-04-06 at 3 24 13 pm" src="https://user-images.githubusercontent.com/5126590/38414565-9be6919c-39ae-11e8-9831-520a70f38573.png">

I've enabled it in my code though:

```
<Editor
        wrapperClassName="editorWrapper"
        toolbarClassName="toolbarWrapper"
        onEditorStateChange={this.onEditorStateChange}
        toolbar={{
          options: ['inline', 'blockType', 'fontSize', 'list', 'textAlign', 'image', 'history'],
          image: {
            urlEnabled: true,
            uploadEnabled: true,
            uploadCallback: this.uploadFile
          }
        }}
      />
```
Am I missing something?
Thanks for this awesome component.

**Comment by tusharkhatiwada** [comment]
Sorry, figured out the problem. Hadn't written the `uploadFile` callback function.

**Comment by Shreykhanna** [comment]
Does this image upload works because mien it shows broken image. Cant figure out exactly why this is happening?
CODE: 
const uploadFile = (file) => {
    console.log('file',file);
    return new Promise(
      (resolve)=>{
        resolve({data:{link:file.name}});
      }
    );

};

**Comment by deniz-yuce** [comment]
> Sorry, figured out the problem. Hadn't written the `uploadFile` callback function.

Can you share the callback function? Thank you.

**Comment by codigoisaac** [comment]
> options: ['inline', 'blockType', 'fontSize', 'list', 'textAlign', 'image', 'history'],

For me it doesn't work.

Code:

`<Editor editorState={editorState} onEditorStateChange={setEditorState} placeholder='Enunciado da alternativa' handlePastedFiles={addPastedImgToServer} toolbar={{
  options: ['inline', 'blockType', 'fontSize', 'list', 'textAlign', 'image', 'history'],
  image: {
    urlEnabled: true,
    uploadEnabled: true,
    uploadCallback: undefined,
    inputAccept: 'image/gif,image/jpeg,image/jpg,image/png,image/svg',
    uploadFile: undefined
  }
}} />`

All I see is the url input.

**Comment by ahelmi365** [comment]
> Can you share the callback function? Thank you.

+1
