### ISSUE TITLE
Load Html and keep font-size and colors

### ISSUE THREAD

**Issue by MarinusDR** [jpuri/react-draft-wysiwyg#64]
Hello Jyoti.
I think your draft editor is great. I appreciate all your work!
You take the time to answer questions. What a service!

My question is about the possibility to load HTML into the editor.
It works fine. But things like font-size and colors are gone..

Think that you had some different font-sizes and font-colors in your
sampleEditorContent.js which is used in one of your samples here: initialContentState={sampleEditorContent}.
How could we keep/show them?

**Comment by jpuri** [comment]
Hi @MarinusDR,

For converting HTML to Editor Content i have used DraftJS library function. Atm it does not take care of all HTL attribute - and looking at vast HTML syntax its also hard.

For saving and re-hydrating Editor state I would strongly recommend using JSON, HTML should be used only for display purpose.

I would think about creating a library for HTML to Editor content which would support at-least all the styling provided by this editor.

**Comment by MarinusDR** [comment]
Thank you so much for your quick response!
Now I use Json to save the Editor state and it works great!

First I make a json string from the Editor:
var jsonString = JSON.stringify(this.state.editorContents[0], null, 4);
This string can be saved to the database.

Later I can get the string from the database and make it 'raw':
var raw = JSON.parse(jsonString);
initialContentState= {raw}

Should you have done it in the same way?

**Comment by MeierRm** [comment]
Hi, sorry bin gerade besch?ftigt, kannst du das installieren, bitte

Von meinem iPhone gesendet

Am 22.11.2016 um 15:43 schrieb MarinusDR <notifications@github.com<mailto:notifications@github.com>>:


Thank you so much for your quick response!
Now I use Json to save the Editor state and it works great!

First I make a json string from the Editor:
var jsonString = JSON.stringify(this.state.editorContents[0], null, 4);
This string can be saved to the database.

Later I can get the string from the database and make it 'raw':
var raw = JSON.parse(jsonString);
initialContentState= {raw}

Should you have done it in the same way?

-

**Comment by ZeroCho** [comment]
@jpuri +1 for creating a library for HTML to Editor content.
Because currently convertFromHTML(draftjs function) doesn't support iframe. I'm seeking for the solution.

**Comment by sureshHARDIYA** [comment]
+1 for creating a library for HTML to Editor Content. I am looking for the solution as well. Also feature like ability to see the source code and modify it would be great.

**Comment by jpuri** [comment]
There is already an issue for converting HTML to editor state, thus closing this: https://github.com/jpuri/react-draft-wysiwyg/issues/103
