### ISSUE TITLE
defaultTargetOption not setting link target

### ISSUE THREAD

**Issue by marciaga** [jpuri/react-draft-wysiwyg#640]
Hi,
I'm trying to set the target option of links as shown below, but although the checkbox for "open link in new window" is checked, when you click on "Add", the resulting link content has a `target="_self"` attribute set. Toggling the checkbox also seems to not be invoking the callback. 

```
const linkOptions = {
    defaultTargetOption: '_blank'
};

 <Editor
     toolbar={{ link: linkOptions }}
/>
```

Is anyone else able to duplicate this issue? I haven't changed anything in my codebase and one of the users of my application has indicated that this feature used to work.

**Comment by jpuri** [comment]
I am checking this out.

**Comment by jpuri** [comment]
I just added it here: https://github.com/jpuri/react-draft-wysiwyg/blob/master/stories/ConvertToHTML/index.js#L44

Its working well.

**Comment by jpuri** [comment]
Also try once with the latest version of the editor since I tested on latest code.

**Comment by marciaga** [comment]
It's working perfectly! I upgraded both `draft-js` to `0.10.5` and this library to `1.12.12`, which I completely forgot to try (or maybe I thought I'd already tried). Anyway, thanks for the help!

**Comment by jpuri** [comment]
Great 👍

**Comment by RamNagendran** [comment]
in my case, 

    link: {
              inDropdown: false,
              defaultTargetOption: '_self',
              options: ['link', 'unlink'],
            },

even if give "_self"  as default, it always opens in new tab only.....what should i do for self tab.....
