### ISSUE TITLE
Text editor shows unpredictable behaviour when entering text (mobile)

### ISSUE THREAD

**Issue by DineshMadhanlal** [jpuri/react-draft-wysiwyg#641]
I have tested this with my Samsung Galaxy S7 Edge. When typing text in the editor text is often deleted, duplicated or overwritten. It's really hard to get a note in at all. One problem I can replicate at will:
- Typing "12.5" results in duplication to "12.512.5"
- Other problems come and go.
- The issue gets really bad if you use the Google GBoard (which allows for handwriting). 
- Most of the time text entered gets deleted immediately after you entered it. 
- Also deleting text doesn't work since it always comes back.

**Comment by kwarr128** [comment]
Draftjs doesnt support mobile yet https://draftjs.org/docs/advanced-topics-issues-and-pitfalls.html

**Comment by DineshMadhanlal** [comment]
Oh, I see. Thanks, @kwarr128. I was wondering how Facebook mobile works since it has implemented draft.js. Please do correct me if I am wrong.

**Comment by kwarr128** [comment]
As far as i know, if you go to facebook.com on an android phone (instead of using the app), the comment boxes and stuff are just plain textareas

**Comment by DineshMadhanlal** [comment]
But, how about Facebook in browsers? It suggests peoples when we type **@** and as far as I know, that stuff is taken care by Draft.js.

**Comment by kwarr128** [comment]
Its not just "taken care of". You have to implement it using draft entities and decorators, which i believe @jpuri has done in this editor.

**Comment by DineshMadhanlal** [comment]
Yeah. The decorators are also implemented by @jpuri and that's great. I was just wondering how Facebook  works in mobile browsers.

**Comment by DineshMadhanlal** [comment]
I am closing this issue as it is a Draft.js mobile issue and not react-draft-wysiwyg issue.
