### ISSUE TITLE
Cannot set bold/italics/underline without any text highlighted

### ISSUE THREAD

**Issue by briancappello** [jpuri/react-draft-wysiwyg#65]
Noticed this just playing around on the demo page. Firefox 49. 

Expected behaviour: I click, and it toggles. Together, they should behave like checkboxes, not radio buttons.

**Comment by MarinusDR** [comment]
Yes, I noticed this as well: the bold/italic/underline/.. -buttons **only** work when some text has been selected.

**Comment by cmpis** [comment]
At the very least the section where the cursor is and text exists should be affected. But both empty text and existing text do not respond the buttons without selection

**Comment by jpuri** [comment]
@briancappello: its already like checkboxes, its not exclusive selection. Or do I not understand the issue you are mentioning. Can you plz share video.

@MarinusDR / @0xCMP: I see what you are saying has a point. This is currently a limitation with DraftJS. I will think over fixing it.

**Comment by jpuri** [comment]
Closed  by mistake.

**Comment by MarinusDR** [comment]
Look at the behaviour here: https://facebook.github.io/draft-js/
Click on BOLD and type some text.
Now click on BOLD again and type some text.
This works without selecting anything.  :-)

**Comment by jpuri** [comment]
I have prioritized this bug to be fixed soon. Thank a lot @MarinusDR, @briancappello, @0xCMP for pointing this out.

**Comment by jpuri** [comment]
The issue has been fixed and will soon be released.

**Comment by jpuri** [comment]
This issue has been fixed and released.
