### ISSUE TITLE
new linkify-it implementation doesn't take into consideration tel links

### ISSUE THREAD

**Issue by omerdn1** [jpuri/react-draft-wysiwyg#650]
hey guys, so because of the `linkify-it` `tel:` links don't work and the URL is set to `""`.
want me to create a PR?

**Comment by jpuri** [comment]
PR is welcome 👍

**Comment by omerdn1** [comment]
@jpuri I thought adding a new linkify schema for `tel:` would solve the problem but it seems like it takes more than that, can you have a look please?

**Comment by jpuri** [comment]
https://github.com/jpuri/react-draft-wysiwyg/pull/768 will be able to help you @serialbandicoot .
