### ISSUE TITLE
image uploadCallback should not assume response.data use 'link', it could be 'url'

### ISSUE THREAD

**Issue by endiliey** [jpuri/react-draft-wysiwyg#653]
**Relevant code:**
https://github.com/jpuri/react-draft-wysiwyg/blob/master/src/controls/Image/Component/index.js#L130-L135

**Comparison of popular image uploading api, assuming we use axios**
1. imgur (https://api.imgur.com/models/image)
uploaded image url is returned at `response.data.link`

2. cloudinary (https://cloudinary.com/documentation/upload_images#upload_response)
uploaded image url is returned at `response.data.secure_url` and `response.data.url`

**What is the problem ?**
Some people might use cloudinary or other image upload services instead of imgur but their uploadCallback will fail on react-draft-wysiwyg because imageUpload assume the data reside at `data.link` instead of general `data.url`

**Solution**
Few solutions are available, e.g:
1. A dirty solution is that react-draft-wysiwyg user had to modify their response data in their code to include `link`
2. A slightly better solution is to modify the code to assume the url reside at either `data.url` or `data.link`
3. A better solution is to let user let us know the 'key' of where the url is residing. Example: if key is 'url', we will check `data.url` instead of `data.link`
 

Let me know if you think this is a problem and what approach should we use to solve this.

**Comment by endiliey** [comment]
Merged #654

**Comment by johnpaul89** [comment]
### **Solution to Cloudinary** **_The ones using url instead of link_**



`function uploadImageCallBack(file) {
            return new Promise(
            (resolve, reject) => {
                const xhr = new XMLHttpRequest();
                xhr.open('POST', '<Your URL>');
                // xhr.setRequestHeader('Authorization', 'Client-ID XXXXX');
                const data = new FormData();
                data.append("file", file);
                data.append("resource_type", "___");
                data.append("upload_preset", "___");
                data.append("cloud_name", "___");
                xhr.send(data);
                xhr.addEventListener('load', () => {
                    
                    var data = JSON.parse(xhr.responseText);

                    // Magic Happens Here

                    var response = {data:  {link: data.secure_url} }
                    // console.log(response)
                
                resolve (response);
                // console.log(response);
                });
                xhr.addEventListener('error', () => {
                const error = JSON.parse(xhr.responseText);
                reject(error);
                });
            }
            );
        }`
