### ISSUE TITLE
Multiple toolbar modals open causes bugs

### ISSUE THREAD

**Issue by asantos00** [jpuri/react-draft-wysiwyg#66]
When you click on multiple toolbars it opens one without closing another (i think closing the other toolbars would be a nice and normal behaviour).

<img width="457" alt="screen shot 2016-11-22 at 11 14 49" src="https://cloud.githubusercontent.com/assets/2593480/20522219/07ba3410-b0a7-11e6-8b02-320d0c034838.png">

**Comment by jpuri** [comment]
Yep this is expected behavior, in fact I already have another issue create for this #31. Handling mouse down events across toolbar and editor is tricky. This need more time I plan to do it.

**Comment by jpuri** [comment]
Issue has been fixed and change is in develop branch.

**Comment by jpuri** [comment]
Issue has been fixed and release in version `1.2.0`.
