### ISSUE TITLE
install on react ssr

### ISSUE THREAD

**Issue by pedromguerra** [jpuri/react-draft-wysiwyg#660]
I always get this error: client.js:21 Uncaught TypeError: Cannot read property 'getIn' of undefined
after trying to run the editor on server side render react.

what I need to do to run the editor on ssr?

thanks

**Comment by jpuri** [comment]
@pedromguerra , can you plz share the whole stack trace here.

**Comment by jakerobers** [comment]
A little more context:

On load, I get

```
warning.js:33 Warning: Prop `data-offset-key` did not match. Server: "2h08u-0-0" Client: "8vpol-0-0"
```

So

```
editorState.getBlockTree(anchorBlockKey)
```

I believe it expects the parameter: `8vpol`

but gets: `2h08u` instead.

**Comment by jakerobers** [comment]
The solution that I have come up with is to set a flag on `componentDidMount` and only render the editor after the component has been mounted client side. I believe this is a sufficient work-around.

Also see: https://github.com/facebook/draft-js/pull/796

We can probably close the issue since this probably has to be addressed in draft-js

**Comment by jelenajjo** [comment]
@jakerobers I am having the same issue, can you please share code example how you solved it? I am not sure that I understand how to solve it from your description. It would mean a lot!

**Comment by erikmueller** [comment]
@jelenajjo taken from https://github.com/facebook/draft-js/issues/385#issuecomment-266552300

something like:

```js
constructor(props) {
  super(props)
  this.state = {
    editor: false,
  }
}

// Once component mounts, enable editor
componentDidMount() {
  this.setState({
    editor: true
  })
}

render() {
  const { editor } = this.state
  return (
    <div className="someComponent">
      { editor
        ? <DraftEditor />          
        : null
      }
    </div>
  )
}
```

**Comment by KubaZachacz** [comment]
@erikmueller thanks! Works like a charm with Next.js

**Comment by pdandradeb** [comment]
It didn't work for me (I'm also using Next.js). I end up using dynamic importing as suggested [here](https://stackoverflow.com/a/57848309/715451):

```javascript
import dynamic from 'next/dynamic'
const Editor = dynamic(() =>
  import('react-draft-wysiwyg').then(mod => mod.Editor)
)
```

**Comment by thicodes** [comment]
@pdandradeb Nice! I tried with dynamic, but i got this error: "Window is not defined"
I passed `ssr: false` and work fine

```js
const Editor = dynamic(
  () => {
    return import('react-draft-wysiwyg').then((mod) => mod.Editor);
  },
  { loading: () => null, ssr: false },
);
```

**Comment by devwhatoplay** [comment]
```
Module parse failed: Unexpected token (19:9)
You may need an appropriate loader to handle this file type.
|
| var Editor = dynamic(function () {

return import("react-draft-wysiwyg").then(function (mod) {
| return mod.Editor;
| });`
```

I applied the code above but still getting this error

**Comment by nagayev** [comment]
@thicodes Thanks a lot!
