### ISSUE TITLE
Disabling features in the toolbar

### ISSUE THREAD

**Issue by erkidhoxholli** [jpuri/react-draft-wysiwyg#661]
Hello,

I was wondering how can I disable/remove different features from the toolbar, ex: Removing 'Image' button.
I cant seem to find anything in the docs.

Nevermind I found it: 
```
toolbar={{
    options: ['inline', 'blockType', 'fontSize', 'list', 'textAlign', 'history'],
}}
```

**Comment by steve-king** [comment]
@jpuri Thanks for the great work on this package!

The above configuration is not working for me. Any changes I make to the toolbar.options array above have no effect on the toolbar options displayed.

I would like to remove most of the formatting options from the toolbar and I cannot find any way to do this. Please help?

Many thanks

**Comment by prakriti89** [comment]
Same here! I also always see full default toolbar. Please help!

**Comment by jeemonputhusseri** [comment]
I also have the same problem, for some reason earlier it worked, not sure i installed any supporting plugin at that time, later once i recloned the repo its not wrking

**Comment by jeemonputhusseri** [comment]
Its working for me now, its just version issue

**Comment by jeemonputhusseri** [comment]
> Same here! I also always see full default toolbar. Please help!

Just roll back the version

**Comment by gemamreza** [comment]
hello @jeemonputhusseri i have same issues, which version do you use? thanks

**Comment by ivan133** [comment]
I think it happens when I add inline option!!!
Works:
```
                        toolbar={{
                          options: ['inline', 'blockType', 'fontSize', 'list', 'textAlign',
                            'history'],
                        }}
```
Does not work
```
                        toolbar={{
                          options: ['inline', 'blockType', 'fontSize', 'list', 'textAlign',
                            'inline',
                            'history'],
                        }}
```

**Comment by muskankhedia** [comment]
@ivan133 Can you also please mention how to disable the desired inline features as well in the toolbar?

**Comment by KotAleksei** [comment]
just do it in that way 
`        toolbar={{
          options: ['inline', 'list', 'link'],
          inline: {
            options: ['bold', 'italic', 'underline'],
          },
          list: { options: ['unordered', 'ordered'] },
          link: { showOpenOptionOnHover: false },
        }}`
