### ISSUE TITLE
Positioning of the Toolbar vs. the editor

### ISSUE THREAD

**Issue by itsDZhang** [jpuri/react-draft-wysiwyg#673]
Hi,

I was wondering if there's an option to change the position of the editor and the Toolbar?
For ex. I want to place the toolbar at the bottom. 

I need to have the 'toolbarOnFocus' option on so if it's focused, it looks like:
![image](https://user-images.githubusercontent.com/16616714/40890525-8578aeee-672c-11e8-8625-f520dcbe6dc0.png)

However when the user navigates somewhere else, it'll look like this:
![image](https://user-images.githubusercontent.com/16616714/40890529-9130b7fe-672c-11e8-9cbe-868706bd2921.png)

I would like the toolbar to be placed at the bottom.

**Comment by itsDZhang** [comment]
used this:https://developer.mozilla.org/en-US/docs/Web/CSS/order 

Solved

**Comment by galmyndlift** [comment]
@itsDZhang 
Hey there, 
Where did you use "order" in order to set the toolbar below?
I cant figure it out
