### ISSUE TITLE
Non standard links e.g. myapp://xyz

### ISSUE THREAD

**Issue by serialbandicoot** [jpuri/react-draft-wysiwyg#674]
Hi,

I'm using the library and then re-rendering in an iOS app. Linking standard links such as http or https is great. However I want to deep link, which means using a non-standard link. e.g. myapp://xyz/123

`{\"url\":\"\",\"targetOption\":\"_self\"}}`

The result is the url is empty. It looks like the library is using Linkify.It, which is stripping out non standard domains. In my case this is not so good...as above.

Is there a way of allowing these types of links? :)

**Comment by serialbandicoot** [comment]
I've added a question in the linkify library - see what they come back with. :)

https://github.com/markdown-it/linkify-it/issues/64

**Comment by serialbandicoot** [comment]
Given there is a way of adding in new schemas https://github.com/markdown-it/linkify-it#addkey-value is there a way of being able todo this with the library?

I'm happy to take a look at the code, if you point me in the right direction?

**Comment by jpuri** [comment]
https://github.com/jpuri/react-draft-wysiwyg/pull/768 will be able to help you @serialbandicoot .
