### ISSUE TITLE
Extra space added when inserting link

### ISSUE THREAD

**Issue by jaminmelville** [jpuri/react-draft-wysiwyg#681]
Hi thanks for this project, it's really useful!
I have noticed that when you have existing words separated by spaces and you add a link to any word (except the last) then you end up with another space being inserted.
This is a slightly different issue from #676. 

eg:
Before = 'this is text'
After = 'this [is](#) &nbsp;text'

Notice there's 2 spaces between 'is' and 'text' afterwards.

I've come up with a solution [here](https://github.com/jaminmelville/react-draft-wysiwyg/tree/bug/multiple-spaces-with-links) but I don't really know what I'm doing when it comes to draft-js so it's probably not that useful.

Cheers

**Comment by slavikbez** [comment]
Facing the same problem. Would be great if this extra space could be set to on/off via config

**Comment by jmoonorm** [comment]
Please, if possible, merge this fix

**Comment by TheoKand** [comment]
Does anyone know when this fix is going to be merged or when the issue will be fixed by other means?

**Comment by mathew2450** [comment]
Would like to see this implemented as well!

**Comment by ScottBurfieldMills** [comment]
@jpuri Can this please be addressed?

**Comment by imamatory** [comment]
It would be so nice if someone merged #707 and closed this issue

**Comment by simonprovost** [comment]
When #707 will be merge please ? Sometimes it could be hard to detect if it's us or the add link option which've added the extra space.

Please, let us know when you planned to merged this one💡
Thank you for this PR @slavikbez btw 🕵️‍♂️
