### ISSUE TITLE
Prefix classes

### ISSUE THREAD

**Issue by jackmoore** [jpuri/react-draft-wysiwyg#69]
Quick suggestion, if you are going to use classes to assign styles then you should probably add some sort of unique or definable prefix to the class names.  Right now you are opening yourself up to a lot of unintentional collisions if someone were to use this in an existing project.  Currently it would be difficult for others to keep in mind what all class names you've taken off the table.

**Comment by jpuri** [comment]
Ah that is very useful suggestion. I will soon implement it. Thanks again @jackmoore.

**Comment by jpuri** [comment]
This has been fixed and released.
