### ISSUE TITLE
How to disable copy and paste on the editor?

### ISSUE THREAD

**Issue by gnyani** [jpuri/react-draft-wysiwyg#692]
Hi,

I want to make the editor not copyable and also not pasteable. If its a text area I can suppress this by simpy doing : 

```
onCut={(event)=>{event.preventDefault()}} onCopy={(event)=>{event.preventDefault()}}
    onPaste={(event)=>{event.preventDefault()}}
```

I.e. by supressing the default event. Please let me know how to configure this rich text editor to supress these actions.

An example of implementation will really help.

Thanks,
Gnyani

**Comment by gnyani** [comment]
@jpuri  any help is really appreciated.

**Comment by archansel** [comment]
using `stripPastedStyles` props work for me
