### ISSUE TITLE
Avoid 'undefined' class name

### ISSUE THREAD

**Issue by jackmoore** [jpuri/react-draft-wysiwyg#70]
Be mindful of passing undefined values to className, because React interprets that as a class name of `"undefined"`.  When I inspect your editor, I see a lot of `class="... undefined"`.

**Comment by jpuri** [comment]
Oh I see, at a lot of places I am passes props to classnames and that is optional and can result in undefined. I will fix this. Thanks a lot for pointing this out.

**Comment by jpuri** [comment]
The issue has been fixed and will soon be released. Thanks a lot @jackmoore for ur nice suggestions.

**Comment by jpuri** [comment]
The change has been completed and released.
