### ISSUE TITLE
"Edit link" and "unlink" actions not working when link is highlighted from right to left

### ISSUE THREAD

**Issue by slavikbez** [jpuri/react-draft-wysiwyg#708]
Steps to reproduce:

1. I have an existing link in my description editor
2. I want to edit the Link Title and/or Link Target
3. I highlight the link in my description editor (from right to left)
4. I click the "link" button
5. I change the Link Title and/or Link Target 
6. I click "Add"
7. The description editor did not edit my original link, instead it added 2+ additional links

Same steps can be used for "unlink" action

SelectionState 
```
const selectionState = editorState.getSelection();
const isBackward = selectionState.getIsBackward();
``` 
knows about `isBackward` selection. Maybe this is something to take in count when setting anchor and focus offsets here: 
https://github.com/jpuri/react-draft-wysiwyg/blob/master/src/controls/Link/index.js#L127 
and here: 
https://github.com/jpuri/react-draft-wysiwyg/blob/master/src/controls/Link/index.js#L111

**Comment by slavikbez** [comment]
https://github.com/jpuri/react-draft-wysiwyg/pull/709

**Comment by jpuri** [comment]
`react-draft-wysiwyg@1.12.19` has the fix. Thanks @slavikbez for the PR.
