### ISSUE TITLE
Issue with nesting/indenting unordered lists within ordered lists?

### ISSUE THREAD

**Issue by Don-L** [jpuri/react-draft-wysiwyg#717]
This is probably a bit of an edge case, but I've encountered a potential issue where a user tries to add an indented unordered list inside an ordered list; the sequence of the top level list items after indentation is not preserved. So a user might want to create a list like this:

1. Ordered list item one
    • Unordered list item
    • Unordered list item
2. Ordered list item two
3. Ordered list item three

However (unless I'm missing something), in attempting to use the list types and indentation offered by react-draft-wysiwyg, they'll end up with a list that looks something like this:

1 Ordered list item one
        • Unordered list item
        • Unordered list item
1 Ordered list item two
2 Ordered list item three

Do you think this could be fixed?

BTW, we and our clients have been using the editor for several months now and think it's great!

Thanks.

**Comment by harsharora04** [comment]
were you able to solve this?

**Comment by Don-L** [comment]
No we decided this was an edge case so didn't spend much time looking for a solution. Apologies if I caused any confusion by closing the issue.
