### ISSUE TITLE
Problem importing Editor - Can't resolve 'draft-js'

### ISSUE THREAD

**Issue by thiagoiferreira** [jpuri/react-draft-wysiwyg#727]
I ran npm install **```react-draft-wysiwyg```,** imported the Editor by using **``` import { Editor } from 'react-draft-wysiwyg';```**, yet, without even trying to use the Editor tag in my render it presents me with the error below, I have restarted the build and all but it still presents me with error.

```
Failed to compile.
./node_modules/react-draft-wysiwyg/dist/react-draft-wysiwyg.js
Module not found: Can't resolve 'draft-js' in '/home/thiago/Documents/projects/puma/puma-frontend/node_modules/react-draft-wysiwyg/dist
```

**Comment by kenshinman** [comment]
is this plugin still being maintained? is it still working?

**Comment by kenshinman** [comment]
Had to use `react-quill` in the end

**Comment by thiagoiferreira** [comment]
https://github.com/jpuri/react-draft-wysiwyg/issues/390
I found the answer in the Issue above, basically had to add a --save when doing the plugins install.
```npm i --save draft-js react-draft-wysiwyg```
the projects readme didn't add the --save in the install instructions, making it so the error above occurred.

**Comment by marinona** [comment]
> #390
> I found the answer in the Issue above, basically had to add a --save when doing the plugins install.
> `npm i --save draft-js react-draft-wysiwyg`
> the projects readme didn't add the --save in the install instructions, making it so the error above occurred.

It solved the problem for me 👍

**Comment by theshubhagrwl** [comment]
> #390
> I found the answer in the Issue above, basically had to add a --save when doing the plugins install.
> `npm i --save draft-js react-draft-wysiwyg`
> the projects readme didn't add the --save in the install instructions, making it so the error above occurred.

This instruction is not updated in the Docs on the website.
It says draft-js as a dependency but I think it will be better if we add draft-js in the yarn/npm command.
![image](https://user-images.githubusercontent.com/37265683/131452909-ccedf196-4ce7-4a8e-9597-7baeba165992.png)
