### ISSUE TITLE
How to use spellcheck?

### ISSUE THREAD

**Issue by MarinusDR** [jpuri/react-draft-wysiwyg#73]
The spellcheck does not work annymore in your samples.
I tried to include "spellcheck={true}".
But that made no difference.

**Comment by jpuri** [comment]
@MarinusDR: I actually took off that feature it was interfering with mentions. I want to take some time to built it more nicely. Sorry for the inconvenience but it will be there soon.

**Comment by MarinusDR** [comment]
Thank you so much for your quick response!

**Comment by jpuri** [comment]
@MarinusDR: the issue is fixed, will be available in library after next minor release, hopefully next week.
