### ISSUE TITLE
Any way to add remove link button

### ISSUE THREAD

**Issue by saiemsaeed** [jpuri/react-draft-wysiwyg#735]
Hey Devs, I want o add remove button on link hover box. I have attached screenshot below have a look box. For now, it contains 'Add' and 'Cancel' buttons, i want to add another one 'Remove', that removes link for this button, as unlink icon on toolbar does. Please let me know if there is some builtin for this.

Thanks in Advance!
<img width="479" alt="screenshot 2018-10-13 at 7 24 12 am copy" src="https://user-images.githubusercontent.com/33630921/46900309-7ad74500-ceb9-11e8-8554-f7e94b14c533.png">

**Comment by UliaAlen** [comment]
Can you show result if you have solved this problem?
