### ISSUE TITLE
Allow user to configure RTL

### ISSUE THREAD

**Issue by jpuri** [jpuri/react-draft-wysiwyg#74]

**Comment by jpuri** [comment]
RTL is important requirement for the editor. DraftJS uses bidi algo to determine test direction. But the editor also out of box supports RTL. But it still needs following:

1. Text direction should be reflected in generated HTML. This should be done at the level of each block.

2. User should be able to pass a parameter to strictly override the results of bidi algo.

**Comment by jpuri** [comment]
Code changes have been completed and will be part of next release.

**Comment by Navid61** [comment]
I'm going to know how I can put cursor position at correct position when user is changing language from RTL to LTR or LTR to RTL during he/she is typing?
for instance: if user began with a word in LTR when he/she did finish type, cursor must be end of the  LTR word however if user want switch to RTL language, Naturally cursor position must be start from end of last previous word like like this "Hi سلام" conversely, if user began from right to left by an English word cursor position will be like below:

assume text direction is RTL but user began with an English word
                                                                                                                                                                                                Hi, سلام
whereas, I'd expect this one: 
                                                                                                                                                                                                 سلام ،Hi
