### ISSUE TITLE
Not possible to correct after usage of dictation

### ISSUE THREAD

**Issue by dzmitryburiak** [jpuri/react-draft-wysiwyg#762]
Hi Colleagues,

We have flowing issue.

Once text captured with usage of dictation it's not possible to remove any character. This issue is reproducible even on demo page https://jpuri.github.io/react-draft-wysiwyg/#/

Is there any workaround for that issue?

Thanks,
Dmitri

**Comment by jpuri** [comment]
This is actually issue with draftjs lib :(

**Comment by jpuri** [comment]
Hey @dzmitryburiak : draftjs support for mobile is not good :(
And the issue continue to be in this editor also.

**Comment by dzmitryburiak** [comment]
Ok. That's not a good news for us, but anyway, let's close the issue if it's not possible to fix...
Thanks!

**Comment by jpuri** [comment]
:(
