### ISSUE TITLE
Toolbar & ReactDOM.createPortal

### ISSUE THREAD

**Issue by pavel-sindelka** [jpuri/react-draft-wysiwyg#766]
Hello, could you add option for create portal to toolbar?

**Comment by jpuri** [comment]
Hey @pavel-sindelka , this will definitely be good feature. I am not spending a lot of time on project atm. I am not sure how soon I will be able to build it.

I will be happy to have a PR about this.

**Comment by pavel-sindelka** [comment]
@jpuri OK. Im working on it right now. When I have it finished I will send you PR.

**Comment by PeiyunBai** [comment]
![image](https://user-images.githubusercontent.com/23203887/50891375-17689f00-1437-11e9-8d19-285715d2ba1e.png)

**Comment by jpuri** [comment]
Thanks @pavel-sindelka

**Comment by markolofsen** [comment]
@pavel-sindelka it's ready?))) I'm waiting too

**Comment by pavel-sindelka** [comment]
@markolofsen Yes it is but I dont have time to do MR.
Here is example: https://ibb.co/8BwXtZj

**Comment by markolofsen** [comment]
@pavel-sindelka It's look nice, how to test it?)

**Comment by mitchellwarr** [comment]
Genuinely excited if this gets put in

**Comment by RedFish** [comment]
Any update?
