### ISSUE TITLE
getEntityRange returns undefined after refresh

### ISSUE THREAD

**Issue by norayr93** [jpuri/react-draft-wysiwyg#774]
I have a very strange error case that i couldn't resolve already a very long time . 
```
addCTABox = (boxTitle, boxText, buttonText, url, ctaTargetLinkOption) => {
    const { editorState, onChange } = this.props;
    const { currentEntity } = this.state;
    let selection = editorState.getSelection();

    if (currentEntity) {
      const entityRange = getEntityRange(editorState, currentEntity);
      console.log( entityRange, ' entityRange');
      selection = selection.merge({
        anchorOffset: entityRange.start,
        focusOffset: entityRange.end,
      });
    }

    const entityKey = editorState
      .getCurrentContent()
      .createEntity('CTA_BOX', 'MUTABLE', {
        ctaTitle: boxTitle,
        ctaText: boxText,
        ctaButtonText: buttonText,
        url,
        targetOption: ctaTargetLinkOption,
      })
      .getLastCreatedEntityKey();

    let contentState = Modifier.replaceText(
      editorState.getCurrentContent(),
      selection,
      `${buttonText}`,
      editorState.getCurrentInlineStyle(),
      entityKey,
    );
    let newEditorState = EditorState.push(editorState, contentState, 'insert-characters');

    onChange(EditorState.push(newEditorState, contentState, 'insert-characters'));
    this.doCollapse();
  };
```
When i first create some **container** which lets assume has a button, title and description, it creates it without any problem and also editing is working nice , but after refreshing my page (which sends the draft editor content to server and loads it back after refreshing) , when i click **edit** , change something (let's assume button text) and try to save it , entityRange returns me undefined. So i can't find the solution , and even worse , i have also tried maybe all possible ways to solve this problem , but couldn't manage it . If you need , i can provide more code to be more clear , but this is the last destination i am trying to find a help

**Comment by jpuri** [comment]
@norayr93 : this does not seems to be issue with the editor. Just wondering does editor has selection after refresh ?
