### ISSUE TITLE
Link query string not supported

### ISSUE THREAD

**Issue by sanjitbauli** [jpuri/react-draft-wysiwyg#778]
when i try to add some link with query string
https://www.example.com?q=somevalue
it is removing the part ?q=somevalue

**Comment by jpuri** [comment]
![screenshot 2019-02-09 at 2 59 55 pm](https://user-images.githubusercontent.com/2182307/52519038-6181b200-2c7b-11e9-9ca5-2d386397e1dc.png)

I could not replicate the issue in docs.

**Comment by sanjitbauli** [comment]
@jpuri - My bad, the exact scenario is i am unable to add query string when using mailto: link
example:
mailto:info@example.com?Subject=This%20is%20a%20subject
What it does is, it open default mail and pre-fill subject. Its a standard behavior.

**Comment by sanjitbauli** [comment]
After updating the package and using linkCallback problem got resolved.
