### ISSUE TITLE
> sign added when embed something.

### ISSUE THREAD

**Issue by ZeroCho** [jpuri/react-draft-wysiwyg#78]
I added youtube in your demo.
![chrome_2016-11-25_06-35-22](https://cloud.githubusercontent.com/assets/10962668/20610206/9e8af1d4-b2d9-11e6-92f7-75c4a3dc629f.png)
In front of iframe, `>` sign is added, and this blocks rest of HTML from rendering normally.

also, can I change that **315px** to other number?

**Comment by jpuri** [comment]
@ZeroCho: I will fix the issue of `<` appearing very soon.

I plan to add feature for user to be able to set size of image and embedded media. I will do that soon. For now may be you can clone draftjs-to-html repo and change this `315px` there.

**Comment by jpuri** [comment]
@ZeroCho: I am not facing this issue of extra `>`.
![screen shot 2016-11-25 at 11 50 57 am](https://cloud.githubusercontent.com/assets/2182307/20616107/a7df8570-b305-11e6-9777-88a74f051e8a.png)

Can you plz make sure that you use latest version of the repo for HTML generation.

**Comment by ZeroCho** [comment]
Thank you!
What i meant is when I saved that result html with '>', due to '>'  rest html got broke. This will be fixed if you fix >

Thanks again!

**Comment by jpuri** [comment]
@ZeroCho: please install draftjs-to-html version: 0.3.9, I just published it and it has the fix.

**Comment by jpuri** [comment]
Thanks @ZeroCho: for bringing up the issue. I created a separate task for resize of embedded media, I will work on that soon. This issue should be fixed now. Plz close after you test it.

**Comment by ZeroCho** [comment]
@jpuri Thank you, it is fixed.
