### ISSUE TITLE
jest tests with snapshots broken due to random `id`, `aria-*` and `data-*` attributes on each test run

### ISSUE THREAD

**Issue by JustFly1984** [jpuri/react-draft-wysiwyg#780]
I'm setting up testing environment with jest, and I have issues with testing components on top of
```
import { Editor } from 'react-draft-wysiwyg'
```

I have this test output:
```
    Received value does not match stored snapshot "<Labeled
Editor /> LabeledEditor renders correctly 1".

    - Snapshot
    + Received

    @@ -7,11 +7,11 @@
        >
          labelText
          <div
            aria-label="rdw-wrapper"
            className="inputClassName rdw-editor-wrapper"
    -       id="rdw-wrapper-5728"
    +       id="rdw-wrapper-9281"
            onBlur={[Function]}
            onClick={[Function]}
            style={
              Object {
                "boxSizing": "border-box",
    @@ -425,11 +425,11 @@
              >
                <div
                  className="DraftEditor-editorContainer"
                >
                  <div
    -               aria-describedby="placeholder-87un8"
    +               aria-describedby="placeholder-3m0fk"
                    aria-expanded={null}
                    aria-label="rdw-editor"
                    autoCapitalize="off"
                    autoComplete="off"
                    autoCorrect="off"
    @@ -472,19 +472,19 @@
                      data-contents="true"
                    >
                      <div
                        className=""
                        data-block={true}
    -                   data-editor="87un8"
    -                   data-offset-key="alv7c-0-0"
    +                   data-editor="3m0fk"
    +                   data-offset-key="1o5l9-0-0"
                      >
                        <div
                          className="public-DraftStyleDefault-block public-DraftStyleDefault-ltr"
    -                     data-offset-key="alv7c-0-0"
    +                     data-offset-key="1o5l9-0-0"
                        >
                          <span
    -                       data-offset-key="alv7c-0-0"
    +                       data-offset-key="1o5l9-0-0"
                            style={Object {}}
                          >
                            <span
                              data-text="true"
                            >

      38 |       .toJSON()
      39 | 
    > 40 |     expect(tree).toMatchSnapshot()
         |                  ^
      41 |   })
      42 | })
      43 | 

      at Object.toMatchSnapshot (src/components/common/labeled-editor.test.js:40:18)

 › 1 snapshot failed.
```

Is there any way to fix this behavior by passing some predictable prop value?

**Comment by jpuri** [comment]
@JustFly1984 : try using these props"

https://github.com/jpuri/react-draft-wysiwyg/blob/master/src/Editor/index.js#L79

https://github.com/jpuri/react-draft-wysiwyg/blob/master/src/Editor/index.js#L83

This ones appears to be specific to draftjs
```
                          <span
    -                       data-offset-key="alv7c-0-0"
    +                       data-offset-key="1o5l9-0-0"
                            style={Object {}}
                          >
```

**Comment by jpuri** [comment]
Check this for last one: https://github.com/facebook/draft-js/issues/1199

**Comment by juniorjp** [comment]
The following fixed `data-offset-key` random key errors for me:
`jest.mock("draft-js/lib/generateRandomKey", () => () => "123");`

**Comment by chipcullen** [comment]
Just in case anyone else ends up here via googling, @juniorjp 's solution works - you just have to put that `jest.mock("draft-js/lib/generateRandomKey", () => () => "123");` in your _test file_ (e.g. storyshots.test.js) not your storybook. (That took me a while to figure out)

**Comment by andreluisce** [comment]
the solution for the `id="rdw-wrapper-XXXX` is to mock the Math.random method. As Editor uses Math.random to generate the ID ([code](https://github.com/jpuri/react-draft-wysiwyg/blob/1c8e85c45e466884b1e4494b50242442de27aa6e/src/Editor/index.js#L106)).

An example to mock Math.random you can find [here](https://stackoverflow.com/a/43532567/1161791)

**Comment by pentaphobe** [comment]
**:warning: Future people:** Save yourself some painful time and don't bother trying to mock `Math.random` - it's used by other parts of Jest and will cause funky behaviour including hanging tests.

I unfortunately used the above suggestion alongside a bunch of test updates and it took quite a while to realise what was broken.

Read @juniorjp and @chipcullen comments for a solution which works

**Comment by matttk** [comment]
Hmm this doesn't seem to be working for me.

I tried:

```
import initStoryshots from "@storybook/addon-storyshots";
import { mount } from "enzyme";
import { createSerializer } from "enzyme-to-json";

initStoryshots({
  renderer: mount,
  snapshotSerializers: [createSerializer()]
});

jest.mock("draft-js/lib/generateRandomKey", () => () => "123");
```

And:

```
import initStoryshots from "@storybook/addon-storyshots";
import { mount } from "enzyme";
import { createSerializer } from "enzyme-to-json";

jest.mock("draft-js/lib/generateRandomKey", () => () => "123");

initStoryshots({
  renderer: mount,
  snapshotSerializers: [createSerializer()]
});
```

But I still get the random ids every time.

e.g.

```
<i
  className="la la-angle-down"
    -  id="id-rywelh6q39"
    +  id="id-cxmg5c3iy1v"
  style={
```

**Comment by Mheaus** [comment]
My solution was to do this in a global jest config file.

```
jest.mock('@react-aria/ssr/dist/main', () => ({
  ...jest.requireActual('@react-aria/ssr/dist/main'),
  useSSRSafeId: () => 'react-aria-generated-id',
}));
```

**Comment by arackaf** [comment]
@Mheaus's solution is the modern, updated one. Let's hope Jest doesn't go changing the structure of their builds :D

**Comment by arackaf** [comment]
@Mheaus that's really, really clever, and much less brittle. Stick it a util function somewhere and ... man I think I'm gonna steal this. Angry I didn't think of it. Thanks SO much!

**Comment by devinkulanjith** [comment]
@Mheaus Thank you so much

**Comment by devinkulanjith** [comment]
@Mheaus  

  it('Testing po number snapshot tests', async () => {
    const { container } = render(<PoNumberSelector maxPOLength={20} />)

    expect(container).toBeDefined()
    replaceReactAriaIds(container)
    expect(container).toMatchSnapshot()
  })
   
  this one is not working, could you explain what should i place after calling "replaceReactArialds(container)"? ,
