### ISSUE TITLE
Image - alignment like a text

### ISSUE THREAD

**Issue by pavel-sindelka** [jpuri/react-draft-wysiwyg#784]
Hello, is it possible to focus and align an image like a text? If so how?

**Comment by jpuri** [comment]
![screenshot 2019-02-11 at 11 02 45 pm](https://user-images.githubusercontent.com/2182307/52581618-305ada80-2e51-11e9-9ca8-87a25a891b22.png)

@pavel-sindelka : above option will appear on hover.

**Comment by pavel-sindelka** [comment]
@jpuri Thanks, but this I know... But I want to hide this options, focus an image and align it by alignment controls like a text.

**Comment by jpuri** [comment]
Hey @pavel-sindelka , this is not supported :(
