### ISSUE TITLE
Give user option to add custom images to toolbar options.

### ISSUE THREAD

**Issue by jpuri** [jpuri/react-draft-wysiwyg#8]

**Comment by jpuri** [comment]
The option has now been added.

**Comment by jpuri** [comment]
This has already been completed.

**Comment by mbrnwsk** [comment]
Hi,

It would be nice to have an option to pass <i />, not only images. Would you consider this? Or maybe there is a way to achieve this?

**Comment by jpuri** [comment]
Hey @mbrnwsk, you can achieve a lot of customization using css class and image already. Also editor supports adding custom options to toolbar.

Atm , its not possible to pass whole customize toolbar button for existing toolbar options.
