### ISSUE TITLE
how to load content from the file into this editor 

### ISSUE THREAD

**Issue by NiyazMulla** [jpuri/react-draft-wysiwyg#811]

**Comment by space11** [comment]
@NiyazMulla 

You my need to provider more information about what are You planning to achieve. Do You want to save editor state in the user browser local storage, in the data base, or as a regular file?
In any case  first you have to  serialize (and deserialize when loading) the contents of the editor. 
You can do it by using provided by Draft.js functions:

```js
import {convertFromRaw, convertToRaw} from 'draft-js';
...

**Comment by NiyazMulla** [comment]
> @NiyazMulla
> 
> You my need to provider more information about what are You planning to achieve. Do You want to save editor state in the user browser local storage, in the data base, or as a regular file?
> In any case first you have to serialize (and deserialize when loading) the contents of the editor.
> You can do it by using provided by Draft.js functions:
> 
> ```js
> import {convertFromRaw, convertToRaw} from 'draft-js';
> ...
> ```

**Comment by NiyazMulla** [comment]
> @NiyazMulla
> 
> You my need to provider more information about what are You planning to achieve. Do You want to save editor state in the user browser local storage, in the data base, or as a regular file?
> In any case first you have to serialize (and deserialize when loading) the contents of the editor.
> You can do it by using provided by Draft.js functions:
> 
> ```js
> import {convertFromRaw, convertToRaw} from 'draft-js';
> ...
> ```

my application in is hitting api returning the data but  not loading  the content of data into that editor,
so how can i do this i am new in react js 
thank you

**Comment by HJain13** [comment]
@NiyazMulla What is the type of Content that you are trying to load? If its something which the editor can understand directly (**Highly Unlikely**), then you should change your code from

```JS
this.setState({data:res})
this.state.editorstate=this.setState({data:res});
```

to 

```JS
this.setState({data: res, editorstate: res})
```

There are multiple problems with your original code:
* `this.setState({data:res})` doesn't return anything
   So `this.state.editorstate` is being basically set as `null`
* `this.state.foo = bar`
   Setting the state this way should be avoided
