### ISSUE TITLE
Developer to be able to update editor editor content.

### ISSUE THREAD

**Issue by jpuri** [jpuri/react-draft-wysiwyg#84]
Its very probable scenario for developer to require to reset / change editor content. Currently editor only allow initializing the content.

**Comment by ZeroCho** [comment]
This will be aweseome!

**Comment by 949mac** [comment]
I'm experiencing an issue when re-generating the view in a Modal window. This would be terrific.

**Comment by 949mac** [comment]
Actually, I was able to solve this. I'm using a single Editor displayed in a Modal window and passing the props from the child back to the parent to reset the state and everything appears to be working as expected now. I also switched from a vanilla Bootstrap modal implementation to using react-modal. I think the primary issue I was having before was that my vanilla Modal wasn't unmounting properly (which contains the editor) and was only being hidden. For this case, I no longer need to update the content of the editor like I thought I did previously. I hope this helps anyone else who might be experiencing the same issue with modals.

**Comment by jpuri** [comment]
React inputs typically have controlled and un-controlled modes. The advantage with controlled mode is that developer has complete control over the changes in state of input.

I would typically like to have this kind of behavior for the editor also, but currently in case of react-draft-wysiwyg the editor content is exported in form of `RawDraftContentState`. Conversion from `RawDraftContentState` to `EditorState` is expensive operation and doing it on each change can be performance overhead.

I am considering to export / re-hydrate editor content in form of `EditorState` and now `RawDraftContentState` so that editor can be made controlled also without loss in performance. But this would be a breaking change - thus I am postponing it for 2.0.

For now I am adding another property `contentState` to react-draft-wysiwyg whenever this changes  the editor content will be reset. It can potentially be used to change editor to controlled component but that can have performance over-heads. `initialContentState` is now redundant and I will consider removing it in 2.0 release.

**Comment by jpuri** [comment]
Change has been released closing the issue.
