### ISSUE TITLE
react warning

### ISSUE THREAD

**Issue by luisrudge** [jpuri/react-draft-wysiwyg#86]
![image](https://cloud.githubusercontent.com/assets/941075/20648187/def9874a-b486-11e6-90a6-afc526a07937.png)

> Warning: A component is `contentEditable` and contains `children` managed by React. It is now your responsibility to guarantee that none of those nodes are unexpectedly modified or duplicated. This is probably not intentional.

**Comment by jpuri** [comment]
This warning was kind of un-avoidable. As I remember it happens with mentions. I will still again look into it in depth.

**Comment by jpuri** [comment]
I looked into this again again this is kind-of un-avoidable. Ref: https://www.reddit.com/r/reactjs/comments/2wnge4/how_to_disable_react_warnings/

I am closing this issue.

**Comment by nss213** [comment]
Might this help? https://github.com/facebook/react/pull/6112
