### ISSUE TITLE
Custom inline style is not getting converted to html

### ISSUE THREAD

**Issue by abhilashkumar002** [jpuri/react-draft-wysiwyg#882]
Hi @jpuri First of all thank you for all your work on this library, its excellent. 
I am facing a issue as follows.
I am passing customStyleMap to Editor. It is working in editor however it's not getting converted to html.
custom style:

`const CustomStyleMap = {
  redBackground: {
    backgroundColor: 'red',
    fontSize:"20px",
  },
  greenBackground: {
    backgroundColor: 'green'
  }
};`

Editor:
`<Editor
          editorState={editorState}
          wrapperClassName="demo-wrapper"
          editorClassName="demo-editor"
          onEditorStateChange={this.onEditorStateChange}
          onChange={this.onContent}
          toolbar={{
            options: ['history','inline', 'blockType', 'fontSize', 'fontFamily', 'list', 'textAlign', 'colorPicker', 'link', 'embedded', 'emoji', 'image', 'remove', ],
            inline: { inDropdown: true},
            
          }}
          toolbarCustomButtons={[<CustomOption handleToggle={this.handleToggle}/>]}
          customStyleMap = {CustomStyleMap}
        />`

Handling toggle:
`  handleToggle = () => {
    console.log("here")
    this._handleChange(
      RichUtils.toggleInlineStyle(
        this.state.editorState,
        "greenBackground"
      )
    )
  }`

you can see here in dom it's there:
![issue_1](https://user-images.githubusercontent.com/35776269/68129236-35ac0800-ff3f-11e9-9cfd-56e0e826dc32.png)

Here its rendering in editor but not after i convert it to html.
![issue_2](https://user-images.githubusercontent.com/35776269/68129243-3b095280-ff3f-11e9-8f33-098eea358c6d.png)

**Comment by Leka74** [comment]
Have you managed to solve this?
