### ISSUE TITLE
SSR window is not defined

### ISSUE THREAD

**Issue by hnaoufal** [jpuri/react-draft-wysiwyg#893]
Hey guys,

after the update from 1.13.2 to 1.14.0 I get the following error:
ReferenceError: window is not defined

So I assume it doesn't support the building in SSR environments. Can you please check the error and make sure this is fixed? I can also create a pull Request if you like

**Comment by jpuri** [comment]
@hnaoufal : i will appreciate a PR. Thx

**Comment by hnaoufal** [comment]
Ok I had a quick look at it. It seems like it is a sub dependency of your library which is causing this issue. I will check maybe the next week what is exactly causing the problem. In the dev mode it works but when compiled it throws the error.

To give you more details:
/node_modules/react-draft-wysiwyg/dist/react-draft-wysiwyg.js:1:393

which points to:
require("draft-js"),require("immutable")):e.reactDraftWysiwyg=t(e.react,e["draft-js"],e.immutable)}(window,function(n,o,r){return c={},i.m=a=[function(e,t,n){e.exports=n(9)()},function(e,t){e.exports=n},function(e,t,n){var o;

This window there is doing the problem. If you have a hint, I could have a look at it but for now I can't plan this in our sprint.

I think for now I will just do dynamic loading of the component to avoid SSR problems.

**Comment by hnaoufal** [comment]
If someone is facing the same problem use the following example:

import dynamic from 'next/dynamic'; // (if using Next.js or use own dynamic loader)
const Editor = dynamic(() => import('react-draft-wysiwyg').then(mod => mod.Editor)) as Editor;

I think you can close this issue because this is not directly connected to your module.

**Comment by vedovato** [comment]
Adding my 2 centshere. Also had to set ssr option to false

const Editor = dynamic(
  () => import('react-draft-wysiwyg').then(mod => mod.Editor),
  { ssr: false }
)

**Comment by pradipvadher** [comment]
Can you pls tell me where to place this code? @vedovato

**Comment by vedovato** [comment]
That's the import statement you put at the beginning of file, @pradipvadher.
Use it instead of `import Editor from import 'react-draft-wysiwyg'`

**Comment by otuleja** [comment]
Thank you, everyone... this worked for me.

**Comment by jonathanshell** [comment]
Does anyone have a solution for this within Gatsby? It does not have a comparative `dynamic` functionality...

**Comment by devwhatoplay** [comment]
Module parse failed: Unexpected token (19:9)
You may need an appropriate loader to handle this file type.
| 
| var Editor = dynamic(function () {
>   return import("react-draft-wysiwyg").then(function (mod) {
|     return mod.Editor;
|   });`

I applied the code above but still getting this error

**Comment by KumarAbhirup** [comment]
The above solutions aren't working for me. I get this error: #1005

**Comment by chfritz** [comment]
I think I found a workaround that also enables SSR:

```js
window = (typeof window != 'undefined' ? window : {});
let DraftEditor;
import('react-draft-wysiwyg').then(mod => DraftEditor = mod.Editor);
```

With that I'm able to do server-side rendering in the usual way:
```js
ReactDOMServer.renderToString(<Editor contentState={myContent} readonly toolbarHidden/>);
```

**Comment by raoufswe** [comment]
this worked for me 

`
import dynamic from "next/dynamic"
import "../node_modules/react-draft-wysiwyg/dist/react-draft-wysiwyg.css"

const Editor = dynamic(() => import("react-draft-wysiwyg").then((mod) => mod.Editor), { ssr: false })

export default Editor

`

**Comment by beulahpt** [comment]
How to solve this in react-js without next?

**Comment by VadSiam** [comment]
> How to solve this in react-js without next?

I did it by this way:

`const [ssrReady, setSsr] = React.useState<boolean>(false);

  React.useEffect(() => {
    if (typeof window !== 'undefined') {
      setSsr(true);
    }
  }, []);

 if (!ssrReady) {
  return <div>Loading...</div>
} 

return <ComponentWithDraftWYSIWYG />
`

**Comment by kachar** [comment]
> Adding my 2 cents in here. Also had to set ssr option to false
> 
> ```
> const Editor = dynamic(
>   () => import('react-draft-wysiwyg').then(mod => mod.Editor),
>   { ssr: false }
> )
> ```



Here's a typescript version of it

```shell
yarn add --dev @types/draft-js @types/react-draft-wysiwyg
yarn add --dev @types/draft-js @types/react-draft-wysiwyg
```

```tsx
import dynamic from 'next/dynamic'
import { EditorProps } from 'react-draft-wysiwyg'

const Editor = dynamic<EditorProps>(
  () => import('react-draft-wysiwyg').then((mod) => mod.Editor),
  { ssr: false}
)

```

**Comment by aboutonlineblog** [comment]
> Adding my 2 cents in here. Also had to set ssr option to false
> 
> ```
> const Editor = dynamic(
>   () => import('react-draft-wysiwyg').then(mod => mod.Editor),
>   { ssr: false }
> )
> ```

This is what works for me

**Comment by KhoiNguyenDo1991** [comment]
For those who facing the problem: "that the type of the function that you are passing to the dynamic() function is not compatible with the type that the function expects..."

const Editor = dynamic<EditorProps>(
  async () => {
    const mod = await import('react-draft-wysiwyg');
    return { default: mod.Editor as unknown as ComponentType<EditorProps> };
  },
  { ssr: false }
);

**Comment by KhoiNguyenDo1991** [comment]
and for those who facing the warning: "React does not recognize the `editorState` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `editorstate` instead. If you accidentally passed it from a parent component, remove it from the DOM element.)"
If you try to add a custom button on the toolbar.  please wrap it with <React.Fragment>
