### ISSUE TITLE
Warning: componentWillMount has been renamed, and is not recommended for use

### ISSUE THREAD

**Issue by hiranvikas77** [jpuri/react-draft-wysiwyg#898]
My Current react version: 16.8.6

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: i, o, r

**Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.**

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

**Comment by crscaballero** [comment]
Just so you know, has fixed on 1.14.1 version

**Comment by hiranvikas77** [comment]
@crscaballero thanks for info. Just checked and seems it's fixed!
