### ISSUE TITLE
Controlled/Uncontrolled link target error

### ISSUE THREAD

**Issue by luke-j** [jpuri/react-draft-wysiwyg#90]
The `keydown` and `blur` events on the link target input field causes the following error:

<img width="482" alt="screen shot 2016-11-30 at 2 30 19 pm" src="https://cloud.githubusercontent.com/assets/6657011/20738807/06faa9f6-b70a-11e6-9570-df21de865dfa.png">

**Comment by jpuri** [comment]
Yep this is coz controlled inputs still behave as un-controlled till value is undefined - that is actually issue with React. Not avoidable.

**Comment by jpuri** [comment]
This is yet another un-avoidable react warnings :(

I am closing this issue.

**Comment by chenyehai** [comment]
I set hyper link, and cause this error. And then ,the onBlur callback is failed， what can I do ?

**Comment by jpuri** [comment]
@chenyehai: What failure are you facing for onBlur ?
