### ISSUE TITLE
onEditorStateChange is causing toolbox to change and image upload to disable

### ISSUE THREAD

**Issue by shwetasabne** [jpuri/react-draft-wysiwyg#911]
Hello, 

I am running into a rather weird problem. I have a very basic editor box and when I start typing into the input, the toolbox expands and the option to upload "File" vanishes. 

Please see the gif elaborating the issue:
![react-draft-wsiwyg-image-upload-issue](https://user-images.githubusercontent.com/6800111/71775970-26553500-2f57-11ea-849e-02b2cb03a06a.gif)

I am unable to understand what is causing this issue and what am I doing wrong ! Any help / suggestion / ideas are most welcome !

My component code is as below:
```javascript
import React, {Component} from 'react';
import {EditorState, convertToRaw} from "draft-js";
import {Editor} from "react-draft-wysiwyg"
import '../../node_modules/react-draft-wysiwyg/dist/react-draft-wysiwyg.css';
import draftToHtml from 'draftjs-to-html';

function uploadImageCallBack(file) {
  return new Promise(
    (resolve, reject) => {
      const xhr = new XMLHttpRequest();
      xhr.open('POST', 'https://api.imgur.com/3/image');
      xhr.setRequestHeader('Authorization', 'Client-ID 917ef1c53d1ec30');
      const data = new FormData();
      data.append('image', file);
      xhr.send(data);
      xhr.addEventListener('load', () => {
        const response = JSON.parse(xhr.responseText);
        resolve({data: {link: response.url}})
      });
      xhr.addEventListener('error', () => {
        const error = JSON.parse(xhr.responseText);
        reject(error);
      });
    }
  );
}

class EditorContainer extends Component {
  state = {
    editorState: EditorState.createEmpty()
  }

  onEditorStateChange = (editorState) => {
    const currentContent = draftToHtml(convertToRaw(this.state.editorState.getCurrentContent()))
    console.log(currentContent)
    this.setState({
      editorState,
    });
  };

  render(){
    const { editorState } = this.state;
    return (
      <div>
        <Editor
        editorState={editorState}
        wrapperClassName="editorWrapper"
        toolbarClassName="toolbarWrapper"
        onEditorStateChange={editorState => this.onEditorStateChange(editorState)}
        toolbar={{
          options: ['inline', 'blockType', 'fontSize', 'list', 'textAlign', 'image', 'history'],
          image: {
            urlEnabled: true,
            uploadEnabled: true,
            uploadCallback: uploadImageCallBack,
            alt: { present: true, mandatory: true }
          }
        }}
      />
    </div>
    )
  }
}

export default EditorContainer;
```

**Comment by SilverMagnolia** [comment]
I have the same issue. When the text area gets focused, the toolbar options I set is ignored and the tool box expands. The bug happens when I set the 'editorState' props. It never happens when initialEditorState is set or neither of editorState and initialEditorState are set.

**Comment by NatasXWY** [comment]
Maybe a code miss.
In 'src/Editor/index.js(81)'
`const toolbar = mergeRecursive(defaultToolbar, toolbar);`
toolbar is reused.
Webpack build result is 
`var _toolbar2 = Object(_utils_toolbar__WEBPACK_IMPORTED_MODULE_10__["mergeRecursive"])(_config_defaultToolbar__WEBPACK_IMPORTED_MODULE_18__["default"], _toolbar2);`
'_toolbar2' is the customer setting，but current line is 'undefined',
toolbar be reset with default value.

Solution : 
define the  toolbar setting object
`
<Editor
      toolbar={toolbarDefine}
/>
`
because 'if (toolbar !== prevProps.toolbar) {'     src/Editor/index.js (80)

Sorry, my english is not well. 
只能这么写了，以后会努力学英文的。

**Comment by shwetasabne** [comment]
Thanks for the tip @NatasXWY - I will try and let you know if it works ! thanks again !

**Comment by shwetasabne** [comment]
@NatasXWY : I updated my code to this, but it still does not work and the bug persists. The only time, this bug goes away is if I remove the `onEditorStateChange` props; but that cannot be the solution since I need that callback to be fired when content changes.

**Comment by shwetasabne** [comment]
@NatasXWY : oh yes you are right ! that solved the issue for me. Thank you :)

**Comment by jpuri** [comment]
Using `react-draft-wysiwyg@1.14.4` should fix this issue.
