### ISSUE TITLE
Impossible to hide / reorder options from toolbar

### ISSUE THREAD

**Issue by svervoort** [jpuri/react-draft-wysiwyg#914]
Good day,

It seems impossible to hide / re-order the options in the toolbar. I have tried to re-create example 10 (https://jpuri.github.io/react-draft-wysiwyg/#/demo), but the full set of options still show. 

  ```
<Editor
    wrapperClassName="demo-wrapper"
    editorClassName="demo-editor"
    toolbar={{
      inline: { inDropdown: true },
      list: { inDropdown: true },
      textAlign: { inDropdown: true },
      link: { inDropdown: true },
      history: { inDropdown: true }
    }}
  />
```

![Schermafbeelding 2020-01-07 om 21 22 59](https://user-images.githubusercontent.com/5927707/71926569-e75ff300-3193-11ea-91ca-448bb6d35634.png)

Maybe I miss something, but there seems to be no way to customise the options. I could hide options through CSS, but that does not solve the re-order problem.

Thank you.

**Comment by prakriti89** [comment]
I have the same problem. I try to only show certain toolbar options but its showing everything.
```
<Editor
        editorState={editorState}
        onEditorStateChange={e => setEditorState(e)}
        toolbar={{
          options: ["fontSize", "inline", "list", "history"],
          fontSize: {
            options: [16, 18, 22, 26, 30]
          },
          inline: {
            options: ["bold", "italic", "underline", "strikethrough"]
          }
        }}
/>
```

**Comment by geodotka** [comment]
I have the same problem in version `1.14.3`. After editor is focused, full toolbar appears. In version `1.13.2` everything works correctly.

**Comment by nlopin** [comment]
It looks like the issue happens only in controlled editor

**Comment by jpuri** [comment]
Plz do not use latest version `1.14.3`, I will soon fix this issue.

**Comment by svervoort** [comment]
Awesome @nlopin. Now we wait until your updates gets merged in the master?
Thanks again.

**Comment by NatasXWY** [comment]
See issue #911

**Comment by nlopin** [comment]
@jpuri could you take a look at my PR? looks like a lot of people have troubles with the current version

**Comment by jpuri** [comment]
`react-draft-wysiwyg@1.14.4` has the fix for issue.

**Comment by svervoort** [comment]
![Schermafbeelding 2020-01-13 om 09 22 42](https://user-images.githubusercontent.com/5927707/72241168-6a46da80-35e6-11ea-8edf-572a1ac361c8.png)

Same code, after the update. Thanks guys.
