### ISSUE TITLE
ReadOnly mode?

### ISSUE THREAD

**Issue by devnetf** [jpuri/react-draft-wysiwyg#94]
Does have readonly mode like https://facebook.github.io/draft-js/docs/api-reference-editor.html#readonly?  

I want to display the editor's content to the user but not letting them edit. I try to avoid using dangerouslySetInnerHTML.

**Comment by jpuri** [comment]
@devnetf: This is important feature I missed, its smaller change I will add it really soon hopefully today.

**Comment by jpuri** [comment]
Fix is already there in develop branch now.

**Comment by jpuri** [comment]
Change has been released closing the issue.

**Comment by devnetf** [comment]
Thanks for the quick reply! It still doesn't work for me in release 1.1.3. I had a quick read on the pull-request. It seems that there is at least one typo:
`            ref={this.setEditorReference}
            onTab={this.onTab}
            tabIndex={tabIndex}
            readOnly={readOnly}
            readOnly={readOnly}
`
ie readOnly line appeared twice.
