### ISSUE TITLE
Suggestion dropdown is not coming out

### ISSUE THREAD

**Issue by parthipan15** [jpuri/react-draft-wysiwyg#984]
![Capture](https://user-images.githubusercontent.com/44926524/85993567-cff11c80-b9f6-11ea-8c2f-d64701785f6c.PNG)

The Suggestion dropdown is not coming out

**Comment by mbouzi** [comment]
Having the same issue

**Comment by Abdulrehmanharisdev** [comment]
@parthipan15  how you solve this issue ?
