### ISSUE TITLE
Integration with formik

### ISSUE THREAD

**Issue by oikantik** [jpuri/react-draft-wysiwyg#985]
Anyone looking to integrate with Formik, and having trouble, can take a look at this dirty coding of mine :)

RichTextEditor.js

```
import React, { useState, useEffect } from "react";
import { EditorState, convertToRaw, ContentState } from "draft-js";
import { Editor } from "react-draft-wysiwyg";
import "react-draft-wysiwyg/dist/react-draft-wysiwyg.css";
import draftToHtml from "draftjs-to-html";
import htmlToDraft from "html-to-draftjs";

const RichTextEditor = ({ setFieldValue, value }) => {
  const [editorState, setEditorState] = useState(EditorState.createEmpty());

  const prepareDraft = value => {
    const draft = htmlToDraft(value);
    const contentState = ContentState.createFromBlockArray(draft.contentBlocks);
    const editorState = EditorState.createWithContent(contentState);
    setEditorState(editorState);
  };
  useEffect(() => {
    value && prepareDraft(value);
  }, [value]);

  const onEditorStateChange = editorState => {
    const forFormik = draftToHtml(
      convertToRaw(editorState.getCurrentContent())
    );
    setFieldValue("body", forFormik);
    setEditorState(editorState);
  };
  return (
    <div>
      <Editor
        editorState={editorState}
        wrapperClassName="demo-wrapper"
        editorClassName="demo-editor"
        onEditorStateChange={onEditorStateChange}
      />
    </div>
  );
};

export default RichTextEditor;

```

App.js

```
import React from "react";
import "./styles.css";
import { Formik, Field } from "formik";
import RichTextEditor from "./RichTextEditor";

export default function App() {
  return (
    <div className="App">
      <Formik
        onSubmit={e => console.log(e)}
        initialValues={{
          body: "<p>It works</p>"
        }}
      >
        {({ handleSubmit, setFieldValue, values }) => (
          <form onSubmit={handleSubmit}>
            <Field
              value={values.body}
              name="body"
              component={RichTextEditor}
              setFieldValue={setFieldValue}
            />
            <input type="submit" value="submit" />
          </form>
        )}
      </Formik>
    </div>
  );
}

```

Sandbox:
https://codesandbox.io/s/gifted-leakey-f5v79?file=/src/App.js

**Comment by Yossri21** [comment]
in The component Editor.js 

    import { useField } from "formik";
    const [field, meta] = useField(props.name);
    const error = meta.touched && meta.error;

I added bellow <Editor ... /> 

    {meta.touched && meta.error && (
          <FormHelperText>{error}</FormHelperText>
        ) }

In the page where I used the Editor
when click in the editor , the value will be by default `<p></p>` and length 8 so the test of dirty ll be true

    
    <EditorDraft
                  name="value"
                  style={{ maxHeight: '200px' }}
                  // when click in the editor , the value will be by default <p></p> and length 8
                  handleChange={v => {
                    if (v.length > 8) {
                      setFieldValue('value', v);
                    } else {
                      setFieldValue('value', '');
                    }
                  }}
                  defaultValue={values.value}
                  toolbar={{
                    options: [
                      'inline',
                      'blockType',
                      'fontSize',
                      'fontFamily',
                      'list',
                      'textAlign',
                      'colorPicker',
                      'remove',
                      'history',
                    ],
                  }}
                />
